### ISSUE TITLE
Unsupported machine type

### ISSUE THREAD

**Issue by mauromorales** [dmacvicar/terraform-provider-libvirt#10]
When running `terraform apply` with the example `libvirt.tf` I get the following error:

```
Error applying plan:

1 error(s) occurred:

* libvirt_domain.terraform_test: Error crearing libvirt domain: [Code-1] [Domain-10] internal error: process exited while connecting to monitor: 2016-04-05T09:56:21.548490Z qemu-system-x86_64: -msg timestamp=on: Unsupported machine type
Use -machine help to list supported machines!
```

It seems to be caused because the defined machine `pc-i440fx-2.4` in `domain_def.go` is not there for the following libvirt version:

```
$ virsh --version
1.2.18.2
```

Changing the value to an existing machine fixes the problem as expected.

**Comment by mikewaters** [comment]
I believe you need qemu 2.4 for the `pc-i440fx-2.4` machine type.

**Comment by dmacvicar** [comment]
I want to keep this provider simple and not expose all qemu features into the configuration but to give a more "cloud" feel.
At some point I even thought about using the standard EC2/OpenStack machine sizes as shortcuts.

But what we can do is to use [`virConnectGetDomainCapabilities`](https://libvirt.org/html/libvirt-libvirt-domain.html#virConnectGetDomainCapabilities) to get the machine type of the host and use that.

**Comment by mauromorales** [comment]
Seems to work fine under Leap :)

**Comment by dmacvicar** [comment]
great to hear that!
