### ISSUE TITLE
Support new modular libvirt daemons

### ISSUE THREAD

**Issue by michaelbeaumont** [dmacvicar/terraform-provider-libvirt#1025]
### Provider and libvirt versions

```sh
$ terraform-provider-libvirt -version
0.7.1
```

libvirt `9.5.0`

___

### Setup

There's [a new modular architecture for the libvirt daemons](https://libvirt.org/daemons.html#architectural-options) that's not supported by this provider.

### Steps to Reproduce Issue

There is no longer a `/var/run/libvirt/libvirt-sock` with this setup, so any attempt to use the provider via the unix socket fails.

**Comment by michaelbeaumont** [comment]
Actually [there's now `virtproxyd` as described here](https://libvirt.org/daemons.html#switching-to-modular-daemons) that provides the old socket. It works after enabling that socket and service!

**Comment by kastl-ars** [comment]
Just stumbled upon this. In your case, this is valid as you like to connect via SSH. But enabling the proxy on local machine just to use this provider seems like an ugly workaround.

So this would be nice to have without the proxy workaround.

**Comment by michaelbeaumont** [comment]
@kastl-ars I don't know, I think it's not really a workaround, it's the official way to get a socket interface

**Comment by kastl-ars** [comment]
> @kastl-ars I don't know, I think it's not really a workaround, it's the official way to get a socket interface

Hi @michaelbeaumont 

the documentation says this:

> If connections from remote hosts need to be supported the proxy daemon must be enabled and started

This explicitly mentions "remote hosts". That is way I called it a workaround.

Local connections using virsh are working even with the proxy daemon disabled, as there are lots of sockets available. My guess is that the libvirt provider "just needs to be told" to look in a different place for the socket...

**Comment by michaelbeaumont** [comment]
I'm not enough of an expert in libvirt here but from my understanding, the issue is that [there are multiple sockets now](https://libvirt.org/daemons.html#modular-sockets). Is it clear that we only need say, the qemud socket? I don't know. Also we'd need https://github.com/digitalocean/go-libvirt/issues/171 anyway, because the API calls happen in `go-libvirt`.
