### ISSUE TITLE
[FEATURE] Add more comprehensive support for ssh_config, specifically bastion hosts

### ISSUE THREAD

**Issue by memetb** [dmacvicar/terraform-provider-libvirt#1058]
### Provider and libvirt versions `9adc2521e37b0c8938330bf81111d3c633825c76-dirty`
___

Hello @dmacvicar, I've coded a new feature for the project and am opening an issue prior to submitting a WIP PR.

I have updated the code for [`ssh.go`](https://github.com/dmacvicar/terraform-provider-libvirt/blob/main/libvirt/uri/ssh.go) to add more thorough support for making use of `ssh_config` parameters.

This code change resolves the following specific and important issues: 
- inability to use a identity file other than `~/.ssh/id_rsa`
- inability to use bastion hosts as they are defined in the ssh_config file

This feature requires upgrading `ssh_config` module to v1.2.0 which is the as of now current module (is currently at v0.0.0 in the master branch). Other than this, all changes are confined to `ssh.go`.

**Comment by SimonWoidig** [comment]
This is something that we would love to see aswell - especially the proxies.

**Comment by scabala** [comment]
since #1059 was merged, I think this can be closed

**Comment by dmacvicar** [comment]
and 0.8.0 is released
