### ISSUE TITLE
test driver support

### ISSUE THREAD

**Issue by deas** [dmacvicar/terraform-provider-libvirt#1067]
### Linux distribution

n/a

### Terraform version

n/a

### Provider and libvirt versions

v0.7.6

## Checklist

n/a

## Description of Issue/Question
For testing purposes, it would be nice if the [Test "mock" driver](https://libvirt.org/drvtest.html) could be made available.

### Setup

n/a

### Steps to Reproduce Issue

Use a system without the libvirt daemon running/listening at `/var/run/libvirt/libvirt-sock`.

```
$ export LIBVIRT_DEFAULT_URI = "test:///default"
$ terraform plan
....
 Error: failed to connect: dial unix /var/run/libvirt/libvirt-sock: connect: no such file or directory
...
$ virsh list
 Id   Name   State
----------------------
 1    test   running
$

**Comment by dmacvicar** [comment]
The mock driver fakes the hypervisor, so you would anyway a libvirt socket for the client to connect to.
