### ISSUE TITLE
Implement If-Modified-Since when downloading images

### ISSUE THREAD

**Issue by inercia** [dmacvicar/terraform-provider-libvirt#109]
Our HTTP client currently downloads the image specified on `source` even when the image in the server is the same as a local copy previously downloaded.

For ths case where a local copy is already in the pool, we could perform the HTTP request with the [`If-Modified-Since`](https://developer.mozilla.org/es/docs/Web/HTTP/Headers/If-Modified-Since) header (using the [modification time](https://golang.org/pkg/os/#FileInfo) of the local image), so it would be downloaded only if the remote file has been updated.

**Comment by MalloZup** [comment]
@inercia good idea
