### ISSUE TITLE
[Domain-44] invalid argument: could not find capabilities for arch=x86_64 domaintype=kvm

### ISSUE THREAD

**Issue by fisabelle** [dmacvicar/terraform-provider-libvirt#11]
Hi.
I'm running my tests from a LVM VM and I don't have KVM nesting support.
It seems to me that I should use the QEMU emulation as reported by:
[terraform]$ virt-host-validate
  QEMU: Checking for hardware virtualization                                 : WARN (Only emulated CPUs are available, performance will be significantly limited)
  QEMU: Checking for device /dev/vhost-net                                   : WARN (Load the 'vhost_net' module to improve performance of virtio networking)
  QEMU: Checking for device /dev/net/tun                                     : PASS
   LXC: Checking for Linux >= 2.6.26                                         : PASS

It looks like I need to change the hard coded defaults and recompile the module. I'm going to try that.
I might look into the code to find how to to make that a configuration parameter. But I'm a GO-lang ignorant right now..

**Comment by fisabelle** [comment]
root@vircentos7-48 ~]# virsh list
 Id    Name                           State
----------------------------------------------------
 7     terraform_test                 running
I got a little further with the qemu / pc machine type.

But even though the VM spawns, the I/O do not work.

[root@-48 ~]# virsh console terraform_test
Connected to domain terraform_test
Escape character is ^]
error: internal error: cannot find character device <null>




2016-04-18 18:50:52.114+0000: starting up libvirt version: 1.2.17, package: 13.el7_2.4 (CentOS BuildSystem <http://bugs.centos.org>, 2016-03-31-16:56:26, worker1.bsys.centos.org), qemu version: 1.5.3 (qemu-kvm-1.5.3-105.el7_2.3)
LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin QEMU_AUDIO_DRV=spice /usr/libexec/qemu-kvm -name terraform_test -S -machine pc-i440fx-rhel7.0.0,accel=tcg,usb=off -m 512 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid 3c8fd355-bfd2-4b23-9fe6-60fb200a42d1 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-terraform_test/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -no-acpi -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -spice port=5900,addr=127.0.0.1,disable-ticketing,seamless-migration=on -vga cirrus -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3 -msg timestamp=on
((null):5911): SpiceWorker-Warning **: red_worker.c:1306:validate_surface: canvas address is 0x7fe657b26308 for 0 (and is NULL)

((null):5911): SpiceWorker-Warning **: red_worker.c:1307:validate_surface: failed on 0
((null):5911): SpiceWorker-Warning **: red_worker.c:1308:validate_surface: condition `!worker->surfaces[surface_id].context.canvas' reached
((null):5911): SpiceWorker-Warning **: red_worker.c:153:rendering_incorrect: rendering incorrect from now on: dev_destroy_primary_surface
((null):5911): SpiceWorker-Warning **: red_worker.c:9695:red_create_surface: condition `surface->context.canvas' reached

**Comment by fisabelle** [comment]
FYI.

I was able to get to the console with virt-viewer using the spice URI.
I'm not so sure why virt-manager and virsh console don't support that how of the box on RH7, they might be too old I guess. So now I'm down to the "unreadable boot disk message". Which make sense since I didn't set any disk image.

**Comment by dmacvicar** [comment]
Hi, thanks for your report! can you explain me what is a "LVM VM" ?

I just pushed a commit that does not force a certain machine type and architecture, but the provider still forces the `hvm` type.

Can you retry on master with a proper disk image to figure out if I should close this issue or not? Thanks again.

**Comment by isabellf** [comment]
I meant a KVM virtual machine, so basically, my host machine is already a virtual machine.
Thank you, I might not be able to that in the short term though.

**Comment by fisabelle** [comment]
I was able to span the VM without changing the code.
