### ISSUE TITLE
Provider ignores "running" parameter for domain

### ISSUE THREAD

**Issue by r7vme** [dmacvicar/terraform-provider-libvirt#119]
#  Version Reports:

### Distro  version of host:

Ubuntu 14.04

### Terraform Version Report

v0.8.6

### Libvirt version

1.3.1

### terraform-provider-libvirt plugin version (git-hash)

a07e21b74726d9ce443ac9332417c169b2ccd708
___
# Description of Issue/Question
Despite "running = false" domain always running.

### Setup
```
provider "libvirt" {
  uri = "qemu+ssh://root@host/system"
}

resource "libvirt_domain" "rs-removeme" {
  name = "rs-removeme"
  vcpu = 1
  memory = 4096
  running = false
}
```

### Steps to Reproduce Issue
1) Create file with state above
2) terraform apply. [See log](http://paste.openstack.org/show/603763/)

Expected result:
VM is not running

Actual result:
VM is running.

___
# Additional Infos:

No Apparmor

**Comment by dmacvicar** [comment]
Ok. I read the PR and I get it, but, I can't get where you do the connection between "running" and "destroy". A domain can be existent but running/not running. Why should setting `running = false` destroy it? Or am I misunderstanding something`

**Comment by MalloZup** [comment]
@dmacvicar : https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown

running - (Optional) Use false to turn off the instance. If not specified, true is assumed and the instance, if stopped, will be started at next apply.
