### ISSUE TITLE
volume source is not downloaded directly by target server

### ISSUE THREAD

**Issue by gtirloni** [dmacvicar/terraform-provider-libvirt#127]
### Distro  version of host:
CentOS 7.3

### Terraform Version Report
Terraform v0.9.6-dev (adfa7aedfbde60a79ab07455cf20947585d6d647)

### Libvirt version
3.2.1

### terraform-provider-libvirt plugin version (git-hash)
bb20e1a40689b4c1e33faf52ee69c2d1d9f20ae8
___
# Volume source is not downloaded directly from target server

When a volume source is specified, the libvirt provider seems to try to find the file (or download it) locally on the machine where terraform is running, as opposed to downloading it from the target server. This is very slow depending on where the TF client is running.

### Setup

```
provider "libvirt" {
  #	uri = "qemu:///system"
  uri = "qemu+libssh2://user@server/system"
}

resource "libvirt_volume" "centos_base" {
  name = "centos_base"
  source = "/var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2" # or https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
}

resource "libvirt_volume" "test_disk" {
  name = "test_disk"
  base_volume_id = "${libvirt_volume.centos_base.id}"
}

resource "libvirt_domain" "terraform_test" {
  name = "test-domain"
  memory = 4096
  vcpu = 4
  disk = {
    volume_id = "${libvirt_volume.test_disk.id}"
    scsi = "yes"
  }
}
```

### Steps to Reproduce Issue
* terraform plan
* terraform apply

### Error

```
Error applying plan:

1 error(s) occurred:

* libvirt_volume.centos_base: 1 error(s) occurred:

* libvirt_volume.centos_base: open /var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2: no such file or directory
```

```
server$ file /var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2
/var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2: QEMU QCOW Image (v2), 8589934592 bytes
```

**Comment by flavio** [comment]
This is done by design. To achieve what you wrote you should put the `CentOS-7-x86_64-GenericCloud.qcow2` into a pool known by libvirt and then define the volume inside of terraform as:

```
resource "libvirt_volume" "volume" {
  name = "test.qcow2"
  pool = "mypool"
  base_volume_name= "CentOS-7-x86_64-GenericCloud.qcow2"
}
```

This will create a `test.qcow2` disk based on the CentOS image.

**Comment by gtirloni** [comment]
Sorry, I hadn't realized that. Thank you!
