### ISSUE TITLE
consider moving to terra-farm or core?

### ISSUE THREAD

**Issue by josephholsten** [dmacvicar/terraform-provider-libvirt#131]
I don't know if libvirt is ready to start joining core, but if it is I'd like to help with the process.

If we want to not actually be in core, some folks are putting together an org like [sous-chefs](https://github.com/sous-chefs) does for chef cookbooks. Then maintainers can help each other out reviewing, merging and releasing changes. The main advantage is having more than one maintainer who can pass the torch. If that sounds interesting, the conversation is happening at https://github.com/terra-farm/meta/issues

If that doesn't sound ideal, please let me know!

**Comment by flavio** [comment]
I personally think this is an exciting idea.

IMHO the code needs some refactoring and we have to tag an initial release of the project before joining.

What do the others think about it?

**Comment by dmacvicar** [comment]
I am more in favour of identifying the cleanups needed to be in core more than an extra project.

If this umbrella would be already something active and popular, I would see things differently. At least, there is more than one person with commit access to the repo already so maintainers are not the problem.

**Comment by josephholsten** [comment]
@dmacvicar totally understand. If there's anything I can do to help, do let me know.

One of the things I'm working on is regularly running acc tests for some providers. I can't tell from the Travis.yml, is libvirt running acc tests on every pr? Or just unit?

I don't know if there's any other shared resources we could use, but let me know if you think of anything.

**Comment by flavio** [comment]
The acceptance tests are run on each PR together with the unit tests. (See https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/.travis.yml#L28)

**Comment by dmacvicar** [comment]
BTW providers were already deleted from core, 
https://github.com/hashicorp/terraform/commit/1ab40eae3532d285ec94bfbf20a5d62ffc1f9d63

and there is a project here:
https://github.com/terraform-providers

I think we should try to move there.

**Comment by josephholsten** [comment]
@dmacvicar absolutely! Would someone like to open an issue in hashicorp/terraform for this? Hopefully, it'll just involve a code review pass and then be migrated.

**Comment by flavio** [comment]
These are the things I would like to see done before moving to https://github.com/terraform-providers:

  * Code cleanup:
     * Drop all the XML definitions by switching to the official `libvirt-go-xml` project. Tracked by issue https://github.com/dmacvicar/terraform-provider-libvirt/issues/143
     * Code refactoring of big functions, for example split the domain [resourceLibvirtDomainCreate function](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go#L172) into smaller parts.
  * Improve documentation: issue https://github.com/dmacvicar/terraform-provider-libvirt/issues/138
  * Identify a list of relevant open issues and close them (TBD)
  * Tag a release

I'll talk with the SUSE users of this provider that I know to identify the issues that have to be fixed before the move to the central repo. I'll also create a milestone on github to keep track of them.

**Comment by dmacvicar** [comment]
I don't think we are anywhere near being able to sustain ourselves inside the terraform repository, in terms of quality, number of contributors, etc.

**Comment by MalloZup** [comment]
i just close it because we have an implicit decision here.
I agre that we cannot live in terraform repo atm

thx all for your POV. ( in the future we can still reopen it if we have interest)

**Comment by MalloZup** [comment]
@josephholsten  thank you for bring this up :+1:

**Comment by ringods** [comment]
@MalloZup are you still working to get this provider moved to `terraform-providers`? The `terra-farm` organization is still welcoming you to join. 😉
