### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by andersla** [dmacvicar/terraform-provider-libvirt#138]
___
# Description of Issue/Question
It looks like a really interesting project and I would like to test it for my setup of a KVM machine. Is there some documentation about how to configure the provider?

**Comment by flavio** [comment]
What a nice coincidence, last night I figured out how to build nice docs like the one from the terraform official website. I plan to work on that during my spare time.

In the meantime you can find [docs](https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/docs/providers/libvirt) and [examples](https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples) inside of git.

**Comment by andersla** [comment]
I think it was because I missed the "r" subdirectory: https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/docs/providers/libvirt/r

**Comment by flavio** [comment]
I'm working on this topic by:
  * Changing the existing documentation to use the same style as upstream
  * Revamp the contents
  * Add more examples (I've already quite of them on my laptop, I just have to clean them up and add them).

**Comment by MalloZup** [comment]
@flavio  i think we are more or less good with this task now.

What could be left? Maybe we might close this card and split in more smaller cards

**Comment by MalloZup** [comment]
i'm just closing this because for the moment we achieved, feel free to reopen a new more specific task
