### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by andersla** [dmacvicar/terraform-provider-libvirt#139]
___
# Description of Issue/Question

OS: Ubuntu 16.04
go version go1.8.1 linux/amd64
glide version v0.12.3

I am trying to build on Ubuntu 16.04 but I have no experience in using go or glide. Simply issuing the command `go install` as stated in build instructions does not produce a binary:-)
This is the output:
```
go install
../../src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-getter/decompress_tbz2.go:4:2: cannot find package "archive/tar" in any of:
	/home/anders/work/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/vendor/archive/tar (vendor tree)
	/home/anders/work/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/archive/tar
	/home/anders/go/src/archive/tar (from $GOROOT)
	/home/anders/work/src/archive/tar (from $GOPATH)
../../src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/vendor/github.com/hashicorp/go-getter/decompress_zip.go:4:2: cannot find package "archive/zip" in any of:
	/home/anders/work/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/vendor/archive/zip (vendor tree)
	/home/anders/work/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/archive/zip
	/home/anders/go/src/archive/zip (from $GOROOT)
	/home/anders/work/src/archive/zip (from $GOPATH)
../../src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/vendor/github.com/go-ini/ini/parser.go:18:2: cannot find package "bufio" in any of:
	/home/anders/work/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/vendor/bufio (vendor tree)
	/home/anders/work/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/bufio
	/home/anders/go/src/bufio (from $GOROOT)
....
....
....
```

**Comment by MalloZup** [comment]
@andersla , you want to build from src or use the plugin?

 if you want to just use and install the terraform-libvirt, take
inspiration from this:

https://github.com/moio/sumaform#installation

**Comment by andersla** [comment]
I got it working - I just had to get into golang a little bit:

Here are some extended build instructions (Ubuntu 16.04):

- Install go (I preferred this instead of apt-package):  https://golang.org/doc/install
- Verify install: `go version`
- clone repo into  into:  `$GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt`
- Install non-go dependencies (pkg-config, libvirt-dev): `sudp apt-get install pkg-config libvirt-dev`
- `cd $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt`
- `go build` / `go install`

**Comment by momania** [comment]
I'm trying to build it on OS X (10.11.6), but get the following error running `go build` (go1.8.3 darwin/amd64):
```
./main.go:12: cannot use "github.com/dmacvicar/terraform-provider-libvirt/libvirt".Provider (type func() "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value
```

Any hint as to what might be wrong in my setup?

**Comment by monstermunchkin** [comment]
Closing this issue since it has been solved/answered.
