### ISSUE TITLE
Define multiple disks

### ISSUE THREAD

**Issue by johnavp1989** [dmacvicar/terraform-provider-libvirt#14]
Is this supported? I attempted this but it defines both disks as sda.

XML error: target 'sda' duplicated for disk sources

I'm trying to attach an Ubuntu cloud image and a config drive to a guest.

**Comment by johnavp1989** [comment]
The documentation suggests that multiple disks can be mounted:

> disk - (Optional) An array of one or more disks to attach to the domain. The disk object structure is documented below.

But looking at the code it seems that sda is hard-coded.

`func newDefDisk() defDisk {
	disk := defDisk{}
	disk.Type = "volume"
	disk.Device = "disk"
	disk.Format.Type = "qcow2"

	disk.Target.Dev = "sda"
	disk.Target.Bus = "virtio"

	return disk
}`

If I knew the first thing about go I would attempt to fix this myself but I can't make any sense of the code.

**Comment by johnavp1989** [comment]
I've made some progress on this in #15 but could use assistance.

**Comment by dmacvicar** [comment]
Thanks, looks definitely a bug. I will look into it.

**Comment by johnavp1989** [comment]
Thank you. I did my best to try to implement it myself but I don't know what I'm doing when it comes to go  :smile:

**Comment by dmacvicar** [comment]
Reproduced with a testcase

```console
=== RUN   TestAccLibvirtDomain_VolumeTwoDisks
--- FAIL: TestAccLibvirtDomain_VolumeTwoDisks (0.11s)
        testing.go:172: Step 0 error: Error applying: 1 error(s) occurred:

                * libvirt_domain.acceptance-test-domain: Error crearing libvirt domain: [Code-27] [Domain-20] XML error: target 'sda' duplicated for disk sources '<null>' and '<null>'
FAIL
exit status 1
FAIL    github.com/dmacvicar/terraform-provider-libvirt/libvirt 0.127s
```

**Comment by dmacvicar** [comment]
Give it a try now

**Comment by dmacvicar** [comment]
Thanks a lot for your patch, it was much easier to understand the problem thanks to it!. This time I am using a different solution as we need to generate disk names, not partition names and I prefer to setup the name outside of the disk definition structs.

**Comment by johnavp1989** [comment]
Works like a charm. Thanks!
