### ISSUE TITLE
pty serial console is needed for ubuntu cloud image to boot

### ISSUE THREAD

**Issue by andersla** [dmacvicar/terraform-provider-libvirt#141]
# Description of Issue/Question

If you are using an Ubuntu 16.04 or Ubuntu 17.04 cloud-image, a serial console is needed to be defined in your domain block for virtual machine to boot OK.

In the libvirt-domain resource, make sure you have a console block:

```
console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
}
```

My OpenSuse and CentOS cloud-image are booting ok without this console added.

**Comment by monstermunchkin** [comment]
IMHO this can be closed since it's neither an actual issue nor a question. Feel free to reopen if needed.

**Comment by paxsonsa** [comment]
Actually, this might be a good idea to toss into the examples This hung me up for a few days until I realized it.
