### ISSUE TITLE
Use libvirt-go-xml for marshalling/unmarshalling libvirt's XML

### ISSUE THREAD

**Issue by inercia** [dmacvicar/terraform-provider-libvirt#143]
We could use https://github.com/libvirt/libvirt-go-xml for doing all the marshalling/unmarshalling of _libvirt_'s XML.

**Comment by monstermunchkin** [comment]
I can have a look at that.

**Comment by flavio** [comment]
Sure, I started to look into that for fun. There are some things that are not exposed by the xml bindings, I fear because they are not really needed to create an object.

Spoiler alert: this is not going to be fun :)

**Comment by flavio** [comment]
Assigning to @monstermunchkin who is already working on that.

**Comment by flavio** [comment]
Ops, I spoke too early... @dmacvicar can you add @monstermunchkin as a contributor for this repository?
