### ISSUE TITLE
Using cloud-init resources breaks on subsequent apply runs

### ISSUE THREAD

**Issue by grahamhayes** [dmacvicar/terraform-provider-libvirt#145]
#  Version Reports:

### Distro  version of host:

``` openSUSE 42.2 ```

### Terraform Version Report
`Terraform v0.9.4`

### Libvirt version

```2.0.0```

### terraform-provider-libvirt plugin version (git-hash)

```
commit 612d0af3ec4bb23bdebdf878d7f8970517c755cc
Author: J. Eduardo <j.eduardo@gmail.com>
Date:   Fri Jun 30 23:56:46 2017 +0200

    Exported logic used to create a new backingStore representation onto a separated method.
```
___
# Description of Issue/Question

When rerunning `terraform apply` on a terraform stack that includes a `cloud-init` resource will cause the state to become corrupted.

### Setup
```
provider "libvirt" {
  uri = "qemu:///system"
}
resource "libvirt_volume" "node" {
  name           = "node.qcow2"
  pool           = "default"
  base_volume_id = "/var/lib/libvirt/images/opensuse-VAGRANTSLASH-openSUSE-42.1-x86_64_vagrant_box_image_1.0.0.img"
}

resource "libvirt_cloudinit" "node" {
  name      = "node_cloud_init.iso"
  pool      = "default"
  user_data = "${file("node.cfg")}"
}

resource "libvirt_domain" "node" {
  name      = "test_node"
  memory    = "2048"
  vcpu      = "2"
  cloudinit = "${libvirt_cloudinit.node.id}"

  disk {
    volume_id = "${libvirt_volume.node.id}"
  }

  network_interface {
    network_id     = "9d1891f1-b68d-4753-a7d2-395229ac5151"
    hostname       = "node"
    wait_for_lease = 1
  }

  graphics {
    type        = "vnc"
    listen_type = "address"
  }
}
```

### Steps to Reproduce Issue

1. Run `terraform apply` - it works.
  - https://gist.github.com/grahamhayes/02c6b5a80543de66fedfcd7993f3c056#file-tf-apply-1-log

2. Run `terraform apply` 
  - https://gist.github.com/grahamhayes/02c6b5a80543de66fedfcd7993f3c056#file-tf-apply-2-log
  - Trace Logs: https://gist.github.com/grahamhayes/02c6b5a80543de66fedfcd7993f3c056#file-tf-apply-2-trace-log

___
# Additional Infos:

Standard OpenSuse Leap install, all other resources work

**Comment by simonswine** [comment]
I am seeing exactly the same

* latest master of terraform-provider-libvirt
* Ubuntu 16.04
* Terraform v0.9.10

```
resource "libvirt_cloudinit" "master" {
  name = "${var.environment}-master-cloudinit-${count.index+1}.img"
  pool = "${var.storage_pool}"

  local_hostname     = "master-${count.index+1}"

  user_data = "${file("user-data.yaml")}"

  count = "${var.count_master}"
}

resource "libvirt_domain" "master" {
  name      = "${var.environment}-master-${count.index+1}"
  cloudinit = "${element(libvirt_cloudinit.master.*.id, count.index)}"

  disk {
    volume_id = "${element(libvirt_volume.master.*.id, count.index)}"
  }

  network_interface {
    network_id = "${libvirt_network.network.id}"

    hostname       = "master-${count.index+1}"
    wait_for_lease = 1
  }

  count = "${var.count_master}"
}
```

That's my error on the second apply: https://gist.github.com/simonswine/17273d199265cd4769e2baf59abb9621

Once I use an empty user_data the cloudinit resource isn't regenerated at the next apply:
```
  user_data = ""
```
