### ISSUE TITLE
storage pool bug encountered 

### ISSUE THREAD

**Issue by fisabelle** [dmacvicar/terraform-provider-libvirt#16]
I got this issue ( 1 time out of 3 maybe) when setting up 2 VMs
- libvirt_volume.centos7_vm_disk: Error refreshing pool for volume: [Code-1] [Domain-18] internal error: pool 'default' has asynchronous jobs running.

I wonder if you could make the provider a little more robust, with a few retries maybe, this is really a temporary failure I think and it seems related to an old libvirt bug.

**Comment by dmacvicar** [comment]
Did this one got fixed with https://github.com/dmacvicar/terraform-provider-libvirt/pull/17 ?

I am thinking about removing the refresh of the volume entirely. I added it to workaround a libvirt bug.

**Comment by johnavp1989** [comment]
This does not appear to have been fixed. I encounter this error more times than not when deploying 3 VM's in parallel. Re-running terraform apply almost always fixes it. On one occasion I've had to apply 3 times.

**Comment by dmacvicar** [comment]
Yes, this is because I added workaround code in one place but I do a pool refresh in two places.

I will fix it soon. I need to investigate a bit if there is something more elegant than blindly retry, like get the amount of jobs for the pool first.
