### ISSUE TITLE
libvirt_network, OVS support

### ISSUE THREAD

**Issue by jfgibbins** [dmacvicar/terraform-provider-libvirt#170]
Testing libvirt_network with the following: 
```
resource "libvirt_network" "pfSense" {
  name = "pfSense"
  mode = "bridge"
  bridge = "patch"
}
```
fails with the following message:
```
* libvirt_network.pfSense: Error defining libvirt network: virError(Code=1, Domain=19, Message='internal error: bridge name 'patch' already in use.') -   <network>
      <name>pfSense</name>
      <bridge name="patch" stp="on"></bridge>
      <domain></domain>
  </network>
```
No bridge named patch exists in libvirt, but is the name of the bridge on openvswitch.  If I change the name, I can get it to run, and virsh net-dumpxml pfSense provides following:
```
<network>
  <name>pfSense</name>
  <uuid>9b4db10a-dbbc-4232-91e0-d6198864b3a8</uuid>
  <bridge name='patch2' stp='on' delay='0'/>
  <mac address='52:54:00:82:a3:c7'/>
</network>
```

I'll assume that is what's expected, but not what is wanted.  What I need is to be able to create the following:
```
<network connections='1'>
  <name>pfSenseFW</name>
  <uuid>8cdc54fd-e760-4a1d-bf4a-c2d3d27c284b</uuid>
  <forward mode='bridge'/>
  <bridge name='patch'/>
  <virtualport type='openvswitch'/>
</network>
```
Thanks

**Comment by jfgibbins** [comment]
And someone please tell me how to get that stupid markdown to not screw up my plain text.

**Comment by flavio** [comment]
I fixed the formatting, it's a matter of using \`\`\` properly ;)

**Comment by hexfusion** [comment]
@jfgibbins I am going to take a crack at this one.

**Comment by jfgibbins** [comment]
@hexfusion  Very cool, let me know if you need any information.

**Comment by hexfusion** [comment]
@jfgibbins sorry for delay will get some cycles on this soon.

**Comment by jfgibbins** [comment]
no worries, I've been distracted by other projects for a while, doing some firewall evaluations as well as some IaC w/Terraform

**Comment by pananormalny** [comment]
Hi @jfgibbins , @hexfusion 

I've made some progress on this...

First of all virtualport support needs to be added to libvirt-go-xml (that's done) https://www.redhat.com/archives/libvir-list/2017-November/msg00561.html

I also modified a little bit terraform-provider-libvirt and have working terraform with OVS - for now it's just a prototype... I'm thinking if we would like to have something like this:

```
resource "libvirt_network" "ovs" {
   name = "ovs"
   mode = "bridge" // mode can be bridge but then i would add new value with type: ovs? 
   bridge = "vm0"
}```

or `mode: ovs` would be better? what do you think? bridge variable will stay cause it's still needed.

**Comment by himani93** [comment]
Hi, I would like to work on this issue.

Thanks

**Comment by MalloZup** [comment]
hi @himani93 sure feel free to take it ! thx and feel free to ask if you have any question

**Comment by zeenix** [comment]
@himani93 So did you make any progress? While OVS would be great to have, I don't think this issue is that big a deal when/if it happens. You'd have a similar issue if you don't give unique names to your other resources. So unless someone is working on this, I'd suggest we close this.

**Comment by zeenix** [comment]
> First of all virtualport support needs to be added to libvirt-go-xml (that's done) https://www.redhat.com/archives/libvir-list/2017-November/msg00561.html

Oh and just FYI, this has landed a while ago and vendored by us already.

**Comment by MalloZup** [comment]
In theory with `xslt` we can support any feature already. Closing

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown#altering-libvirts-generated-domain-xml-definition
