### ISSUE TITLE
Video option

### ISSUE THREAD

**Issue by jfgibbins** [dmacvicar/terraform-provider-libvirt#171]
```hcl
# Configure the Libvirt provider
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_domain" "pfSense" {
  name = "pfSense"
  vcpu = 4
  memory = 4096
  running = true
  autostart = true
  disk {
    volume_id = "${libvirt_volume.pfSense.id}"
  }
  network_interface {
    network_name = "pfSense"
    hostname = "pfSense"
  }
}

resource "libvirt_volume" "pfSense" {
  name = "pfSense"
  source = "/var/lib/libvirt/images/pfSense.qcow2"
}
```

Generates error and will not start, but going into virt-manager, changing video from Cirrus to QXL and container boots successfully.  There was also a device called qemu-ga, but no idea what that even is, deleted as well from config.

**Comment by hexfusion** [comment]
Try defining graphics few options that have worked for me.
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown#graphics-devices
```
  graphics {
    type = "vnc"
    listen_type = "address"
  }
```

```
  graphics {
    type = "spice"
    listen_type = "address"
    autoport = true
  }
```
-HTH

**Comment by jfgibbins** [comment]
the options you listed are for VNS vs.SPICE, but not the actual graphics hardware for the guest, but thanks

**Comment by monstermunchkin** [comment]
Feel free to send a pull request adding the video option.

**Comment by jfgibbins** [comment]
I would, but I'm not a programmer.  Do not pass go, and do not collect $200.

**Comment by deasmi** [comment]
I am working on some vnc additions so I'll see if I can include this. No promises however.

**Comment by jfgibbins** [comment]
@deasmi Always appreciated.  It's on my list to start learning go, but currently working on a lot of "infrastructure as code".  Once I get that done, I might have a few working brain cells left to start learning something new.

**Comment by deasmi** [comment]
Can we add this to 0.1 ?

**Comment by deasmi** [comment]
@jfgibbins Can you test if my patch fixes your issue please.

Branch graphicsandvnc on https://github.com/deasmi/terraform-provider-libvirt.git

Pull request #198

**Comment by MalloZup** [comment]
We use now xslt for allowing custom parameters to domain network etc. Look at the doc or examples. Tia
