### ISSUE TITLE
./main.go:12: cannot use "github.com/dmacvicar/terraform-provider-libvirt/libvirt"

### ISSUE THREAD

**Issue by rj-reilly** [dmacvicar/terraform-provider-libvirt#172]
#  Version Reports:

### Distro  version of host:

```ubuntu 17.04 ```

### Terraform Version Report
Terraform v0.10.2

### Libvirt version

2.5.0

### terraform-provider-libvirt plugin version (git-hash)

8d2b4a3f51b20837238386785431eff3129bd716
___
# Description of Issue/Question

fails to build on ubuntu 17.04, I installed libvirt and it's libs
```# _/home/rreilly/terraform-provider-libvirt
./main.go:12: cannot use
 "github.com/dmacvicar/terraform-provider-libvirt/libvirt".Provider (type func() "github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider)
 as type "github.com/hashicorp/terraform/plugin".ProviderFunc in field value```

**Comment by hexfusion** [comment]
@rj-reilly this is how I build it
```
go get github.com/dmacvicar/terraform-provider-libvirt
```
which should put your binary here.
```
$GOPATH/bin/terraform-provider-libvirt
```
I can replicate that error if I issue `go build` in the package.

-HTH

**Comment by monstermunchkin** [comment]
I cannot reproduce this issue on Ubuntu 17.04 with Terraform 0.10.2, go 1.8, and libvirt 2.5.0. Also, `go build` works fine for me.

Were you able to figure this out or is it still an issue?

**Comment by hexfusion** [comment]
FWIW @monstermunchkin I can confirm that this works fine for me now as well.  The error I made in replicating the issue was not issuing building within $GOPATH which is required for Glide to work properly. @rj-reilly ?

**Comment by rj-reilly** [comment]
that worked, I am new to GO so i appreciate the help !

**Comment by hexfusion** [comment]
Glad it works.
