### ISSUE TITLE
output ip address for interfaces (as output variables)

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#18]
When a VM is started, an output variable with every interface ip addresses should be set.

Requires some work in libvirt-go, being done here: https://github.com/dmacvicar/libvirt-go/tree/domain_iface_addr in order to add `virDomainInterfaceAddresses`.

The current idea is to set an option per network interface that allows to wait until that interface gets an ip address. Something like:

```hcl
resource "libvirt_domain" "domain1" {
  name = "domain1"
  disk {
    volume_id = "${libvirt_volume.myvol.id}"
  }
  network_interface {
    network = "default"
    wait_for_address = true
  }
```

If `wait_for_address` is `true` then `terraform apply` would wait until that interface gets an address and then set a variable `network_interface.0.ip_v4.0` to `x.x.x.x`.

@fisabelle @johnavp1989 input appreciated.

**Comment by dmacvicar** [comment]
Learned about `SetConnInfo`, I think this is the magic sauce.

https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance.go#L719

**Comment by johnavp1989** [comment]
This would be a nice feature. I'm currently assigning static IP's via cloud-init but this would potentially make DHCP a much better option. No need to assign a specific MAC for DHCP reservation when the IP is available as a variable.

**Comment by dmacvicar** [comment]
I have it already implemented and working in this branch https://github.com/dmacvicar/terraform-provider-libvirt/tree/connect_ip_address :

![screenshot from 2016-05-17 00-25-45](https://cloud.githubusercontent.com/assets/15332/15401180/aa058d38-1dee-11e6-87f6-2eac93f126d9.png)

But I can't merge it into master yet. It lacks:

* Documentation
* To figure out how to test it
* Upstreaming a patch to libvirt-go

And the feature automatically sets the connection info on the resource so that the provisioners like `file` using `ssh` work out of the box:

![screenshot from 2016-05-17 00-34-13](https://cloud.githubusercontent.com/assets/15332/15401193/b7a363ca-1dee-11e6-9795-b66fb58f07a8.png)

**Comment by dmacvicar** [comment]
The current implementation waits for addresses (from the libvirt lease) on all defined interfaces. This allow the provider to set the ip information when applying the plan, otherwise applying the plan may end before the network interface gets an ip address.

You say until now you were using another method (cloud-init) to assign an address. I think it makes then sense to not wait for libvirt leases by default but make it a option per interface. Something like:

```hcl
resource "libvirt_domain" "domain1" {
  name = "domain1"

  network_interface {
    network = "default"
    wait_for_lease = true
  }

  network_interface {
    network = "mystaticnet"
  }
}
```

What do you think?

**Comment by johnavp1989** [comment]
Agreed. I wouldn't want this to be a default behavior. In my use case it would only add unnecessary delay.
