### ISSUE TITLE
question: Release tasks?

### ISSUE THREAD

**Issue by hexfusion** [dmacvicar/terraform-provider-libvirt#189]
I know this has been asked before but I feel the milestones are not reflecting what needs to be done for a release. I would like to help what is required for a proper release?

https://github.com/dmacvicar/terraform-provider-libvirt/milestones

**Comment by flavio** [comment]
Sure, feel free to propose your ideas here.

**Comment by hexfusion** [comment]
since we have made a release going to close this.
