### ISSUE TITLE
provider.libvirt: virError(Code=1, Domain=25, Message='internal error: IVirtualBox object is null')

### ISSUE THREAD

**Issue by rj-reilly** [dmacvicar/terraform-provider-libvirt#195]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 17.04 ```

### Terraform Version Report
Terraform v0.10.2

### Libvirt version
2.5.0

### terraform-provider-libvirt plugin version (git-hash)
8d2b4a3f51b20837238386785431eff3129bd716
___
# Description of Issue/Question

```
Error running plan: 1 error(s) occurred:

* provider.libvirt: virError(Code=1, Domain=25, Message='internal error: IVirtualBox object is null')
```

### Setup
(Please provide the full **main.tf** file for reproducing the issue (Be sure to remove sensitive info)
```
variable "ip" {}

provider "libvirt" {
    uri = "vbox:///system"
}

resource "libvirt_network" "test" {
   name = "test"
   mode = "bridged"
   addresses = ["192.168.1.$${ip}/24"]
}

# qcow2 image from file
resource "libvirt_volume" "test" {
  name = "test"
  source = "http://192.168.1.6:8000/centos7-base-0.1.0-disk001.qcow"
}

# domain using qcow2-backed volume
resource "libvirt_domain" "test" {
  name = "test.qcow2"
  memory = "2048"
  vcpu = 2
  network_interface {
    network_name = "tf"
  }
  disk {
    volume_id = "${libvirt_volume.test.id}"
  }
  graphics {
    type = "spice"
    listen_type = "address"
    autoport = "yes"
  }
}
```

**Comment by flavio** [comment]
It looks like you are using the wrong connection url. According to the [official documentation](https://libvirt.org/drvvbox.html) you should be using ‘vbox:///session‘

**Comment by rj-reilly** [comment]
I will give that a try thanks !
