### ISSUE TITLE
genisoimage is not available on all platforms/distros

### ISSUE THREAD

**Issue by deasmi** [dmacvicar/terraform-provider-libvirt#199]
genisoimage seems totally unavailable for macOS and doesn't appear to be very common across linux distros

This makes cloudinit isos OS dependent on the client.

I'm going to look for a more common cross platform/distro alternative as this is the only thing that prevents this running anywhere

**Comment by deasmi** [comment]
Whatever tools are used suspect build constraints the best way to implement rather than runtime detection.

https://golang.org/pkg/go/build/#hdr-Build_Constraints

**Comment by deasmi** [comment]
hdiutil makehybrid -iso -joliet -o image.iso /path/to/source can use used on macOS

**Comment by simonswine** [comment]
This might also work, never tried it though: https://github.com/johto/iso9660wrap

**Comment by MalloZup** [comment]
@deasmi  is ```hdiutil``` a std pkg on darwin?

**Comment by deasmi** [comment]
@MalloZup MacOS definitely out the box, I don't have a pure darwin host to check, but the diskimages framework isn't open source, so quite possibly not.
http://www.openradar.me/31813634

**Comment by MalloZup** [comment]
@deasmi ok thx for info :boat:

**Comment by inercia** [comment]
I think it was fixed in #269. Closing.
