### ISSUE TITLE
Easy-fix: Coveralls code coverage algorithm is wrong( decrease when adding documentation)

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#210]
I just noticed that the goveralls decrease for adding documentation or other files.

This cannot be the real coverage target. We need to adapt the filters :sunflower:

**Comment by MalloZup** [comment]
i will try to fix  it

**Comment by flavio** [comment]
Ouch, this is really bad :/

**Comment by MalloZup** [comment]
@flavio  yop,  to me seems that adding a ruby and dir decrease. i will have try to look at it more in deep once i have some free time in life :sunflower:
