### ISSUE TITLE
Device Name for each disk when multiple disks?

### ISSUE THREAD

**Issue by pfremm** [dmacvicar/terraform-provider-libvirt#219]
# Description of Issue/Question
Is it possible to specify the device name such as /dev/vdb when attaching multiple disks?  I'm not seeing an option in the documentation.

**Comment by dmacvicar** [comment]
AFAIK we don't set the 'dev' parameter of 'target' in libvirt.

What would be the usecase?

**Comment by pfremm** [comment]
For coreos it would ensure i know the dev device for the ignition config as systemd is used to mount the addition device.

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/issues/418
