### ISSUE TITLE
Can't compile from latest master branch

### ISSUE THREAD

**Issue by johnavp1989** [dmacvicar/terraform-provider-libvirt#22]
Attempted to recompile against the latest master and got the following errors:

> \# github.com/dmacvicar/terraform-provider-libvirt/libvirt
libvirt/resource_libvirt_domain.go:212: domain.ListAllInterfaceAddresses undefined (type libvirt.VirDomain has no field or method ListAllInterfaceAddresses)
libvirt/resource_libvirt_domain.go:212: undefined: libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE
libvirt/resource_libvirt_domain.go:239: undefined: libvirt.VIR_IP_ADDR_TYPE_IPV4
libvirt/resource_libvirt_domain.go:241: undefined: libvirt.VIR_IP_ADDR_TYPE_IPV6
libvirt/resource_libvirt_domain.go:359: domain.ListAllInterfaceAddresses undefined (type libvirt.VirDomain has no field or method ListAllInterfaceAddresses)
libvirt/resource_libvirt_domain.go:359: undefined: libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE

**Comment by fisabelle** [comment]
You need the updates libvirt-go

**Comment by dmacvicar** [comment]
Yes, I keep my fork of libvirt-go in sync with this project.

**Comment by johnavp1989** [comment]
Durp... got it. Thank you.
