### ISSUE TITLE
Disable coverall?

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#220]
All the PR polluted with its comments is lot of noise and the information is not very useful.

**Comment by MalloZup** [comment]
i vote for +1

**Comment by flavio** [comment]
On the other side I find useful to see how the code coverage would change as a reaction to the PR. I don't like to get emails from him though :)

**Comment by dmacvicar** [comment]
I can't read PRs anymore, it is a mess. I disabled it, kept the status API (summary) and the README.
