### ISSUE TITLE
(Discussion) Create subpackages for the provider

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#225]
@dmacvicar   @flavio  @monstermunchkin @inercia  is the terraform plugin design somehow preventing us to create golang subpackages? 
What do you think about. I think this could help us to refactoring and organize code.

Maybe we if we agree, we should just focus on how and which packages we can create. :anchor:

**Comment by monstermunchkin** [comment]
I don't think anyone/anything can prevent you from creating golang subpackages. However, I had a look at some of the bigger providers in [this project](https://github.com/terraform-providers), and all of them are structured the same way without using subpackages.

We don't have that many files, so refactoring the code should be just fine. I don't believe that subpackages are a good solution here.

**Comment by MalloZup** [comment]
ok thx, closing
