### ISSUE TITLE
false positive in network_interface change detection forcing rebuild of domain

### ISSUE THREAD

**Issue by fisabelle** [dmacvicar/terraform-provider-libvirt#23]
Hi.

Since I pulled that latest master this morning, I no longer see storage pool issues.

However, even if I don't make any change to the network_interface data., the provider always sees:

    network_interface.#:                "0" => "1" (forces new resource)
    network_interface.0.address.#:      "" => "<computed>"
    network_interface.0.mac:            "" => "52:54:00:A1:A3:61" (forces new resource)
    network_interface.0.network:        "" => "host-bridge2" (forces new resource)
    network_interface.0.wait_for_lease: "" => "0" (forces new resource)

As a result, my VM are being refreshed or completely rebuilt, this is not convenient.
I wonder if this is expected.
Thank you.

**Comment by dmacvicar** [comment]
Can you share your `.tf` file?

**Comment by fisabelle** [comment]
The only thing I describe in the network interface is the network and the mac

  network_interface {
    network = "host-bridge2"
    mac= "52:54:00:A1:A3:${var.vnfc1_mac}"
  }
==

here is a sample:

resource "libvirt_domain" "centos7_vm1_domain" {
  name = "centos7_vm_domain_${var.vnfc1_mac}"
  vcpu = 2
  memory = 2048

  disk {
     volume_id = "${libvirt_volume.centos7_vm1_disk.id}"
  }


  network_interface {
    network = "host-bridge2"
    mac= "52:54:00:A1:A3:${var.vnfc1_mac}"
  }

  connection {
   host = "${var.vnfc1_ip}"
   user = "root"
  }



}

**Comment by fisabelle** [comment]
I see the terraform.tfstate does no include the resources previously defined:



 "resources": {
                "libvirt_domain.centos7_vm1_domain": {
                    "type": "libvirt_domain",
                    "depends_on": [
                        "libvirt_volume.centos7_vm1_disk"
                    ],
                    "primary": {
                        "id": "4007b631-5ba3-4b41-aead-58f569fa0115",
                        "attributes": {
                            "disk.#": "1",
                            "disk.0.volume_id": "/home/vmstore/ramdisk/centos7_vm_disk_57",
                            "id": "4007b631-5ba3-4b41-aead-58f569fa0115",
                            "memory": "2048",
                            "name": "centos7_vm_domain_57",
                            **"network_interface.#": "0",**
                            "vcpu": "2"
                        }
                    }
                },

**Comment by dmacvicar** [comment]
Ok, should be fixed now. The way terraform handles values that are not part of the living infrastructure is still a bit blur to me. I now set `mac` as computed + optional and `wait_for_lease` is passed *as is* on domain `read`.

**Comment by fisabelle** [comment]
It's a blur to me too, but I'm not sure it's working yet.

When I run the initial apply I get:
module.vm_xsa_single.libvirt_volume.centos7_vm_disk: Creating...
  name:   "" => "centos7_vm_disk_76"
  pool:   "" => "ram"
  size:   "" => "<computed>"
  source: "" => "http://localhost:80/images/centos7.base"
module.vm_xsa_single.libvirt_volume.centos7_vm_disk: Creation complete
module.vm_xsa_single.libvirt_domain.centos7_vm_domain: Creating...
  disk.#:                        "" => "1"
  disk.0.volume_id:              "" => "/home/vmstore/ramdisk/centos7_vm_disk_76"
  memory:                        "" => "2048"
  name:                          "" => "centos7_vm_domain_76"
  network_interface.#:           "" => "1"
  network_interface.0.address.#: "" => "<computed>"
  network_interface.0.mac:       "" => "52:54:00:A1:A3:76"
  network_interface.0.network:   "" => "host-bridge2"
  vcpu:                          "" => "2"

It applies successfully. 

Than I re-apply it, assuming nothing will change, but it reapplies the whole thing.

module.vm_xsa_single.libvirt_volume.centos7_vm_disk: Refreshing state... (ID: /home/vmstore/ramdisk/centos7_vm_disk_76)
module.vm_xsa_single.libvirt_domain.centos7_vm_domain: Refreshing state... (ID: 2a512446-fb4c-4379-920e-8308af8c5ab0)
libvirt_domain.centos7_vm_domain: Destroying...
libvirt_domain.centos7_vm_domain: Destruction complete
module.vm_xsa_single.libvirt_domain.centos7_vm_domain: Creating...
  disk.#:                        "" => "1"
  disk.0.volume_id:              "" => "/home/vmstore/ramdisk/centos7_vm_disk_76"
  memory:                        "" => "2048"
  name:                          "" => "centos7_vm_domain_76"
  network_interface.#:           "" => "1"
  network_interface.0.address.#: "" => "<computed>"
  network_interface.0.mac:       "" => "52:54:00:A1:A3:76"
  network_interface.0.network:   "" => "host-bridge2"
  vcpu:                          "" => "2"
module.vm_xsa_single.libvirt_domain.centos7_vm_domain: Provisioning with 'file'...
module.vm_xsa_single.libvirt_domain.centos7_vm_domain: Provisioning with 'remote-exec'...

For  some reason, the disk is not being recreated, but the VM is rebooted which is not desirable

**Comment by dmacvicar** [comment]
Did you start everything from scratch? eg. without the `.tfstate` files after recompiling/reinstalling the provider?

**Comment by fisabelle** [comment]
Yes. But I will give it another try.
Le 27 mai 2016 18:50, "Duncan Mac-Vicar P." <notifications@github.com> a
écrit :

**Comment by dmacvicar** [comment]
The bug (well, one of them) was that after creating the resources from the `.tf` file, we usually read all back from libvirt. I did not store `wait_for_lease` in the state file so that is why it may not work with a previous state.
