### ISSUE TITLE
question NIC model and PCI address options?

### ISSUE THREAD

**Issue by michtam** [dmacvicar/terraform-provider-libvirt#247]
# Description of Issue/Question

I have two question about provider:
- It is possible to set pci bus address of device?
- Can I set model of network interface? Default is virtio - I would like to set e1000.

**Comment by MalloZup** [comment]
ciao @michtam  you can have a look here : https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/website/docs/r, in this pages. if it not present, then we hadn't implemented it, afaik.  (speaking from my pov, i am not 100% sure.)

**Comment by MalloZup** [comment]
@michtam i will close this issue since we improved the documentation here

https://github.com/dmacvicar/terraform-provider-libvirt#website-docs

Thank you for your issue, feel free to ask if you have any further questions! :white_flower:
