### ISSUE TITLE
Option to make libvirt_network autostart after reboot

### ISSUE THREAD

**Issue by mludy** [dmacvicar/terraform-provider-libvirt#248]
Is it possible to add option silimar to libvirt_domain autostart  on libvirt_network level ? 
In our use case its mandatory for libvirt domain to survive machine restart and because there is no possibility to set network autostart option domain is not able to recover.

**Comment by MalloZup** [comment]
ciao @mludy , afaik we can implement this, since in libvirt is possible. I can have a look when i have some time.

**Comment by MalloZup** [comment]
@mludy  once the Pr is merged (here referenced), you can use the autostart option like with

* `autostart` - (Optional) Set to `true` to start the network on host boot up.
 If not specified `false` is assumed.

**Comment by mludy** [comment]
Great. Thanks for really fast action !

**Comment by MalloZup** [comment]
@mludy thank you :smile: feel free to use it now
