### ISSUE TITLE
Cannot import resources

### ISSUE THREAD

**Issue by Pwpon500** [dmacvicar/terraform-provider-libvirt#254]
#  Version Reports:

### Distro  version of host:

```  Debian 9 ```

### Terraform Version Report
``` Terraform v0.11.0 ```

### Libvirt version

``` 3.0.0 ```

### terraform-provider-libvirt plugin version (git-hash)
Most recent commit:
```
commit a6f137024b0e61e2d6c67c7cb0195493a38d3815
Author: MalloZup <dmaiocchi@suse.com>
Date:   Sun Nov 5 13:20:53 2017 +0100

    Add note about latest golang version required
```

# Description of Issue/Question

### Setup
main.tf:
```
provider "libvirt" {
    uri = "qemu:///system"
}

resource "libvirt_volume" "debian9-qcow2" {
    name = "debian9-qcow2"
    source = "(source file here)"
}

resource "libvirt_volume" "vol-debian9-qcow2" {
    name = "vol-debian9-qcow2"
    base_volume_id = "${libvirt_volume.debian9-qcow2.id}"
    pool = "drive1"
}

resource "libvirt_domain" "domjudge" {
    name = "domjudge"
    memory = 1024
    vcpu = 1

    network_interface {
        bridge = "vmbr100"
    }

    disk {
        volume_id = "${libvirt_volume.vol-debian9-qcow2.id}"
    }

    console {
        type = "pty"
        target_port = "0"
        target_type = "serial"
    }
}
```
When trying to import the domain or volume resource into my terraform state, terraform says that the resource doesn't support import. Is this correct? In #82, the `terraform import` command is mentioned as if it works with the libvirt provider.
```
 /o/terraform > terraform import libvirt_domain.domjudge 22
libvirt_domain.domjudge: Importing from ID "22"...
Error importing: 1 error(s) occurred:

* libvirt_domain.domjudge (import id: 22): import libvirt_domain.domjudge (id: 22): resource libvirt_domain doesn't support import
```

**Comment by MalloZup** [comment]
ciao @Pwpon500 , we don't have implemented the ```importer``` functionality in the plugin, so it is normal that you get the message.

**Comment by Pwpon500** [comment]
Ah OK, that makes sense. I didn't want to make a feature request because I wasn't sure if I was just doing something wrong or if the importer functionality wasn't in the plugin yet. Thanks for the help!
