### ISSUE TITLE
Support network_interfaces for meta-data in cloud-init

### ISSUE THREAD

**Issue by solidnerd** [dmacvicar/terraform-provider-libvirt#265]
Hey,
I think this a good feature if you can't rely on DHCP in some environments. I would like to introduce a new key that helps to set `network-interfaces` key in meta-data. An example with network-interfaces key looks like this:

```yml
instance-id: iid-abcdefg
network-interfaces: |
  iface eth0 inet static
  address 192.168.1.10
  network 192.168.1.0
  netmask 255.255.255.0
  broadcast 192.168.1.255
  gateway 192.168.1.254
hostname: myhost
```
The content of `network-interfaces` is the normal content of `/etc/network/interfaces` . So you can configure everything you want. 

Example in a cloud-init ressource.

```hcl
resource "libvirt_cloudinit" "template_cloud_init" {
  name = "test_cloud_init.iso"
  local_hostname ="myhost"
  user_data = "${file("user-data.yaml")}"
  meta_data_network_interfaces = "${file("network-interface")}"
}
```
```bash
# file: network-interface
# The loopback network interface
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
  address 192.168.1.10
  network 192.168.1.0
  netmask 255.255.255.0
  broadcast 192.168.1.255
  gateway 192.168.1.254
```

An alternative way would to provided a yaml formatted file that is called `network-config` next to `meta-data` and `user-data` on iso. This file need be formatted als cloud-init [Networking Config Version 1 ](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#network-config-v1) or [Networking Config Version 2](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#network-config-v2) . 

I tested the alternative and this didn't work for me but I think it cloud coming from my cloud-init default configuration on the vms.

For more information have a look at https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html .

**Comment by solidnerd** [comment]
I could give you the PR for that if you want.

**Comment by night199uk** [comment]
+1

**Comment by night199uk** [comment]
Check:
https://github.com/dmacvicar/terraform-provider-libvirt/pull/267
Which should allow you to specify arbitrary metadata to support your first example (I needed the same).

**Comment by inercia** [comment]
I think this could be achieved with #270 .
