### ISSUE TITLE
localOnly domain attribute

### ISSUE THREAD

**Issue by lis0r** [dmacvicar/terraform-provider-libvirt#276]
Hi,

It would be nice to have some means of enabling the localOnly attribute for libvirt_network <domain> definitions.

Thanks!

Lisa

**Comment by cbaines** [comment]
I've just noticed that this branch seems to include support https://github.com/dmacvicar/terraform-provider-libvirt/tree/network_improvs

**Comment by MalloZup** [comment]
we will merge this on https://github.com/dmacvicar/terraform-provider-libvirt/pull/376
