### ISSUE TITLE
Build with go install fails

### ISSUE THREAD

**Issue by andersla** [dmacvicar/terraform-provider-libvirt#277]
Building from source with `go install` fails:
trying to followi instructions from: https://github.com/dmacvicar/terraform-provider-libvirt#building-from-source

```
$ git clone https://github.com/dmacvicar/terraform-provider-libvirt.git
$ cd terraform-provider-libvirt
$ go install
main.go:5:2: cannot find package "github.com/hashicorp/terraform/plugin" in any of:
	/usr/local/go/src/github.com/hashicorp/terraform/plugin (from $GOROOT)
	/home/anders/go/src/github.com/hashicorp/terraform/plugin (from $GOPATH)
```
go version: go1.9.1 linux/amd64
os: Ubuntu 16.04

I also tried to build version v0.2, same error
```
$ git checkout v0.2
$ go install
main.go:5:2: cannot find package "github.com/hashicorp/terraform/plugin" in any of:
	/usr/local/go/src/github.com/hashicorp/terraform/plugin (from $GOROOT)
	/home/anders/go/src/github.com/hashicorp/terraform/plugin (from $GOPATH)
```

**Comment by inercia** [comment]
I think your complier is not finding the vendored dependencies for some reason. For example, `github.com/hashicorp/terraform/plugin` is not found while it is included in [terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin](https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/vendor/github.com/hashicorp/terraform/plugin).

Could you describe your environment? The Go compiler version, and maybe the output of `go env`...

**Comment by MalloZup** [comment]
i think this @andersla @inercia https://github.com/dmacvicar/terraform-provider-libvirt/issues/139
we could close this issue as duplicata of the issue above, since it is the same issue

**Comment by MalloZup** [comment]
i close because of this #139 which is same issue
```
go get github.com/dmacvicar/terraform-provider-libvirt
cd $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt
make build or go build
make install 
```
this is normal workflow for using golang projects.
Thx for issue, feel free to ask here if it doesn't solve
