### ISSUE TITLE
provider.libvirt: Unrecognized remote plugin message

### ISSUE THREAD

**Issue by sivarammedapati** [dmacvicar/terraform-provider-libvirt#278]
Distro version of host:
CentOS Linux release 7.4.1708

Terraform Version Report
Terraform v0.11.3

Libvirt version
3.2.0

[root@localhost ~]# cat libvirt.tf
provider "libvirt" {
    uri = "qemu+ssh://root@172.16.12.54/system"
}
resource "libvirt_volume" "mydisk" {
  name             = "terraform-test1.img"
  pool             = "default"
  base_volume_name = "CentOS-7-x86_64-GenericCloud-1707.qcow2"
}
[root@localhost ~]# terraform plan

Error: Error asking for user input: 1 error(s) occurred:

* provider.libvirt: Unrecognized remote plugin message: Usage: terraform [--version] [--help] <command> [args]

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

**Comment by inercia** [comment]
Did you install the plugin from a `rpm`/`deb` or complie it from the source code?

**Comment by MalloZup** [comment]
closing, i think is invalid since we have centos7 user already feel free to reopen and ask question here if you need help thank you!
