### ISSUE TITLE
README file installation instructions update 

### ISSUE THREAD

**Issue by markostanojlovic** [dmacvicar/terraform-provider-libvirt#284]
#  Version Reports:
Terraform v0.11.3
terraform-provider-libvirt-0.0.0+git20180220.f2cef405-1.1.x86_64 
libvirt-3.3.0-4.28.x86_64

Now, according to the terraform documentation, this is the procedure to install : 
https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

On all other systems, in the sub-path **.terraform.d/plugins** in your user's home directory.

terraform init will search this directory for additional plugins during plugin initialization.

The naming scheme for provider plugins is terraform-provider-NAME_vX.Y.Z, and Terraform uses the name to understand the name and version of a particular provider binary.

**Comment by inercia** [comment]
I think the old system still works (doing a `go install` as described in our [installation instructions](https://github.com/dmacvicar/terraform-provider-libvirt#building-from-source)), but I agree it would be a good idea to update the README and explain how to install it using this new mechanism...

**Comment by MalloZup** [comment]
@markostanojlovic  feel free to spend a PR for this :+1:
