### ISSUE TITLE
Support multiple Provider instances with different URIs

### ISSUE THREAD

**Issue by kawaja** [dmacvicar/terraform-provider-libvirt#290]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 16.04.4 LTS ``` (xenial)

### Terraform Version Report

Terraform v0.11.6-dev (725281f4aa8c166d5d8bd003c2d8f8f4b4bcbc46+CHANGES)

### Libvirt version

On Terraform host:
```# virsh --version
1.3.1
```

On Libvirt host(s):
```# virsh --version
3.2.0
```

### terraform-provider-libvirt plugin version (git-hash)

```# git log
d37e941778af77694f63306d4cae3250885abd87
```
___
# Description of Issue/Question

I want to be able to use a single terraform config to address multiple libvirt hosts, in order to build a cluster of VMs deployed on these different hosts.

### Setup

After reading through the Terraform documentation, I wrote something like this. In `cluster.tf`:

```
provider "libvirt" {
  alias = "host00"
  uri = "qemu+ssh://root@192.168.100.1/system"
}

provider "libvirt" {
  alias = "host01"
  uri = "qemu+ssh://root@192.168.100.2/system"
}

...

module km1 {
  source "./domain"
  host "km1"
  ram "2048"
  providers {
    libvirt = "libvirt.host00"
  }
}

module k01 {
  source "./domain"
  host "k01"
  ram "4096"
  providers {
    libvirt = "libvirt.host01"
  }
}

module k02 {
  source "./domain"
  host "k02"
  ram "4096"
  providers {
    libvirt = "libvirt.host00"
  }
}
```

and then in `domain/main.tf`:

```
variable "host" {
  type = "string"
}

variable "ram" {
  type = "string"
}

...

# this is a temporary workaround required in the current version of terraform
# and should be removed in the future (see https://www.terraform.io/docs/modules/usage.html)
provider "libvirt" {
}

...

resource "libvirt_domain" "host" {
  depends_on = ["null_resource.fix-qcow2-image"]
  name = "${var.host}"
  memory = "${var.ram}"
  vcpu = 1

...
}
```

When I `apply` this, however, it starts all domains on one libvirt host, rather than spreading them across both hosts. In looking at the `terraform-provider-libvirt` code, this is because the first connection is cached in a global variable when the first Provider instance is created and the subsequent Provider instance uses this cached value rather than creating the second connection.

https://github.com/dmacvicar/terraform-provider-libvirt/blob/d37e941778af77694f63306d4cae3250885abd87/libvirt/provider.go#L15

It looks like this may have worked in the past, but commit https://github.com/dmacvicar/terraform-provider-libvirt/commit/2578a7087aec5a5be20e102ba5d9b0963b55bf78 / https://github.com/dmacvicar/terraform-provider-libvirt/commit/0c5cd9c0460accc52e7bdca625d455741f1f6b3a appears to have had the side-effect of removing the ability to use multiple Provider instances with different URIs.

I've locally patched (see https://github.com/kawaja/terraform-provider-libvirt/commit/e9d62e3f9646c533d9fc77e5171529b65b1d6354) to keep separate instances of the `libvirt.Connect` object and multiple Provider instances is working for me now. I assume though that closing the `libvirt.Connect` object is important in the resolution of #266 (any comment @flavio?). So I looked for some way of closing these objects that didn't depend on having a single global variable to hold the object.

I searched through the terraform issues and found one which looks like it's exactly what's needed (https://github.com/hashicorp/terraform/issues/6258), but that was never implemented. So the only way I can think of to close these objects is to keep a list of them in the global context. In C, I would build a linked list and use a global head variable. However, since this is the first go program I've tried to modify, I don't trust myself to build and test this properly.

That's as far as I've got for now.

**Comment by kskewes** [comment]
@dmacvicar do you have any thoughts on how we might achieve this one?

**Comment by dmacvicar** [comment]
Terraform allows to instantiate providers multiple times:

https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances

So you can instantiate the provider twice, the 2nd time with an alias, and then link resources to one of the provider instances. Right now this is not working. I suspect the culprit is some global key-based Mutex that someone introduced without thinking about this. I suspect the mutex is locking the storage pool "default" without distinguishing provider instances.

I will give it a second look. I see why it should not work after we fix that.
