### ISSUE TITLE
Can not connect to existing bridge

### ISSUE THREAD

**Issue by samlabs821** [dmacvicar/terraform-provider-libvirt#293]
#  Version Reports:

### Distro  version of host:
Centos7

### Terraform Version Report
Terraform v0.11.7

### Libvirt version
3.2.0

### terraform-provider-libvirt plugin version (git-hash)commit 5d724d3f761c2b5af7a652fdfd38a853548dc474
___
# Description of Issue/Question

### Setup

provider "libvirt" {
    uri = "qemu+ssh://terra@10.254.4.4/system"
}

resource "libvirt_volume" "centos-img-qcow2" {
  name = "centos-img-qcow2"
  pool = "vm-images"
  source = "/srv/images/CentOS-7-x86_64-GenericCloud.qcow2"
  format = "qcow2"
}

# See example: https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/network.markdown
resource "libvirt_network" "terra-net" {
   name = "terra-net"
   mode = "bridge"
   bridge = "br0"
   addresses = ["10.224.4.0/24"]
}

# Use CloudInit to add our ssh-key to the instance
resource "libvirt_cloudinit" "commoninit" {
   name = "commoninit.iso"
   pool = "vm-images"
   ssh_authorized_key = "ssh-rsa AAAAB3NzaC1yc..."
 }
resource "libvirt_domain" "centos" {
  name = "centos-terraform-2"
  memory = "512"
  vcpu = 1

  cloudinit = "${libvirt_cloudinit.commoninit.id}"

  network_interface {
     network_name = "terra-net"
  }

  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
      type        = "pty"
      target_type = "virtio"
      target_port = "1"
  }

  disk {
       volume_id = "${libvirt_volume.centos-img-qcow2.id}"
  }

  graphics {
    type = "spice"
    listen_type = "address"
    autoport = true
  }
}
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

In docs says bridge should work fine with existing bridges:
bridge: use a pre-existing host bridge. The guests will effectively be directly connected to the physical network (i.e. their IP addresses will all be on the subnet of the physical network, and there will be no restrictions on inbound or outbound connections). The bridge network attribute is mandatory in this case.

But when I try to run apply this error appears:
* libvirt_network.terra-net: Error crearing libvirt network: virError(Code=38, Domain=0, Message='error creating bridge interface br0: File exists')
___
# Additional Infos:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by samlabs821** [comment]
not relevant anymore

**Comment by MalloZup** [comment]
@mgunjan https://github.com/moio/sumaform/blob/1511370aee3407bcd927b6b834dcf6c5448fe129/modules/libvirt/host/main.tf#L38

and official doc here:
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/network.markdown#libvirt_network

Hope it helps!
