### ISSUE TITLE
Crowd Fund some updates to terraform-provider-libvirt

### ISSUE THREAD

**Issue by BruceBushby** [dmacvicar/terraform-provider-libvirt#295]
Anybody else interested in "crowd funding" some updates to this provider ? I'll kick off the pot with $100.00 

I need 
1. Clean up to build with latest terraform and other libraries (libvirt-go-xml)
2. Add ability to use command line or environment variables 

I tried building with "latest everything" however it looks like the definitions for "libvirt-go-xml" may have changed:

ok 12:35 root@dc00 ~/go/src/github.com/terraform-provider-libvirt 
# make build
bash travis/run-gofmt
==> Checking that code complies with gofmt requirements...
*** checking pkg libvirt with gofmt
 pkg libvirt has no lint gofmt errors!

*** running gofmt on main.go
==> go fmt OK !!! ***
golint ./libvirt
go vet .
go build
# github.com/terraform-provider-libvirt/libvirt
libvirt/disk_def.go:14:7: unknown field 'Type' in struct literal of type libvirtxml.DomainDisk
libvirt/domain.go:199:24: cannot use networkInterface.Source.Network (type *libvirtxml.DomainInterfaceSourceNetwork) as type string in append
libvirt/domain_def.go:13:7: unknown field 'Type' in struct literal of type libvirtxml.DomainFilesystem
libvirt/domain_def.go:40:10: unknown field 'Type' in struct literal of type libvirtxml.DomainGraphic
libvirt/domain_def.go:41:14: unknown field 'AutoPort' in struct literal of type libvirtxml.DomainGraphic
libvirt/domain_def.go:46:10: unknown field 'Type' in struct literal of type libvirtxml.DomainChannel
libvirt/domain_def.go:48:11: unknown field 'Type' in struct literal of type libvirtxml.DomainChannelTarget
libvirt/domain_def.go:49:11: unknown field 'Name' in struct literal of type libvirtxml.DomainChannelTarget
libvirt/domain_def.go:57:12: unknown field 'Model' in struct literal of type libvirtxml.DomainRNGBackend
libvirt/resource_libvirt_domain.go:668:50: domainDef.OS.KernelArgs undefined (type *libvirtxml.DomainOS has no field or method KernelArgs)
libvirt/resource_libvirt_domain.go:668:50: too many errors
make: *** [Makefile:4: build] Error 2

fail 12:35 root@dc00 ~/go/src/github.com/terraform-provider-libvirt 
#

**Comment by kskewes** [comment]
I'll do $50. It's been useful for labbing. 
Mine might be a user error, but I'm struggling to use a domain in a module as source multiple times. Doing a cloudinit per module with unique names so I can give VM's a unique hostname.

**Comment by biox** [comment]
Agreed, I'd also throw money in this pot (and help with some of the more simple work)

**Comment by dmacvicar** [comment]
Why not post it in some system like https://www.bountysource.com and then I can link them from the README?

**Comment by brejoc** [comment]
Alright, this issue is now referenced from [BountySource](https://www.bountysource.com/issues/57535849-crowd-fund-some-updates-to-terraform-provider-libvirt) and I've started with $20.

**Comment by kskewes** [comment]
Thanks for starting it. Chipped in 50 for #290.

**Comment by BruceBushby** [comment]
Thanks for starting, added $100.00

**Comment by dmacvicar** [comment]
Can you explain more about:

>Add ability to use command line or environment variables

**Comment by dmacvicar** [comment]
I have splited the dependencies part to https://github.com/dmacvicar/terraform-provider-libvirt/issues/320
Can anyone please:

* Update the bounty-source links
* Open an issue for the environment variables part, which is not very clear what is desired.

I would prefer to close this issue as it mixes different things.

**Comment by MalloZup** [comment]
thank you all :heart:  and @brejoc  for seting that up

**Comment by dmacvicar** [comment]
I claim the first part of the bounty through https://github.com/dmacvicar/terraform-provider-libvirt/pull/322
(minor some decisions that need to be made to merge it)

**Comment by BruceBushby** [comment]
Apologies for my delay in clarifying requirements, I have since moved on so
having to scratch my head to remember what motivated the idea in the first
place.

From my side, the two areas I was hoping for improvement were

1. Environment variables expanded correctly
2. Full implementation of libvirt-go library, for example the ability to
define the mac address in terraform and other libvirt-go functions that
were not present.



Bruce
