### ISSUE TITLE
"Remote" local volumes and HTTP volumes

### ISSUE THREAD

**Issue by hooksie1** [dmacvicar/terraform-provider-libvirt#299]
Trying to wrap my head around everything in here. What would it take to implement using a backing store on a remote server (qemu+ssh:///) or having it download the image over HTTP from the remote machine instead of downloading locally and copying?

**Comment by MalloZup** [comment]
@hooksie1  you can use the remote uri.

Machine one 1

```hcl
provider "libvirt" {
  uri = "qemu+tcp://remote-system.com/system"
}


# We fetch the latest ubuntu release image from their mirrors
resource "libvirt_volume" "ubuntu-qcow2" {
  name = "ubuntu-qcow2"
  pool = "default"
  source = "https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  format = "qcow2"
}
```

Remote server KVM will perform operation

**Comment by MalloZup** [comment]
The source image like `"http://web-server.com/fed-28-template.qcow2"   ` are downloaded to a golang stream and saved directly to libvirt volume which is in the KVM server. 
So there is no local-copy and then transfer to remote uri kvm server.
Instead everything happens on the remote-kvm server with the libvirt-api

So  taking your example

```hcl
provider "libvirt" {
        uri = "qemu+ssh://jhooks@10.1.30.30/system"
}

resource "libvirt_volume" "fedora-28" {
        name = "fedora-28.qcow2"
        source = "http://web-server.com/fed-28-template.qcow2"                                                                         
        pool = "VMs"
}
```
THe images/volume are uploaded on this server 10.1.30.30. and not were the provider is runnig. ( if you specify the remote URI as you did.
hopte it helps

**Comment by MalloZup** [comment]
@hooksie1  for any other question feel free to ask :+1:

**Comment by hooksie1** [comment]
Ok I uploaded a video to the youtubes https://youtu.be/Os1h29n4n2E. Sorry it's so long, but I was trying to get everything I'm seeing. If I run terraform from my laptop over wireless to the KVM server I see much slower transfer speeds than if I run terraform directly on the KVM server. If I lose connection to the remote web server holding the image the apply fails even though the KVM server can get to the image (did this by editing the hosts file for a fake failure). However if I lose the connection (by editing the hosts file) on the KVM server and running terraform on my laptop it still works?

I admit these don't mean that the laptop is copying the file, I made that assumption. But it does seem strange that the performance/behaviour would change that much from running on one system vs the other when only one should be doing the work.

Top left is my laptop. Bottom left and right are the KVM server. Using the same `test.tf` file I posted above, but with a different template URL so I didn't have to run the web server internally again (since I'm lazy).

**Comment by hooksie1** [comment]
Also sorry it's taken so long to respond. Started a new job and it's been busy.

**Comment by inercia** [comment]
@MalloZup I think images are imported using the `image` interface implemented [here](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/utils_volume.go) for _local_ and _http_ images, and called from the ["source"](https://github.com/dmacvicar/terraform-provider-libvirt/blob/02b30c6dd766ee9288f3c890659487a73004a7cc/libvirt/resource_libvirt_volume.go#L242) for volumes. So I think the download is performed in the machine where the provider is running...

Regarding a possible solution for this problem, unless libvirt could do the download for us (and AFAIK it  cannot do that), there is not solution for this...

**Comment by hooksie1** [comment]
Ah that makes sense @inercia, thanks.
