### ISSUE TITLE
Installation on Tumbleweed: nothing provides genisoimage needed by terraform-provider-libvirt

### ISSUE THREAD

**Issue by moio** [dmacvicar/terraform-provider-libvirt#305]
#  Version Reports:

### Distro  version of host:

openSUSE Tumbleweed

### Terraform Version Report

Irrelevant

### Libvirt version

Irrelevant

### terraform-provider-libvirt plugin version (git-hash)

Current `master`
___
# Description of Issue/Question

### Setup
None

### Steps to Reproduce Issue
```
zypper in terraform-provider-libvirt
```

## Actual results
```
Problem: nothing provides genisoimage needed by terraform-provider-libvirt-0.0.0+git20171027.feec1d19-1.11.x86_64
  Solution 1: do not install terraform-provider-libvirt-0.0.0+git20171027.feec1d19-1.11.x86_64
  Solution 2: break terraform-provider-libvirt-0.0.0+git20171027.feec1d19-1.11.x86_64 by ignoring some of its dependencies
```

## Hypothesized cause

`genisoimage` is being deprecated by several distros (such as [Debian](https://wiki.debian.org/genisoimage)) and `xorriso` seems the most likely successor. [Kiwi has already transitioned to `xorriso`](https://github.com/SUSE/kiwi/issues/635), and Tumbleweed recently dropped it.

Apparently cloud-init code was already adapted not to use genisoimage, so it should be a matter of updating the `spec` file (at least for Tumbleweed).

## Workaround

If cloud-init is not used, the dependency problem can simply be ignored

**Comment by MalloZup** [comment]
@moio  could you update the spec once you have time for the spec ?

Do you think is worth to have the spec here in github? :thinking: thx

**Comment by MalloZup** [comment]
https://build.opensuse.org/package/view_file/home:dmacvicar:terraform-provider-libvirt:stable/terraform-provider-libvirt/terraform-provider-libvirt.spec?expand=1

**Comment by moio** [comment]
Issue is still present, and requirement is still in the specfile:

```
Requires:       terraform >= 0.11.0
Requires:       libvirt-client
Requires:       mkisofs
```

https://build.opensuse.org/package/view_file/systemsmanagement:terraform:unstable/terraform-provider-libvirt/terraform-provider-libvirt.spec?expand=1
