### ISSUE TITLE
support more fields for domain configuration

### ISSUE THREAD

**Issue by arashsc** [dmacvicar/terraform-provider-libvirt#306]
there seems to be no way to pass a static mac address to the domain configuration.

 ### use case 
i need a dedicated ip for a virtual machine and my cloud provider restricts dedicated ips to predefined machine mac addresses

**Comment by kskewes** [comment]
Hi @arashsc 
This example works for me: https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/boot/libvirt.tf
I was able to use count interpolation with the MAC address too.

**Comment by arashsc** [comment]
@kskewes 
in the example, Mac address in assigned to a bridge interface whereas i need to set a static MAC address on each virtual machine independently. something like this:

```
// set boot order hd, network
resource "libvirt_domain" "domain-debian9-qcow2" {
  name = "debian9"
  memory = "1024"
  vcpu = 1
  mac = "Some MAC address"

  network_interface {
       bridge = "br0"
       mac = "52:54:00:b2:2f:86"
  }
...
}
```

**Comment by Bischoff** [comment]
@arashsc @kskewes apparently, the same goes for the `addresses =` setting : the IP addresses go to the bridge to the real host (`virbr1`) and not to the domain. I just did the test:
```
resource "libvirt_network" "private_network" {
  name = "mynetwork"
  mode = "none"
}
...
  network_interface {
       network_id = "${libvirt_network.private_network.id}"
       addresses = [ "192.168.5.1" ]
  }

23: virbr1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
  group default qlen 1000
    link/ether 52:54:00:ac:1a:30 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.1/24 brd 192.168.5.255 scope global virbr1
       valid_lft forever preferred_lft forever
```
So at least it's consistent.

In my case, that is perfect, because I needed an IP address on the bridge, not on the VM. But I agree that it at least needs some clarification in the documentation. Maybe it's even a bug.

**Comment by MalloZup** [comment]
Closing
