### ISSUE TITLE
When the source image is updated, the domains keeps the old filesystem's content

### ISSUE THREAD

**Issue by mbaquer6** [dmacvicar/terraform-provider-libvirt#307]
#  Version Reports:

### Distro  version of host:

```  Centos7 ```

### Terraform Version Report
(Provided by running `terraform -v`.)

### Libvirt version

```virsh --version```

### terraform-provider-libvirt plugin version (git-hash)

``` git log```
___
# Description of Issue/Question
Hello,
When I update the OS image running in QEMU with Terraform with another version, in the plan summary it shows that it will destroy the domains involved and create the new, as it should, but when I apply the new configuration, the machines keep the old file system contents (they even won't change their ip addresses or ECDSA fingerprints). The issue may be that the domains are not shutdown when they are removed and they keep accessing the old file blocks.

```
# instance the provider
provider "libvirt" {
  uri = "qemu+ssh://root@kvm_dev/system?socket=/var/run/libvirt/libvirt-sock"
}

resource "libvirt_volume" "eduac_img" {
  name = "eduac"
  pool = "images"

  #source = "http://10.10.0.19:7000/images/eduac"
}

resource "libvirt_volume" "volume" {
  name           = "webserver_${count.index}.qcow2"
  base_volume_id = "${libvirt_volume.eduac_img.id}"
  pool           = "images"

  #count          = "${var.webserver_count}"
  count = 1
}

# Create a network for our VMs 
resource "libvirt_network" "vm_network" {
  name      = "vm_network"
  addresses = ["10.0.4.0/24"]
  mode      = "nat"
  autostart = true
}

resource "libvirt_domain" "domain-centos" {
  count     = 1
  name      = "centos2-terraform${count.index}"
  memory    = "512"
  vcpu      = 1
  autostart = 1

  network_interface {
    hostname       = "centos${count.index}"
    network_name   = "vm_network"
    wait_for_lease = 1
  }

  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
    type        = "pty"
    target_type = "virtio"
    target_port = "1"
  }

  disk {
    volume_id = "${element(libvirt_volume.volume.*.id, count.index)}"
  }

  graphics {
    type        = "spice"
    listen_type = "address"
    autoport    = "true"
  }
}

# provider "dns" {
#   update {
#     server        = "192.168.5.145"
#     key_name      = "ns1.domain.com."
#     key_algorithm = "hmac-md5"
#     key_secret    = "secretkey"
#   }
# }

# resource "dns_a_record_set" "ps" {
#   zone  = "domain.com."
#   name  = "ps${count.index}"
#   count = 4

#   addresses = [
#     "${libvirt_domain.domain-centos.*.network_interface.0.addresses[count.index]}",
#   ]

#   ttl = 300
# }

# Print the Boxes IP
# Note: you can use `virsh domifaddr <vm_name> <interface>` to get the ip later
output "ip" {
  value = "${libvirt_domain.domain-centos.*.network_interface.0.addresses}"
}
```

### Setup
(Please provide the full **main.tf** file for reproducing the issue (Be sure to remove sensitive info)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

___
# Additional Infos:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by MalloZup** [comment]
ciao @mbaquer6 do you have a terraform.tf file that can show this behaviour for reproducing it?

**Comment by mbaquer6** [comment]
@MalloZup 
Hello,
Yes, I updated the description and added the main file.
Thanks.

**Comment by MalloZup** [comment]
@mbaquer6 thank for issue, i could not understand clearly your issue.

namely:
`When I update the OS image running in QEMU with Terraform with another version, `
what do you mean by that? you a distro-upgrade in the vm with a packet manager?  :thinking: 
TIA :+1:

**Comment by MalloZup** [comment]
Closing due od lack o info
