### ISSUE TITLE
graphics.0.autoport cannot parse

### ISSUE THREAD

**Issue by marcindulak** [dmacvicar/terraform-provider-libvirt#311]
#  Version Reports:

### Distro  version of host:

```
cat /etc/*release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 16.04.4 LTS"
```

### Terraform Version Report

```
terraform --version
Terraform v0.11.7
+ provider.libvirt (unversioned)
+ provider.template v1.0.0
```

### Libvirt version

```
virsh --version
1.3.1
```

```
echo $CGO_ENABLED
1
```

### terraform-provider-libvirt plugin version (git-hash)

https://github.com/dmacvicar/terraform-provider-libvirt/commit/b11e5b79ff40dc8f03d762d92226fabe315955dc

___
# Description of Issue/Question

The default example https://github.com/dmacvicar/terraform-provider-libvirt/blob/21c507a4c44b510196b8a4a527aca921e9cd9b11/examples/ubuntu/ubuntu-example.tf

```
cat ubuntu-example.tf 
# instance the provider
provider "libvirt" {
  uri = "qemu:///system"
}

# We fetch the latest ubuntu release image from their mirrors
resource "libvirt_volume" "ubuntu-qcow2" {
  name = "ubuntu-qcow2"
  pool = "default"
  source = "https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  format = "qcow2"
}

# Create a network for our VMs
resource "libvirt_network" "vm_network" {
   name = "vm_network"
   addresses = ["10.0.1.0/24"]
}

# Use CloudInit to add our ssh-key to the instance
resource "libvirt_cloudinit" "commoninit" {
          name           = "commoninit.iso"
          ssh_authorized_key = "<ssh-key-here>"
        }


# Create the machine
resource "libvirt_domain" "domain-ubuntu" {
  name = "ubuntu-terraform"
  memory = "512"
  vcpu = 1

  cloudinit = "${libvirt_cloudinit.commoninit.id}"

  network_interface {
    network_name = "vm_network"
  }

  # IMPORTANT
  # Ubuntu can hang is a isa-serial is not present at boot time.
  # If you find your CPU 100% and never is available this is why
  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
      type        = "pty"
      target_type = "virtio"
      target_port = "1"
  }

  disk {
       volume_id = "${libvirt_volume.ubuntu-qcow2.id}"
  }
  graphics {
    type = "spice"
    listen_type = "address"
    autoport = "yes"
  }
}

# Print the Boxes IP
# Note: you can use `virsh domifaddr <vm_name> <interface>` to get the ip later
output "ip" {
  value = "${libvirt_domain.domain-ubuntu.network_interface.0.addresses.0}"
}
```

```
TF_LOG=debug terraform apply -auto-approve
...
provider.libvirt - *terraform.NodeApplyableProvider
2018/06/29 16:25:50 [TRACE] Graph after step *terraform.CountBoundaryTransformer:
2018/06/29 16:25:50 [DEBUG] Starting graph walk: walkValidate
2018/06/29 16:25:50 [DEBUG] Resource state not found for "libvirt_network.vm_network": libvirt_network.vm_network
2018/06/29 16:25:50 [DEBUG] ReferenceTransformer: "libvirt_network.vm_network" references: []
2018/06/29 16:25:50 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [graphics.0.autoport: cannot parse '' as bool: strconv.ParseBool: parsing "yes": invalid syntax]
2018/06/29 16:25:50 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [graphics.0.autoport: cannot parse '' as bool: strconv.ParseBool: parsing "yes": invalid syntax]
2018/06/29 16:25:50 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: libvirt_domain.domain-ubuntu: graphics.0.autoport: cannot parse '' as bool: strconv.ParseBool: parsing "yes": invalid syntax
```

Changing `autoport = "yes"` to `autoport = "true" or autoport = "1"` seems to help.

**Comment by MalloZup** [comment]
@marcindulak thx for your issue report.

yop this is a bug 
https://github.com/dmacvicar/terraform-provider-libvirt/search?q=autoport&unscoped_q=autoport

I wonder why there is "yes", i mean the logical stuff should be to use true, 'yes' is more uncommon here.

**Comment by MalloZup** [comment]
@dmacvicar  i think you fixed this issue, can you confirm and close the issue?

**Comment by dmacvicar** [comment]
`autoport` is defined as boolean in the schema

However for some reasons we have examples using the libvirt style strings.
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/ubuntu/ubuntu-example.tf#L60

I don't understand why they would fail now. I don't remember changing the code after updating dependencies, so the parsing code would still do:

```go
if d.Get(prefix + ".autoport").(bool) {
```

Which invokes `strconv` IIRC, if it is a string, which parses "true" and false, but not "yes".

So either the examples where always broken, or something else changed.

I would say it is a bug on the HCL description, and we should fix the documentation. We might, however, improve the parsing code to accept those and may be add a warning.

**Comment by dmacvicar** [comment]
Reading other providers code, I can't find instances where a more liberal parsing is done. So I would just fix the documentation to remove the misleading "yes", the examples, and add a warning on the readme, for people porting libvirt xml to HCL,

**Comment by MalloZup** [comment]
@dmacvicar closing in favor of https://github.com/dmacvicar/terraform-provider-libvirt/pull/328
