### ISSUE TITLE
investigate if we can improve vendor mechanism following golang upstream (vgo)

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#318]
investigate if we might switch to use 

https://github.com/golang/dep

instead of glide

**Comment by dmacvicar** [comment]
Go dep will be obsoleted in favor of the [vgo concept](https://blog.golang.org/versioning-proposal), so I don't think this is worth. Lets wait for next go major release and switch to vgo.

**Comment by MalloZup** [comment]
@dmacvicar  thank you i will reading the article.

Ok i full agree if with you then :+1:

**Comment by MalloZup** [comment]
closing since when it will come we will known no need for keeping track.

thx for sharing the link anywayt
