### ISSUE TITLE
research about which opensource tool to use for meeting

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#319]
# Description.
Find out a tool opensource were we can do opensource meeting.

Any suggestion welcome

## tools at moment under consideration:

*    hangouts
*    zoom (free only for N? minutes)
*    bluejean

* https://discordapp.com/open-source

* https://jitsi.org/

## Requirements:

- screen sharing. 
- not much latency.
- opensource

**Comment by hexfusion** [comment]
FTR I have used the following with success

* hangounts
* zoom (free only for N? minutes)
* bluejean

**Comment by MalloZup** [comment]
@hexfusion  yop thx. 

imho hangouts could be ok ( it has videosharing).

As drawback we have that everybody need to have a google-account afaik.
 
bluejean i couldn't find any opensource version of it

**Comment by MalloZup** [comment]
i found also discord, i will look @ it

**Comment by MalloZup** [comment]
@dmacvicar from my pov we might try hangouts in test-mode.

As contra is that people need hangouts google account ( but i think mostly people dev golang has google account ? :laughing: ) 

I tried out the other tools, from my pov hangouts is the best from quality. 

I will try this tm with some small group of people

**Comment by MalloZup** [comment]
i tried out with 5 people was ok

**Comment by hexfusion** [comment]
@MalloZup can get the time/location of meeting today? I will try and make it.

**Comment by MalloZup** [comment]
@hexfusion i think for today we are will not doing it.

I'm waiting for @dmacvicar  which medium he want to use.  
I think maybe we can kickstart it next week, depends on @dmacvicar.
Let's wait :timer_clock: :sunflower:

**Comment by MalloZup** [comment]
https://janus.conf.meetecho.com/docs/

**Comment by MalloZup** [comment]
as we discussed briefly, we think that async communication is best way for interacting.

We can have meetings on fridays at 10.30 via irc gitter channel, and see if it fits, but as starting point is ok
