### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#320]
Originally reported [here](https://github.com/dmacvicar/terraform-provider-libvirt/issues/295)

Updating dependencies fails:

```
ok 12:35 root@dc00 ~/go/src/github.com/terraform-provider-libvirt 
# make build
bash travis/run-gofmt
==> Checking that code complies with gofmt requirements...
*** checking pkg libvirt with gofmt
 pkg libvirt has no lint gofmt errors!

*** running gofmt on main.go
==> go fmt OK !!! ***
golint ./libvirt
go vet .
go build
# github.com/terraform-provider-libvirt/libvirt
libvirt/disk_def.go:14:7: unknown field 'Type' in struct literal of type libvirtxml.DomainDisk
libvirt/domain.go:199:24: cannot use networkInterface.Source.Network (type *libvirtxml.DomainInterfaceSourceNetwork) as type string in append
libvirt/domain_def.go:13:7: unknown field 'Type' in struct literal of type libvirtxml.DomainFilesystem
libvirt/domain_def.go:40:10: unknown field 'Type' in struct literal of type libvirtxml.DomainGraphic
libvirt/domain_def.go:41:14: unknown field 'AutoPort' in struct literal of type libvirtxml.DomainGraphic
libvirt/domain_def.go:46:10: unknown field 'Type' in struct literal of type libvirtxml.DomainChannel
libvirt/domain_def.go:48:11: unknown field 'Type' in struct literal of type libvirtxml.DomainChannelTarget
libvirt/domain_def.go:49:11: unknown field 'Name' in struct literal of type libvirtxml.DomainChannelTarget
libvirt/domain_def.go:57:12: unknown field 'Model' in struct literal of type libvirtxml.DomainRNGBackend
libvirt/resource_libvirt_domain.go:668:50: domainDef.OS.KernelArgs undefined (type *libvirtxml.DomainOS has no field or method KernelArgs)
libvirt/resource_libvirt_domain.go:668:50: too many errors
make: *** [Makefile:4: build] Error 2

fail 12:35 root@dc00 ~/go/src/github.com/terraform-provider-libvirt 
#
```

**Comment by dmacvicar** [comment]
I already started working on this one. I figured it out, and I am doing progress.

**Comment by dmacvicar** [comment]
I have completed the port of the code, but as I am moving on running/porting tests, I realized the first compatibility victim:

* We depend on the https://github.com/terraform-providers/terraform-provider-ignition provider, that depends on terraform 0.10.x. (and vendors it)
* With the update, we jump to terraform 0.11.x libs
* We need either to disable the ignition provider code, or to pin our terraform dependency also to 0.10.x

Normally, it is not a problem, as the RPC protocol has not changed, but we are using the ignition provider at the API level.

I fear the ignition support will have to go. @eamonnotoole

**Comment by eamonnotoole** [comment]
@dmacvicar That's a pity, but on the other hand I don't know how many people are actually making use of ignition.

**Comment by MalloZup** [comment]
i am ok for removing it but i would open an issues to the ignition to ask to upgrade and send message to our gitter about the drop of backward compatibility.

**Comment by dmacvicar** [comment]
I just figured out it only affects the tests (thay instantiate the provider). We could keep it if we disable the tests that use resources from the original provider.

**Comment by dmacvicar** [comment]
Update was merged, and the ignition code was preserved.

Also all integration tests are working.
