### ISSUE TITLE
Refactor libvirt network creation to be in 1:1 correspondance with libvirt 

### ISSUE THREAD

**Issue by Bischoff** [dmacvicar/terraform-provider-libvirt#323]
Currently, we have code like
````
   addresses = [ "192.168.75.0/24" ]
````
that produces libvirt configuration like:
````
  <ip family='ipv4' address='192.168.75.1' prefix='24'>
    <dhcp>
      <range start='192.168.75.2' end='192.168.75.254'/>
    </dhcp>
  </ip>
````

While our current syntax is very concise, we have no control:
* on the host address (we systematically take `.1`)
* on the presence or absence of DHCP (we systematically use DHCP)
    (although addressed by https://github.com/dmacvicar/terraform-provider-libvirt/pull/321)
* on the start of the DHCP range (we systematically take `.2`)
* on the end of the DHCP range (we systematically take `.254`)

Suggestion is to refactor network generation to enable for a finer syntax like:
````
subnets = [
   { host_address = "192.168.75.1/24",
     dhcp = { start = "192.168.75.2", end = "192.168.75.254" } },
   { host address = "fde0::5:1/24",
      dhcp = { start = "fde0::5:2", end = "fde0::5:fe" } }
]
````

This is part of a general movement to make the libvirt provider match more closely with libvirt.

**Comment by Bischoff** [comment]
@MalloZup Yes, you're right, this is an epic.

As a starter, we could enable enable IPv6 on the host adapter. It would be very practical to provision machines with no IPv4 address at all (there is almost always an auto-configured IPv6 link-local address, and QEMU client provides that address if there is no IPv4). If you like, I can create the card.

More generally, it's all settings that are possible here:
* https://libvirt.org/formatnetwork.html
* https://libvirt.org/formatdomain.html#elementsNICS

**Comment by MalloZup** [comment]
closing as stale issue and since it is too generic (we will not close it ever :) ) , feel free to bring one specific issue in this direction.. thx
