### ISSUE TITLE
To be mentioned on relases notes

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#337]
This issues is for gathering PRs and improvements that were done on the provider.
So once we publish the releases-notes we don't forget about this improvements.

Feel free to add more :sunflower: @inercia @dmacvicar jfyi

https://github.com/dmacvicar/terraform-provider-libvirt/pull/336

**Comment by dmacvicar** [comment]
0.4 is released! https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.4
