### ISSUE TITLE
Survey: which terraform-libvirt conf files are for  you important used in PROD or everyday etc?

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#339]
this is a survey:
 i would like that you can post your `tf.files`  that you use in your Project, production or in your daily work flow.  ( without any sensitive data of course :dancer: :robot: ). 
The terraform files or use-cases that you care about.

Having this kind of files could help us to see also the usage and if we cover more or less all scenario with our testacc. ( if this tf files are to much complicated to execute with our testacc we can try to schedule them on a release basis)

**Comment by dmacvicar** [comment]
https://github.com/moio/sumaform/tree/master/modules/libvirt

**Comment by MalloZup** [comment]
https://github.com/kubic-project/automation/blob/master/caasp-kvm/cluster.tf.erb

**Comment by MalloZup** [comment]
https://github.com/openshift/installer/blob/5373f16f2322b243cad7ccb616368847d6516500/steps/masters/libvirt/main.tf

**Comment by MalloZup** [comment]
i am closing it because nobody answered really m anyway is ok was an experiment :sun_with_face:
