### ISSUE TITLE
Update aur pkg and doc more releases process

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#343]
https://aur.archlinux.org/packages/terraform-provider-libvirt/

Is using the 3.0. Can we build aur binary for archlinux? We need also, to update there
@dmacvicar  i would like to know if we can release also the binary in github for minor version like the 4.1 automatically. Tia

**Comment by dmacvicar** [comment]
* It should be possible to build for Arch. Building the package is something you can try locally copying the modified PKGBUILD to the project osc checkout.
* but I am not sure how to do the "publish only the plugin binary" part

* It should be possible to do releases automatically, however, right now writing the release changelog and waiting for all the binaries to build is still a manuall process
* Also, I am signing the binaries sha256, as OBS does no provide anything right now.

If you have concrete proposals, we can do any of both. Right now, given that we started with binaries just a week ago, I think we should learn a bit.

**Comment by dmacvicar** [comment]
(btw the reason why v0.4.1 was tagged and you did not see release is exactly that: I went to bed so that the binaries build and planned to release the next morning).

**Comment by MalloZup** [comment]
ye might have a look at https://github.com/cornelius/yes_ship_it for this kind of assertion concering relase. 
I tend to like the idea of cornelius. i will have a look on AUR pkg after :beach_umbrella:

**Comment by hexfusion** [comment]
I use Arch and could manage the aur package if that makes sense.

**Comment by dmacvicar** [comment]
I have no problem on adidng a PKGBUILD.

I am not sure how to build it like we do for Debian, where we reuse the same spec.

**Comment by MalloZup** [comment]
@hexfusion feel free to update the pkg there if you have time ! thx

At moment i think we are more focused on other stuff.
