### ISSUE TITLE
Use github templates

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#344]
https://github.com/dmacvicar/terraform-provider-libvirt/community
 There is  check list there for template we are missing. We might add some of them if make sense
For issues github provide 2 kind of, one for feature one for bugs. I think this is nice

**Comment by dmacvicar** [comment]
I am ok with introducing templates for the issues and templates, but I would expect a concrete proposal and reasoning for them (eg. one used by a similar project).

I don't see the need for the rest for now.
