### ISSUE TITLE
Add Network Model Configuration

### ISSUE THREAD

**Issue by ncsurfus** [dmacvicar/terraform-provider-libvirt#350]
#  Version Reports:

### Distro  version of host:

``` Ubuntu```

### Terraform Version Report
Terraform v0.11.7

### Libvirt version

```1.3.1```

### terraform-provider-libvirt plugin version (git-hash)
0.4
``` git log```
___
# Description of Issue/Question

Add support for other network model besides virtio. 
In file: resource_libvirt_domain.go, function: setNetworkInterfaces, there is this line of code which hardcodes the network model to virtio. Ideally, virtio should be the default but it would be nice to be able to set this to other values to add support for a wider amount of devices. I modified this locally to e1000 to validate it added network support for my specific use case.
```
		netIface := libvirtxml.DomainInterface{
			Model: &libvirtxml.DomainInterfaceModel{
				Type: "virtio",
			},
		}
```

___
# Additional Infos:

N/A

**Comment by dmacvicar** [comment]
What is the use-case nowadays to not use `virtio`?

**Comment by ncsurfus** [comment]
My use case is for Cisco vIOS and other virtualized routers/switches. The network model support for them is generally poor since their physical counterparts utilize ASICs and these virtualized devices are often meant for a testing / learning environment. Previously, I’ve hand built virtualized network environments to validate code against network devices. My goal is to be able to stand up these environments as part of the testing process (rather than a pre-built environment that I hope never breaks). Besides having to manually change the network model type, I’ve had a ton of success using this project!

**Comment by axxyhtrx** [comment]
+1

**Comment by dmacvicar** [comment]
I am in favor of this, even if it is not in the top of the list of the things I would spend my time on.

Before even accepting more "options" that change the schema, I am toying with the idea to add some hooks to the resources that would allow to set arbitrary values in the _libvirt_ _xml_ definition, that would help everyone with corner cases or custom configurations.

I was thinking something around the lines of:

```hcl
libvirt_domain "foo" {
   # ....
   xml = {
      "//devices/nic[0]/model/@type" = "e1000"  
  }
}
```
As a hook that would set the given _xpath_ values before creating the actual resource and after the provider has its own version of the _xml_ description done.

We would solve a much broader array of corner cases, even if we may choose to standardize some of these in the schema later, people would not need to wait and will have a workaround.

Let me think about it for some more time.

**Comment by MalloZup** [comment]
@ncsurfus we fixed it. Have look with latest release and doc on xslt.
https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/xslt.
