### ISSUE TITLE
Unable to set disk size when deploying from cloud image

### ISSUE THREAD

**Issue by mattymo** [dmacvicar/terraform-provider-libvirt#357]
#  Version Reports:

### Distro  version of host:

```  Ubuntu.. ```

### Terraform Version Report
Terraform v0.11.7

### Libvirt version
1.3.1

### terraform-provider-libvirt plugin version (git-hash)

``` git log```
___
# Description of Issue/Question

How can you use a cloud image (of Ubuntu for example) and create a libvirt_volume larger than the default qcow2 size provided by the source image?

### Setup
(Please provide the full **main.tf** file for reproducing the issue (Be sure to remove sensitive info)

Relevant bit:
```
resource "libvirt_volume" "ubuntu-qcow2" {
  name = "ubuntu-qcow2"
  pool = "default" 
  source = "https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  format = "qcow2"
}

resource "libvirt_volume" "volume" {
  name = "volume-${count.index}"
  base_volume_id = "${libvirt_volume.ubuntu-qcow2.id}"
  size = 42949672960 # 40gb
  count = 3
}
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
Error: Error applying plan:

3 error(s) occurred:

* libvirt_volume.volume[2]: 1 error(s) occurred:

* libvirt_volume.volume.2: 'size' needs to be specified if no 'source' or 'base_volume_id' is given
* libvirt_volume.volume[0]: 1 error(s) occurred:

* libvirt_volume.volume.0: 'size' needs to be specified if no 'source' or 'base_volume_id' is given
* libvirt_volume.volume[1]: 1 error(s) occurred:

* libvirt_volume.volume.1: 'size' needs to be specified if no 'source' or 'base_volume_id' is given
```
___
# Additional Infos:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by mattymo** [comment]
Workaround I have for now:
wget $CLOUD_IMAGE
qemu-img resize $CLOUD_IMAGE 40G
Put the path to image in my libvirt.tf

**Comment by dmacvicar** [comment]
`base_volume_id` uses the _COW_ funcionality of _qcow2_ to direct writtes to the volume on top so that you can share space between images that start from the same initial state. However, I am not aware that you can change the size of the resulting volume if you do this, as resizing it would mean changing the base `qcow2` and when using a base volume, the base `qcow2` is AFAIK read-only.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmacvicar** [comment]
I am closing this one as I don't think we will implement this ourselves.
