### ISSUE TITLE
Remove graphics from the default definition

### ISSUE THREAD

**Issue by Lennie** [dmacvicar/terraform-provider-libvirt#359]
#  Version Reports:

### Distro  version of host:

``` openSUSE 42.2/ Centos7/ Ubuntu.. ```

Debian 9.5

### Terraform Version Report
(Provided by running `terraform -v`.)

### Libvirt version

```virsh --version```

virsh 3.0.0

### terraform-provider-libvirt plugin version (git-hash)

``` git log```

commit 58cc06611667bbbdddafacb411cd6bc8da1c2b00
Author: Duncan Mac-Vicar P <dmacvicar@suse.de>
Date:   Tue Aug 14 14:35:35 2018 +0200

    Update changelog
___
# Description of Issue/Question

I ran into the same issue as:

https://github.com/dmacvicar/terraform-provider-libvirt/issues/65

Now I didn't need graphics anyway (the Ubuntu Cloud image I was using has tty/console set up and I can just use virsh console for that).

So I removed graphs from my .tf file, but looking at the debug it would still try to create the graphics.

So I disabled it in domain_def and it wasn't created anymore.

My suggestion would be to also do that in your repository/code. So when I don't request graphics to be created it will not add it to the XML for libvirt:

```
diff --git a/libvirt/domain_def.go b/libvirt/domain_def.go
index 09a41717..898ee07a 100644
--- a/libvirt/domain_def.go
+++ b/libvirt/domain_def.go
@@ -35,13 +35,13 @@ func newDomainDef() libvirtxml.Domain {
                },
                CPU: &libvirtxml.DomainCPU{},
                Devices: &libvirtxml.DomainDeviceList{
-                       Graphics: []libvirtxml.DomainGraphic{
+/*                     Graphics: []libvirtxml.DomainGraphic{
                                {
                                        Spice: &libvirtxml.DomainGraphicSpice{
                                                AutoPort: "yes",
                                        },
                                },
-                       },
+                       },*/
                        Channels: []libvirtxml.DomainChannel{
                                {
                                        Target: &libvirtxml.DomainChannelTarget{
```
___
# Additional Infos:

Thank you for your effort and time !

**Comment by MalloZup** [comment]
@Lennie thank you for the issue.
the spice is always created because a default value is set there.

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go#L238

I will look at this soon thx for reporting!

**Comment by MalloZup** [comment]
@Lennie i am closing in favor of https://github.com/dmacvicar/terraform-provider-libvirt/issues/84

which is the same issue thx!
