### ISSUE TITLE
domain update function is unused

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#361]
after  some investigation i found out that  this function: 
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go#L536

is never "covered by testacc" even when it should.

The `ForceNew` attribute on resource is forcing new resource instead of updating it.
The open question is why do we have the update call if we don't use it ( still searching)

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go#L54

**Comment by MalloZup** [comment]
@dmacvicar  do you know why we have the domain update function at L536?

i did git blame and found out: 
https://github.com/SUSE/spacewalk/issues/5485#issue-351253027

since we have default parameter that set ForceNew to true, we will never go to domainUpdate function

like https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go#L67

**Comment by dmacvicar** [comment]
`ForceNew` set to true in default parameters should not influence the calling of the _Update_ hook. As I understand the model it is when an attribute marked as `ForceNew` _CHANGES_ that the _Update_ hook not called, but the whole resource destroyed.

In this example, as our _Update_ hook does not implement switching the amount of memory _after_ the resource is created (we could investigate if libvirt supports that), then if you change the value after the domain is created, the provider would then have to recreate the domain.

If this is not working, I would suspect that there is an attribute with `ForceNew` being marked as _changed_ when nothing really _changed.
