### ISSUE TITLE
DPKG warning: maintainer is missing

### ISSUE THREAD

**Issue by sebastian-philipp** [dmacvicar/terraform-provider-libvirt#368]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 18.04 ```

### Terraform Version Report
Terraform v0.11.8

### terraform-provider-libvirt plugin version: 0.4.3-2.1

___

I'm getting this warning:
```
dpkg: Warnung: Parsen der Datei »/var/lib/dpkg/status«, nahe Zeile 48648 Paket »terraform-provider-libvirt«:
 maintainer fehlt
```
fehlt = missing.

**Comment by MalloZup** [comment]
thx

**Comment by MalloZup** [comment]
@dmacvicar  for this, i am not the OBS expert but it might be worth that we put the `spec` file in github so a contributor could fix this sort of issues?

Imho i dunno if OBS can allow to set the maintainer for `ubuntu/debian`.

**Comment by MalloZup** [comment]
@sebastian-philipp  if you want and know how to do it, you can send a Merge requests to 
https://build.opensuse.org/package/show/systemsmanagement:terraform/terraform-provider-libvirt

**Comment by sebastian-philipp** [comment]
@MalloZup , sorry, no.

For deb packages, you need a `Maintainer:` entry in the `debian/control` file. See the man page: https://linux.die.net/man/5/deb-control . How this is derived from the spec file? no idea.

**Comment by MalloZup** [comment]
@sebastian-philipp ok thx for sharing the infos , this already helps a little :+1: :smiley:

**Comment by dmacvicar** [comment]
I don't think we should add _Maintainers_, because:

* It is not a maintained package in Debian
* We don't distribute officially the .debs. We use them to generate the plain executables.

In case it is needed, can we add a url like this issues page?

**Comment by sebastian-philipp** [comment]
The specification mandates a "Maintainers" element. I.e. the warning is pretty severe and user visible. 

As long as there is any kind of "Maintainers" there, everything should be ok.

**Comment by dmacvicar** [comment]
What are the restrictions of the string on the Debian side? Can it be a URL? or does it need to be an email address?

**Comment by MalloZup** [comment]
@sebastian-philipp https://build.opensuse.org/request/show/702784  I think this should be enough in OBS

**Comment by MalloZup** [comment]
@dmacvicar merge that SRC for the pkg. Considering this closed ! thx

**Comment by erbap** [comment]
There is still no "Maintainer:" in the spec as far I can see.
Unpacking terraform-provider-libvirt (0.6.1+git.1578064534.db13b678-20.1) over (0.6.1+git.1577698985.12b905ac-18.1) ...
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 29779 package 'terraform-provider-libvirt':
 missing maintainer

**Comment by MalloZup** [comment]
ok lets' follow up in the next

**Comment by erbap** [comment]
Today an update on my Ubuntu:
terraform-provider-libvirt/unknown 0.6.1+git.1580485189.cc55d5d4-21.1 amd64 [upgradable from: 0.6.1+git.1578064534.db13b678-20.1]
But still:
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 32530 package 'terraform-provider-libvirt':
 missing maintainer

**Comment by MalloZup** [comment]
@erbap  can you try out now? https://build.opensuse.org/package/show/systemsmanagement:terraform/terraform-provider-libvirt

**Comment by MalloZup** [comment]
@erbap  join the new issue here https://github.com/dmacvicar/terraform-provider-libvirt/issues/644

**Comment by erbap** [comment]
Many thanks, problem solved.

Selecting previously unselected package terraform-provider-libvirt.
(Reading database ... 197174 files and directories currently installed.)
Preparing to unpack .../terraform-provider-libvirt_0.6.1+git.1580485189.cc55d5d4-22.1_amd64.deb ...
Unpacking terraform-provider-libvirt (0.6.1+git.1580485189.cc55d5d4-22.1) ...
Setting up terraform-provider-libvirt (0.6.1+git.1580485189.cc55d5d4-22.1) ...

**Comment by MalloZup** [comment]
@erbap thx a lot for your feedback :cupid: #opensource
