### ISSUE TITLE
Plugin not installed on Ubuntu

### ISSUE THREAD

**Issue by sebastian-philipp** [dmacvicar/terraform-provider-libvirt#370]
#  Version Reports: 

### Distro  version of host:

```Ubuntu 18.04```

### Terraform Version Report
(Provided by running `terraform -v`.)
```
 terraform -v
Terraform v0.11.8
+ provider.libvirt (unversioned)
```

### Libvirt version

```
$ virsh --version
4.0.0
```

### terraform-provider-libvirt plugin version (git-hash)

```
$ LANG=C apt search terraform-provider-libvirt
terraform-provider-libvirt/unknown,now 0.4.3-2.1 amd64 [installed]
  Terraform provider for kvm hypervisors via libvirt``
```
___
# Description of Issue/Question

### Steps to Reproduce Issue
```
$  terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "libvirt" not available for installation.  
...snip...
$  ll /usr/bin/terraform-provider-libvirt -rwxr-xr-x 1 root root 34M Aug 14 14:44 /usr/bin/terraform-provider-libvirt
$  mkdir ~/.terraform.d/plugins
$  cp /usr/bin/terraform-provider-libvirt ~/.terraform.d/plugins 
$  terraform init                                 

Initializing provider plugins...

Terraform has been successfully initialized!

...snip...
```
I would have expected that the plugin is either installed in the package, or these two commands should be part of the installation documentation: 
```
$  mkdir ~/.terraform.d/plugins
$  cp /usr/bin/terraform-provider-libvirt ~/.terraform.d/plugins 
``

**Comment by MalloZup** [comment]
@sebastian-philipp thx for issue. to make sense feel free to submit an OBS request

**Comment by sebastian-philipp** [comment]
Well, I don't think a deb package installation should modify the user's home directory. So, this is more like a general Terraform issue, or this can only be fixed in the documentation here on GitHub.

**Comment by MalloZup** [comment]
@sebastian-philipp https://github.com/dmacvicar/terraform-provider-libvirt#installing

On Linux and unix systems, in the sub-path .terraform.d/plugins in your user's home directory

**Comment by sebastian-philipp** [comment]
@MalloZup well, you first have to look for the installation location of the plugin. At least, I'd mention the location of the command. Right now, I had to use `dpkg-query -L terraform-provider-libvirt` to find the plugin.

**Comment by MalloZup** [comment]
@sebastian-philipp ok thx for infos. I'm using the golang source directly so i didn"t know about it
Yeah this would be really cool to make more compact the doc :+1:

**Comment by MalloZup** [comment]
@sebastian-philipp i was wondering if we just copy the binary to `/usr/bin` this is what the suse-pkg is doing, we could do the same for others distros, i think should work

**Comment by MalloZup** [comment]
i am in the way for making a SR to obs.

`%{__install} -p -m 755 $GOBIN/terraform-provider-libvirt ${buildroot}%/{_bindir}`

**Comment by MalloZup** [comment]
@dmacvicar  i added a obs MR https://build.opensuse.org/request/show/636193 ( unstable branch)

for installing to `/usr/bin` for not suse distros.

If we are ok we need also to backport the spec to the `stable` obs branch. 

closing
