### ISSUE TITLE
enable parallel tests

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#379]
depend on https://github.com/hashicorp/terraform/pull/18688

**Comment by MalloZup** [comment]
@dmacvicar  this is possible by next minor version of terraform the PR reference there got merged. 
(https://github.com/terraform-providers/terraform-provider-aws/issues/5874)

**Comment by bflad** [comment]
`v0.11.9-beta1` tag is now available upstream. 😄

**Comment by MalloZup** [comment]
@rphillips awesome thx!

**Comment by MalloZup** [comment]
Closing for moment
