### ISSUE TITLE
add dns enabled= true/false option 

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#391]
follow-up from https://github.com/dmacvicar/terraform-provider-libvirt/pull/376

https://github.com/dmacvicar/terraform-provider-libvirt/pull/376#issuecomment-418134394

**Comment by Bischoff** [comment]
Symptom:
```
13:19] <ebischoff> ebischoff@tegan:~/SCM/github/Bischoff/spacewalk> ps aux | grep dnsmas
[13:19] <ebischoff> dnsmasq  24228  0.0  0.0  73168  2240 ?        S    11:29   0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/ebi3-private.conf --leasefile-ro --dhcp-script=/usr/lib64/libvirt/libvirt_leaseshelper
```

There should be no result when `enabled = false`.

**Comment by praveenkumar** [comment]
As per newer version of libvirt dns can be disabled using `<dns enable='no'/>` and then that specific network interface will not be bind with the dnsmasq which help in case you want to bind that interface with different dns server.

**Comment by praveenkumar** [comment]
More info https://www.redhat.com/archives/libvir-list/2016-August/msg00641.html

**Comment by Bischoff** [comment]
ok, you're suggesting a way to implement this, @praveenkumar , if I understand well?

In my use case, I did not want to use different DNS server. I just wanted no DNS server :smile_cat: .

**Comment by praveenkumar** [comment]
@Bischoff I am going to spend some time and look into the code around how to implement it but even for my usecase I don't want to run any DNS server which is maintained by dnsmasq.

**Comment by Bischoff** [comment]
Cool, thanks Praveen for jumping into this issue.

**Comment by MalloZup** [comment]
thx

**Comment by blaggacao** [comment]
This one seems to be missing out on the docs: https://github.com/dmacvicar/terraform-provider-libvirt/issues/580
