### ISSUE TITLE
ssh key resources

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#4]
The main idea is to allow ssh key resources, and then locally assemble the cloud init metadata, wrap it into an iso and create a metadata volume for the instance resource uploading this created image.

cloud-init can use this disk as a metadata/userdata source to configure the ssh key.

**Comment by flavio** [comment]
I'm working on it

**Comment by flavio** [comment]
I think this can now be closed.
