### ISSUE TITLE
Unable to attach to existing bridge/and use local file

### ISSUE THREAD

**Issue by driftavalli** [dmacvicar/terraform-provider-libvirt#401]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 18.04.1 ```

### Terraform Version Report
Terraform v0.11.8
+ provider.libvirt (unversioned)

### Libvirt version

```4.0.0```

### terraform-provider-libvirt plugin version (git-hash)

``` Downloaded precompiled binary: terraform-provider-libvirt-0.4.3.Ubuntu_18.04.amd64.tar.gz```
___
# Description of Issue/Question
1. Terraform hangs when the source of the volume is specified in the format ```"${file("~/tmp/bionic...")}"```
2. Get an error saying default already exists. From the [libvirt documentation](https://libvirt.org/formatnetwork.html#examplesBridge), it looks like it should be possible to use an existing bridge
### Setup
```
provider "libvirt" {
  uri         = "qemu:///system"
}

resource "libvirt_volume" "ubuntu-qcow2" {
  name        = "ubuntu-qcow2"
  pool        = "default"
  source      = "https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img" //"${file("~/tmp/bionic-server-cloudimg-amd64.img")}"
  format      = "qcow2"
}

resource "libvirt_network" "default" {
  name        = "default"
  mode        = "bridge"
  bridge      = "br0"
}

resource "libvirt_cloudinit" "commoninit" {
  name        = "commoninit.iso"
  ssh_authorized_key  = "ssh-rsa ..."
}

resource "libvirt_domain" "domain-ubuntu" {
  name        = "ubuntu-terraform"
  memory      = "512"
  vcpu        = 1

  cloudinit   = "${libvirt_cloudinit.commoninit.id}"

  network_interface {
    network_name  = "default"
  }

  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
      type        = "pty"
      target_type = "virtio"
      target_port = "1"
  }

  disk {
       volume_id = "${libvirt_volume.ubuntu-qcow2.id}"
  }
  graphics {
    type = "spice"
    listen_type = "address"
    autoport = true
  }
}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
terraform apply

___
# Additional Infos:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?
None enabled

**Comment by MalloZup** [comment]
Hi @driftavalli  thanks for reporting.

https://github.com/dmacvicar/terraform-provider-libvirt/issues/364

i think we can close this  as duplicata

What is your err msg? is atm a known issue that if you have the net existing this will fail

**Comment by MalloZup** [comment]
@driftavalli i am closing this in favor of the #364. the bug is the same.

thank you for reporting !
