### ISSUE TITLE
domain already exists with uuid

### ISSUE THREAD

**Issue by Vanuan** [dmacvicar/terraform-provider-libvirt#423]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 18.04 ```

### Terraform Version Report

`v0.11.8`

### Libvirt version

```4.0.0```

### terraform-provider-libvirt plugin version (git-hash)

```0.4.4```
___
# Description of Issue/Question

```
provider "libvirt" {
  uri = "qemu+ssh://server.home/system"
}

resource "libvirt_domain" "test4" {
  name = "terraform_test4"
  memory = "1024"
  vcpu = 1 

}
```

For some reason terraform thinks it already exists, though I couldn't find it stored anywhere:

```
$ terraform apply

1 error(s) occurred:
* libvirt_domain.test3: 1 error(s) occurred:

* libvirt_domain.test4: Error defining libvirt domain: virError(Code=9, Domain=20, Message='operation failed: domain 'terraform_test4' already exists with uuid eba5ae24-0127-47c5-b4a9-91466c6228c5')

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

`virsh list` doesn't output anything. This is confusing

**Comment by MalloZup** [comment]
@Vanuan hi!
can you please try :
```sudo virsh list --all`` on your local machine and then to the remote server ```qemu+ssh://server.home/system"```

let me know if you don't find the domain with this, tia

**Comment by Vanuan** [comment]
Oh, yeah, I see them with `--all`:

```
sudo virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     terraform_test                 shut off
 -     terraform_test2                shut off
 -     terraform_test3                shut off
 -     terraform_test4                shut off
```

So virsh lists only running machines by default.
So the next question is can't terraform recreate those?
Or at least detect that these already exist?
Is it a normal situation that I have to delete failed machines manually rather than them being recreated by Terraform?

**Comment by Vanuan** [comment]
`virsh undefine terraform_test` works. After which `terraform apply` works normally

Ok so, it's only a problem for shut down machines. And terraform can't bring them up for some reason.
Thanks.

**Comment by Vanuan** [comment]
FYI, I also tried `terraform import` and it didn't work. So looks like a corner case for shutdown machines.

**Comment by MalloZup** [comment]
to me the point seems more  that we might not throw an error when a domain is shutdown, aka we should not trying to recreate an existing domain, instead we should just print `resource` is there and do nothing.

For the `bringing up` the domain i think that  maybe `terraform apply` maybe could  bringing them up if they are down, 

CC @dmacvicar

**Comment by MalloZup** [comment]
i will try to have a look thx

**Comment by wmariuss** [comment]
> to me the point seems more that we might not throw an error when a domain is shutdown, aka we should not trying to recreate an existing domain, instead we should just print `resource` is there and do nothing.
> 
> For the `bringing up` the domain i think that maybe `terraform apply` maybe could bringing them up if they are down, Actually this should work by default. ` running - (Optional) Use false to turn off the instance. If not specified, true is assumed and the instance, if stopped, will be started at next apply.`

Do we have a parameter for that?
