### ISSUE TITLE
Disabling disks is not possible

### ISSUE THREAD

**Issue by ghtyrant** [dmacvicar/terraform-provider-libvirt#437]
#  Version Reports:

### Distro  version of host:

``` Debian GNU/Linux 9.5 (stretch)```

### Terraform Version Report
terraform v0.11.8
+ provider.libvirt (unversioned)

I built this provider from source since Debian ships with libvirt 3.0.0, which doesn't work with the pre-built binaries.

### Libvirt version

```3.0.0```

### terraform-provider-libvirt plugin version (git-hash)

`4cc6d3ba0180c5c1afcbd2f37cbe8f6f8d93ccae`
___
# Description of Issue/Question
I want to be able to create/add disks conditionally. I have a skeleton main.tf with several configuration (.tfvars) files to create a bunch of VMs. These VMs can be configured to have optional data disks.
As far as I understand, this is not possible currently. I can have `count = "${var.data_disk > 0 ? 1 : 0}"` to only create the disk when data_disk is specified, but I can't disable the `disk` block inside the domain.

AFAIK other providers solve this by having pivot resources, e.g.:

```
resource "libvirt_disk" "mydatadisk" {
    domain_id = "${libvirt_domain.mydomain.id}"
    volume_id = "${libvirt_volume.myvolume}"
    scsi = true
}
```

That way, I can disable both libvirt_volume and libvirt_disk by setting their count to 0, resulting in no volume being created and no disk being attached to the domain.

### Setup
```
variable "name" {
  type = "string"
  description = "Name of the virtual machine"
}

variable "address" {
  type = "string"
  description = "Address of the virtual machine"
}

variable "cores" {
  type = "string"
  description = "Number of cores"
}

variable "memory" {
  type = "string"
  description = "Amount of RAM in MB"
}

variable "os_disk" {
  type = "string"
  description = "Size of OS disk in bytes"
}

variable "data_disk" {
  type = "string"
  description = "Size of data disk in bytes (optional)"
  default = 0
}

resource "libvirt_volume" "os_disk" {
  name = "${var.name}_os"
  pool = "vg0"
  size = "${var.os_disk}"
}

resource "libvirt_volume" "data_disk" {
  #count = "${var.data_disk > 0 ? 1 : 0}"
  name = "${var.name}_data"
  pool = "data"
  size = "${var.data_disk}"
  format = "qcow2"

  lifecycle {
    prevent_destroy = true
  }
}

resource "libvirt_domain" "domain" {
  name = "${var.name}"

  running   = true
  autostart = true

  disk {
    file = "/home/tyrant/salt-minion-debian-preseed/images/debian-9.5-amd64-CD-1.iso"
  }

  disk {
    volume_id = "${libvirt_volume.os_disk.id}"
  }

  disk {
    volume_id = "${libvirt_volume.data_disk.id}"
  }

  console {
    type        = "pty"
    target_type = "serial"
    target_port = "0"
  }

  console {
    type        = "pty"
    target_type = "virtio"
    target_port = "1"
  }
  vcpu = "${var.cores}"
  memory = "${var.memory}"
}
```
myvm.tfvars:
```
name = "myvm"
cores = 4
memory = 512
address = "192.168.100.4"
os_disk = 4294967296
```

Run `terraform apply -var-file=myvm.tfvars`

**Comment by MalloZup** [comment]
@ghtyrant hi! thank you for the issue.

I never tried that feature out. How could your feature beeing impacted with the new Terraform  v12 coming soon out? Would we use the same workflow ? ( https://www.hashicorp.com/blog/terraform-0-1-2-preview)

**Comment by ghtyrant** [comment]
Thanks for that link, I wasn't even aware of Terraform v12!

The changes to HCL would definitely solve this issue, especially [For and For-Each](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each) and maybe even [Conditional operator improvements](https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements).
Loops allow me to specify the data disks as a list of their size - an empty list results in no volumes and no disk blocks inside domain.
I'm not sure if I could use Conditionals to somehow assign null to the disk-block. If it's possible, that would be another way to solve this.

**Comment by zeenix** [comment]
We recently upgraded to TF v12 so I guess that solves your problem? So I'd close this one.

**Comment by MalloZup** [comment]
@zeenix thx! yop closing this
