### ISSUE TITLE
Release next version with cloudinit and publish pkg

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#438]
@dmacvicar  i need currently the new patch for cloudinit_disk released.

Can we release the next version without the `xlst`? :sake: :guitar:

**Comment by MalloZup** [comment]
## changelog:

https://github.com/dmacvicar/terraform-provider-libvirt/pull/416
https://github.com/dmacvicar/terraform-provider-libvirt/pull/410

**Comment by dmacvicar** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.5.0

**Comment by MalloZup** [comment]
:tada
