### ISSUE TITLE
VirtualBox support

### ISSUE THREAD

**Issue by lifeofguenter** [dmacvicar/terraform-provider-libvirt#439]
Would be great if VirtualBox could be fully supported: https://libvirt.org/drvvbox.html

**Comment by MalloZup** [comment]
@lifeofguenter  hi thx for issue to me just a first glance seems  a massive new feature.

However if the virtualBox driver use the same resource/names schema as the libvirt could be more easy.

I think need time and research on it, seeing also if the `virtualbox` support is not also conflicting with the actual design and codebase. 

Thx for issue ! :+1:

**Comment by lifeofguenter** [comment]
@MalloZup yes - it also seems like VirtualBox does things slightly different (e.g. for example does not support storage pools, making it currently impossible to use with this project). So not entirely sure how large the demand is :)

**Comment by MalloZup** [comment]
@lifeofguenter  ok it might worth a research use-cases. If it is massive different i think another provider project should be started int that case

**Comment by dmacvicar** [comment]
What is the use case, given that https://github.com/terra-farm/terraform-provider-virtualbox exists?

**Comment by MalloZup** [comment]
good point @dmacvicar  . @lifeofguenter  if your usage are covered by that plugin we can close this imho
