### ISSUE TITLE
opensSUSE tubleweed doesn't provide mkisofs

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#450]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/cloudinit_def.go#L144

When a user install the terraform-provider-libvirt this requirement doesn't get satisfied on tublweed distros

**Comment by ghtyrant** [comment]
The same is true for Debian, which ships a fork of it called genisoimage (https://wiki.debian.org/genisoimage). For me, it was enough to create a link from genisoimage to mkisofs - don't know how stable this is though, since both projects are developed independently.

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/269

**Comment by ghtyrant** [comment]
Good to know, thanks! :)

**Comment by MalloZup** [comment]
Actually the good solution would.be to research something else in other direction as iso imho if possible to remove this external binary dependency .

**Comment by MalloZup** [comment]
Maybe usb disk?

**Comment by dmacvicar** [comment]
I am confused. I use Tumbleweed.

```console
duncan@piscolita:~> cat /etc/os-release  | grep ^NAME=
NAME="openSUSE Tumbleweed"
duncan@piscolita:~> rpm -qf /usr/bin/mkisofs
mkisofs-3.02~a10-5.1.x86_64
duncan@piscolita:~> rpm -qi mkisofs | grep Distribution
Distribution: openSUSE Tumbleweed
```

So, @MalloZup , why do you claim `mkisofs` is not there, and according to you, what is the replacement on Tumbleweed?

**Comment by MalloZup** [comment]
@dmacvicar which `snapshot` version do you have of Tumbleweed?

**Comment by MalloZup** [comment]
i have discussed a bit with some people and confirmed that they `tubleweed` env was outdated and within the latest version the pkg was re-added. 
@ghtyrant feel free to open a issue for debian version if you wish, i will close this since was tublweed related.

Thx
