### ISSUE TITLE
Changelog 0.5.1 / 0.6

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#451]
- https://github.com/dmacvicar/terraform-provider-libvirt/pull/444 ( add `-version` flag)
- ..  (compressed image support WIP) 
- ..

**Comment by dmacvicar** [comment]
Closing this in favour of a release draft (which already exists for 0.5.2)

**Comment by MalloZup** [comment]
@dmacvicar ok thx i didn't saw it.. :+1:
