### ISSUE TITLE
Not support real PCI Passthrough?

### ISSUE THREAD

**Issue by fkpwolf** [dmacvicar/terraform-provider-libvirt#461]
#  Version Reports:

### Distro  version of host:

``` Ubuntu 16.04 ```

### Terraform Version Report

```sh
terraform -v
Terraform v0.11.10
```

### Provider and libvirt versions

```sh
terraform-provider-libvirt -version
.terraform/plugins/linux_amd64/terraform-provider-libvirt was not built correctly
Compiled against library: libvirt 1.3.1
Using library: libvirt 1.3.1
Running hypervisor: QEMU 2.5.0
Running against daemon: 1.3.1
```

If that gives you "was not built correctly", get the Git commit hash from your local provider repository:

```sh
git describe --always --abbrev=40 --dirty
1854aa93f614b0dfc54d5670bb27e9ac6bbda039-dirty
```
___
# Description of Issue/Question

### Setup
(Please provide the full **main.tf** file for reproducing the issue (Be sure to remove sensitive info)
```
diff --git a/examples/ubuntu/cloud_init.cfg b/examples/ubuntu/cloud_init.cfg
index dd29f27..5a243e0 100644
--- a/examples/ubuntu/cloud_init.cfg
+++ b/examples/ubuntu/cloud_init.cfg
@@ -15,5 +15,5 @@
 ssh_pwauth: True
 chpasswd:
   list: |
-     root:terraform-libvirt-linux
+     root:passw0rd
   expire: False
diff --git a/examples/ubuntu/ubuntu-example.tf b/examples/ubuntu/ubuntu-example.tf
index c65603e..91fa3c5 100644
--- a/examples/ubuntu/ubuntu-example.tf
+++ b/examples/ubuntu/ubuntu-example.tf
@@ -7,7 +7,7 @@ provider "libvirt" {
 resource "libvirt_volume" "ubuntu-qcow2" {
   name   = "ubuntu-qcow2"
   pool   = "default"
-  source = "https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img"
+  source = "/home/fan/ubuntu-16.04-server-cloudimg-amd64-disk1.img"
   format = "qcow2"
 }
 
@@ -39,7 +39,12 @@ resource "libvirt_domain" "domain-ubuntu" {
 
   network_interface {
     network_name = "default"
+    hostname = "new"
   }
+  network_interface {
+    passthrough = "enp2s16f6"
+  }
+
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

___
# Additional Infos:
The generated vm configuration has:
```
    <interface type='direct'>
      <mac address='aa:bb:cc:dd'/>
      <source dev='enp2s16f6' mode='passthrough'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </interface>
```
It will attach the host interface to vm with passthrough mode. The interface wasn't removed from host and assigned to vm. I think it should be:
```
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0x02' slot='0x10' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </hostdev>
```

**Comment by MalloZup** [comment]
thx for issue.Afaik not yet implemented

**Comment by MalloZup** [comment]
@fkpwolf  thx for issue

@inercia  maybe you have better insight here :smile: :japan:

**Comment by dmacvicar** [comment]
Can you try with https://github.com/dmacvicar/terraform-provider-libvirt/pull/431 using a xslt transform?

**Comment by fkpwolf** [comment]
thanks @dmacvicar. It is nice feature. But looks too advanced for me and for this task. I am not familiar with with xslt.
HCL(.tf file) is a kind of configuration language, and here introduce another one(xslt). I am not sure if this is a good idea.

**Comment by dmacvicar** [comment]
Ok, ignore everything I said.

I just realized we already support the _passthrough_ element, and this is about it not working. Then it is (probably, as we may not support all variations with a single attribute) a valid bug and we should read https://libvirt.org/formatdomain.html#elementsNICSHostdev and understand how it should work.

**Comment by amitinfo2k** [comment]
Hello Duncan Mac-Vicar P.,
Is there any plan to address this ?  Otherwise I have working patch which supports PCI Passthrough using (using 'hostdev'. element) would like to integrate it. 
Thanks,

**Comment by MalloZup** [comment]
hi @amitinfo2k  thank you for interest! 

We don't have any time in `short-term` to fix so a contribution from your part would be awesome. 

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/CONTRIBUTING.md
Feel free to work on this!

**Comment by fkpwolf** [comment]
any update on this? @amitinfo2k

**Comment by fkpwolf** [comment]
just submit a PR to address this issue #552. Looks I can't reuse existing `network_interface` element and have to create new type in schema. 

My test tf script is:
```
variable "hostdev_list" {
  default = [
    [{
      domain = 0
      bus = 1
      solt = 16
      function = 0
    }],
    [{
      domain = 0
      bus = 1
      solt = 16
      function = 2
    }],
    [{
      domain = 0
      bus = 1
      solt = 16
      function = 4
    }],
  ]
}

....
hostdev = "${var.hostdev_list[count.index]}"
```

**Comment by zeenix** [comment]
@fkpwolf The PR #552 was closed. I understood that you agreed that you can achieve the results you need with XSLT. So I'd suggest to @MalloZup to close this one but please feel free to reopen if that's not the case.

**Comment by MalloZup** [comment]
@zeenix  this isn't only a XSLT: https://github.com/dmacvicar/terraform-provider-libvirt/issues/461#issuecomment-438569134

**Comment by zeenix** [comment]
@MalloZup i saw that comment but PR was created based on that and the [last comment there ](https://github.com/dmacvicar/terraform-provider-libvirt/pull/552#issuecomment-466294793)indicates again that XSLT is probably the way forward.

**Comment by MalloZup** [comment]
closing.thx  @zeenix !!

**Comment by aep** [comment]
Hi!

this wont work for GPU i think?
would it make sense to just have a general xml option where users can add any virt xml?
