### ISSUE TITLE
adapt to computed property some values for resource_libvrt_network.go

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#463]
In codebase we have comment like this:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/4cc6d3ba0180c5c1afcbd2f37cbe8f6f8d93ccae/libvirt/resource_libvirt_network.go#L126

It might that terraform `schema` has specific mechanism/functions for fixing the comments.

**Comment by dmacvicar** [comment]
That is probably invalid. If it is required, but terraform validates "too early" means it is not provided by the user, which means, "computed".

**Comment by MalloZup** [comment]
yop i think we need to fix that

**Comment by MalloZup** [comment]
i have checked this is not possible closing for moment
