### ISSUE TITLE
Failures to change network_name on existing VM

### ISSUE THREAD

**Issue by bartekrutkowski** [dmacvicar/terraform-provider-libvirt#483]
#  Version Reports:

### Distro  version of host:

``` 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

### Terraform Version Report

```
Terraform v0.11.10
+ provider.libvirt (unversioned)
```

### Provider and libvirt versions

```
terraform-provider-libvirt 0.5.0
```
___
# Description of Issue/Question
When changing `network_name` (for example, from 'default' to 'public') on existing `network_interface` for already existing VM Terraform will report the change a successful, but in fact it won't change the network and subsequent runs will attempt (and again, report it successful) applying the change again. The VM will stay in the network that was defined initially. Stopping or rebooting the VM doesn't make any difference.

### Setup
```
resource "libvirt_volume" "freebsd_root" {
    name                = "freebsd_root"
    base_volume_name    = "FreeBSD-11.2-RELEASE-amd64.qcow2"
}

resource "libvirt_domain" "freebsd" {
    running   = "true"
    name      = "freebsd"
    autostart = "true"
    disk      = {
        volume_id = "${libvirt_volume.freebsd_root.id}"
    }
    memory    = "2048"
    vcpu      = "2"
    cpu {
        mode = "host-passthrough"
    }
    cloudinit = "${libvirt_cloudinit_disk.commoninit.id}"
    network_interface {
        network_name = "default"
    }
    console {
        type        = "pty"
        target_port = "0"
        target_type = "serial"
    }
}
```
### Steps to Reproduce Issue

1. Create VM with the above definition
2. Change the network name in the network interface
3. Run `terraform apply` to implement the change
4. Verify that despite terraform claiming the change was made it didn't applied it.
5. Run `terraform apply` to verify that terraform will once more try to implement the change and report success on it.
6. GOTO 4

___
# Additional Infos:

None.

**Comment by MalloZup** [comment]
@bartekrutkowski  thx for this issue, i think this is related to an issue we have currently on updating network and network domains https://github.com/dmacvicar/terraform-provider-libvirt/issues/389

**Comment by dmacvicar** [comment]
I see is as a duplicate, but it is not exactly the same. This is about updating the network interface, not the network, and this need a "design", as it involves [virDomainUpdateDeviceFlags](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainUpdateDeviceFlags)

Ideally we should revisit the whole _Update_ function of all resources, and track it in a single bug (probably updating the description of #389)
