### ISSUE TITLE
v0.5.0 binary not run on WSL because of libVirt 4.1 requirement

### ISSUE THREAD

**Issue by remoe** [dmacvicar/terraform-provider-libvirt#488]
#  Version Reports:

### Distro  version of host:

```Ubuntu 18.04.1 LTS (Bionic Beaver)```

### Terraform Version Report

```Terraform v0.11.10```

__
# Description of Issue/Question

Can't run terraform-provider-libvirt 0.5 binary on Windows WSL:

https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.5.0/terraform-provider-libvirt-0.5.0.Fedora_28.x86_64.tar.gz

It throws:

```/usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_4.1.0' not found```

It works when i build it from source. But why is this newer version of Libvirt needed? Ubuntu provides libVirt 4.0.

**Comment by MalloZup** [comment]
@remoe hi thx for issue.
When you build the pkg from source, it build against the `libvirt-devel` of the host where you build, so this is why it works when you build from source.

For the `0.5.0` fedora pkg, that pkg was builded against that HEADER of Libvirt-Devel and and fedora 28 provide the 4.1  https://fedora.pkgs.org/28/fedora-x86_64/libvirt-devel-4.1.0-2.fc28.x86_64.rpm.html

**Comment by remoe** [comment]
thanks for this detailed explanation.
