### ISSUE TITLE
Support for live migration

### ISSUE THREAD

**Issue by thundertaker** [dmacvicar/terraform-provider-libvirt#490]
#  Version Reports:

### Distro  version of host:

```
Ubuntu 18.04.1 LTS
```

### Terraform Version Report

```sh
Terraform v0.11.10
```

### Provider and libvirt versions

```sh
apt show terraform-provider-libvirt
[ ... ]
Version: 0.5.0-6.1
[ ... ]
```
___
# Description of Issue/Question

Libvirt with qemu-kvm hypervisor has a live migration feature: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-kvm_live_migration-live_kvm_migration_with_virsh

It would be very nice to have this, for example, when changing provider `alias` in `libvirt_*` resources.
It's very likely that it will require some additional configuration on `provider` block or somewhere else.

**Comment by MalloZup** [comment]
Indeed on the user level i think could be a nice feature, thx for bringing this up. On the tech pov we can figure out . Thx!

**Comment by zeenix** [comment]
While this really is one of the impressive features of libvirt, in practice I've not seen it to be very useful in the end. You can't even migrate a simple VM with one volume from session connection to system on the same host:

```
$ virsh migrate --live fedora29-wor qemu+unix:///system
error: Unsafe migration: Migration without shared storage is unsafe
```

So I'd close it unless there is a real push for this.
