### ISSUE TITLE
Destroy domain doesn't destroy if the domain is libvirt_destroyed (shutdown)

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#491]
# How to reproduce: 

```hcl
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_domain" "domain" {
  name = "domain-terra"
}
```

This create the domain.

2) `virsh destroy domain-terra`

3) `terraform destroy` will not destroy the domain.

I think we should undefine the domain even if it is `shutdown`

**Comment by MalloZup** [comment]
@inercia @dmacvicar  any thoughts about this, i think we should destroy the domain if even it shutdown.

**Comment by dmacvicar** [comment]
_destroy_ in terraform means the resource should be gone. That is indeed _undefine_.

Now, _resourceLibvirtDomainDelete_ already calls _undefine_. I tried the _boot_ example and could not reproduce it. The domain was undefined.

Can you run _destroy_ with TF_LOG=debug and show us why it stays there?

**Comment by MalloZup** [comment]
Yop i will update status tm with debug no pb

**Comment by MalloZup** [comment]
@dmacvicar  yop you are right, i think it was my mistake, i retry it now and the domain could get destroyed.

Thx and sorry :sunflower: closing

**Comment by easyawslearn** [comment]
@MalloZup  can you please suggest the solution I am facing the same issue

**Comment by MerreM** [comment]
I have a similar issue with storage pools - they're neither emptied no undefined is this expected?
