### ISSUE TITLE
validate_terraform_files.sh succeeds when terraform command does not exist

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#496]
```console
travis/validate_terraform_files.sh
+cd examples
++wc -c
++terraform fmt
travis/validate_terraform_files.sh: line 4: terraform: command not found
+'[' 0 -ne 0 ']'
The command "travis/validate_terraform_files.sh" exited with 0.
```

**Comment by MalloZup** [comment]
this now fail correctly. https://travis-ci.org/dmacvicar/terraform-provider-libvirt/builds/461170100?utm_source=github_status&utm_medium=notification

`
0.04s$ travis/validate_terraform_files.sh
+cd examples
++wc -c
++terraform fmt
+'[' 13 -ne 0 ']'
+echo 'terraform files need be formatted! run terraform fmt!'
terraform files need be formatted! run terraform fmt!
+exit 1
The command "travis/validate_terraform_files.sh" exited with 1.

`
