### ISSUE TITLE
Enhancement : Support cpu pinning

### ISSUE THREAD

**Issue by amitinfo2k** [dmacvicar/terraform-provider-libvirt#499]
I had a usecase where I need to pin CPU to VM. In current provider plugin there is no option for CPU pinning.
It will good to have that.

**Comment by MalloZup** [comment]
hi @amitinfo2k  you can already add this feature by using XSLT. Have a look at this 
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/xslt/main.tf :+1: if you have question feel free to ping me

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown#altering-libvirts-generated-domain-xml-definition

**Comment by amitinfo2k** [comment]
Let me try xslt (not much familier) but, i would have preferred to have 'cputune' attribute exposed in the terraform template.I have done the changes which works for me.I would like to push those.

**Comment by MalloZup** [comment]
We enabled xslt because exposing quickly variables in terraform,  was adding complexity and bugs in the past and also since we want to make all people happy without coding. If you have a pr feel free to submit it, this is always welcome. Thw

**Comment by MalloZup** [comment]
closing as this can be fixed with `xslt`
