### ISSUE TITLE
Add progress to volume download/upload

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#5]
May be using https://gowalker.org/github.com/mitchellh/ioprogress

**Comment by flavio** [comment]
I looked a bit into that, it looks like this is not possible because terraform takes full control of the stdout/stderr preventing the progressbar from being shown.

I someone else has any idea about how to circumvent this limitation...

**Comment by dmacvicar** [comment]
Well, we could still send a log message every eg. 5% right?

**Comment by italomaia** [comment]
Does any other provider manage to do this? Why not mimic other plugin?

**Comment by MalloZup** [comment]
@dmacvicar to me we could close it since i doubt we will have time/research for this ( and looking for terraform is not something easy to take control the stdout/err
