### ISSUE TITLE
Enhancement: ability to configure USB model = none

### ISSUE THREAD

**Issue by mykaul** [dmacvicar/terraform-provider-libvirt#508]
It'd be great if you could NOT configure USB devices by default.
The XML is simple:
<controller type='usb' model='none'>

**Comment by MalloZup** [comment]
@mykaul not having USB enabled by default, which advantage would bring it? i am just curious. tia

**Comment by mykaul** [comment]
Performance: At least (the old only?) USB controller used to be polling - a periodic interrupt, consuming (small, insignificant?) CPU resources. 
Security: reduced surface attack.

Nothing substantial, really.

**Comment by MalloZup** [comment]
i have just grouped this small enhancements
