### ISSUE TITLE
Enable shared disks usage between created VM-s

### ISSUE THREAD

**Issue by arbulu89** [dmacvicar/terraform-provider-libvirt#514]
#  Version Reports:

### Distro  version of host:

``` openSUSE Leap 15.0```

### Terraform Version Report

```Terraform v0.11.10```

### Provider and libvirt versions
libvirt version:
```libvirtd (libvirt) 4.0.0```

terraform-provider-libvirt plugin version (git-hash)

Current master: afd5c1a78fab19313cbacc9b56dbc5cf6024cae9
___
# Description of Issue/Question

In some of our developments we need to use shared disks between our VM-s. By now this is not supported as terraform complains when an already existing disk is attached to a domain.

Libvirt supports shared disks (disabling caching).

Vagrant has a similar feature for example. Here more info:
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/648

**Comment by arbulu89** [comment]
@inercia thank you for your answer. I have tried your suggestion and apparently everything worked fine! I guess that this "workaround" is good enough by now.
Thanks!

**Comment by MalloZup** [comment]
@arbulu89 thx for issue. and thx @inercia :cupid: 

I think we can let this issue open  because of the `disks` behaviour which we could improve in middle-term/longterm

**Comment by MalloZup** [comment]
we fixed this with XSLT. I think it is not worth to have it in upstream, It will be worth but not enough time to spend on it .
