### ISSUE TITLE
Improve error msg of timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s

### ISSUE THREAD

**Issue by colachg** [dmacvicar/terraform-provider-libvirt#536]
#  Version Reports:

### Distro  version of host:

``` Ubuntu18.04 ```

### Terraform Version Report

```sh
Terraform v0.11.11
+ provider.libvirt (unversioned)
+ provider.template v1.0.0
```

### Provider and libvirt versions

```sh
terraform-provider-libvirt was not built correctly
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Running hypervisor: QEMU 2.11.1
Running against daemon: 4.0.0
```

If that gives you "was not built correctly", get the Git commit hash from your local provider repository:

```sh
b7dab08a9194e388a7f043a1ab7fe60d241b50e5
```
___
# Description of Issue/Question

### Setup
(Please provide the full **main.tf** file for reproducing the issue (Be sure to remove sensitive info)
```
# instance the provider
provider "libvirt" {
  uri = "qemu+ssh://${var.host_ip}/system"
}

# terraform version check
terraform {
  required_version = "> 0.11.10"
}

# We fetch the latest ubuntu release image from their mirrors
resource "libvirt_volume" "ubuntu-qcow2" {
  count = "${var.masters_count}"
  name   = "${var.machine_name}_${count.index + 1}_system"
  pool   = "default"
  source = "/home/developer/Downloads/ubuntu-16.04-server-cloudimg-amd64.img"
}

resource "libvirt_volume" "data_volume" {
  count = "${var.masters_count}"
  name = "${var.machine_name}_${count.index + 1}_data"
  pool = "${var.vg_name}"
  size = "${var.storage_size}"
}

data "template_file" "user_data" {
  template = "${file("${path.module}/cloud_init.cfg")}"
}

# for more info about paramater check this out
# https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/cloudinit.html.markdown
# Use CloudInit to add our ssh-key to the instance
# you can add also meta_data field
resource "libvirt_cloudinit_disk" "commoninit" {
  name           = "commoninit-master.iso"
  user_data      = "${data.template_file.user_data.rendered}"
  # network_config = "${data.template_file.network_config.rendered}"
}

# Create the machine
resource "libvirt_domain" "Ubuntu" {
  count = "${var.masters_count}"
  name = "k8s-master${count.index + 1}"
  memory = "${var.memory}"
  vcpu   = "${var.cpu}"
  qemu_agent = true

  cloudinit = "${libvirt_cloudinit_disk.commoninit.id}"

  network_interface {
    # network_name = "default"
    macvtap = "eno1"
    wait_for_lease = true
    hostname = "k8s-master${count.index + 1}"
  }

  # IMPORTANT: this is a known bug on cloud images, since they expect a console
  # we need to pass it
  # https://bugs.launchpad.net/cloud-images/+bug/1573095
  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
    type        = "pty"
    target_type = "virtio"
    target_port = "1"
  }

  disk {
    # volume_id = "${libvirt_volume.ubuntu-qcow2.id}"
    volume_id = "${element(libvirt_volume.ubuntu-qcow2.*.id, count.index)}"
  }

  disk {
    # volume_id = "${libvirt_volume.data_volume.id}"
    volume_id = "${element(libvirt_volume.data_volume.*.id, count.index)}"
  }

  graphics {
    type        = "vnc"
    listen_type = "address"
    autoport    = true
  }
}

output "ip" {
  value = "${libvirt_domain.Ubuntu.*.network_interface.0.addresses}"
}

```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`terraform init`
`terraform apply`
```
Error: Error applying plan:

2 error(s) occurred:

* libvirt_domain.Ubuntu[0]: 1 error(s) occurred:

* libvirt_domain.Ubuntu.0: timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)
* libvirt_domain.Ubuntu[1]: 1 error(s) occurred:

* libvirt_domain.Ubuntu.1: timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)
```
___
# Additional Infos:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
SELinux disabled
Have you tried to reproduce the issue without them enabled?

**Comment by abbbi** [comment]
You do not seem to define any network resource, still you are waiting for the lease, using a macvtap device. How is the VM supposed to get an IP address? The plugin times out waiting on the dhcp lease for the network address.

**Comment by colachg** [comment]
I follow this:
> Note: when using bridge network configurations you need to enable the qemu_agent = true. otherwise you will not retrieve the ip adresses of domains

@abbbi  
Yes, I didn't define any network resource.Because I  want the VM to get an IP address of the LAN using the macvtap device.
I have used the `default` network, I can get the NAT(ed) IP address(like: 192.168.122.22).This is not my scenario.  
Do you mean if I don't define network resource the VM can not get an IP address or the terraform can not  retrieve the ip adresses of domains even if domains get IPs?

@MalloZup 
Maybe I missed something, I want to know how can I print out  the IP addresses in my scenario?

Thanks for your time :)

**Comment by MalloZup** [comment]
You need to install the qemu agent  pkg on your vms and enable it. This should give you the ip

**Comment by colachg** [comment]
@MalloZup Thanks

**Comment by MalloZup** [comment]
@colachg  for this issue i pushed a PR in wip right now. 

https://github.com/dmacvicar/terraform-provider-libvirt/pull/537.
I would like that also you help there regarding the Error msg suggestion. Is kind wip there for moment. 
I'm closing this issue.
For the 2nd issue you faced is not something we can provide help because this are `libvirt` specific issues which we cannot fix. thx and enjoy.
:sunflower:
