### ISSUE TITLE
Feature Request: Target Multiple Hypervisors

### ISSUE THREAD

**Issue by johnavp1989** [dmacvicar/terraform-provider-libvirt#54]
Currently the uri of the hypervisor is defined in the provider block. Since terraform only allows one provider per config it's not possible to target more than one hypervisor.

```
provider "libvirt" {
  uri = "qemu:///system"
}
```

This feature would make it possible to deploy multiple VM's across multiple hosts with a single apply operation. This is especially useful for clustered applications such as Kubernetes.

**Comment by toddnni** [comment]
To my understanding you can have multiple providers by defining multiple provider blocks with different alias names. See https://www.terraform.io/docs/configuration/providers.html

I think I have even tested this in past.

**Comment by xenolog** [comment]
> To my understanding you can have multiple providers by defining multiple provider blocks
This way is lead to one more complicated problem -- what about networks.
IMHO if we have able to use multiple hypervisors, we should provide transparent networking for instances, running on different hypervisors. Also we should able to define hypervisor which will be used for start instances.

It looks like one provider with a list of hypervisors uri should be better.

**Comment by inercia** [comment]
I think this would add a lot of complexity just for saving some extra `terraform apply`s. I think it is not really worth.

**Comment by flavio** [comment]
I agree with @inercia, closing.
