### ISSUE TITLE
CentOS binaries are not building

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#545]
CentOS build can't find golang package. I can't recall if we had some magic for that, and why it stopped working.

* I recall CentOS 7 never having golang package, but I think we had some magic to reuse the golang binary from a different target

https://build.opensuse.org/project/show/systemsmanagement:terraform:unstable

**Comment by rsjethani** [comment]
Can you list out exact steps followed while packaging CentOS distribution?

**Comment by MalloZup** [comment]
Hi @rsjethani you will need to have obs knowledge on obs system, if you want to take this issue I will help on the road with all the infos

**Comment by MalloZup** [comment]
Hi @rsjethani you will need to have obs knowledge on obs system, if you want to take this issue I will help on the road with all the infos

**Comment by dmacvicar** [comment]
>Can you list out exact steps followed while packaging CentOS distribution?

@rsjethani We just build the source in a .spec file against various distributions. Here is the spec:
https://build.opensuse.org/package/view_file/systemsmanagement:terraform:unstable/terraform-provider-libvirt/terraform-provider-libvirt.spec?expand=1

The result ends as a rpm. There is one step that copies the binary into a OTHER directory. That is used to also output plain tarballs with the binary (non-rpms).

**Comment by rsjethani** [comment]
Thanks @MalloZup @dmacvicar I will start by understanding obs and rpm basics

**Comment by dmacvicar** [comment]
This may help you: https://duncan.codes/tutorials/rpm-packaging

**Comment by rsjethani** [comment]
On centos7 golang is available via epel-release repo

**Comment by dmacvicar** [comment]
I see the binaries are being built again... but I don't recall we did anything to fix it

**Comment by MalloZup** [comment]
no we didn't. to me is that on the `obs` side the `unresolvable` pkg for centos7 was fixed and consequently it fixed also our sub-problem.

thx for closing it :tulip:
