### ISSUE TITLE
Is it a way to have mac address libvirt-like

### ISSUE THREAD

**Issue by Isma399** [dmacvicar/terraform-provider-libvirt#547]
For now, mac address seem to be generated randomly.
Is it a way to the libvirt prefix vendor (ie: 52:54:00) at the beginning of the mac address created.

It's quite comfortable to know where come network flow with this type o MAC address.

Thank you for your answer and for your provider too!

**Comment by Isma399** [comment]
Yes!
Thank you.
From manpage for virt-install (https://linux.die.net/man/1/virt-install):

> 
> mac
> Fixed MAC address for the guest; If this parameter is omitted, or the value "RANDOM" is specified a 
> suitable address will be randomly generated. For Xen virtual machines it is required that the first 3 
> pairs in the MAC address be the sequence '00:16:3e', while for QEMU or KVM virtual machines it must > be '52:54:00'. 

I suppose it's still relevant.
I'll will give a try tomorrow. That will be my first time in Go!

**Comment by Isma399** [comment]
Hello,
I modifiy the code to have libvirt-like mac address and install the plugin and a Centos7 fresh install.
I successfully created a VM with the expected Mac Address (ie: 52:54:00:FA:F9:7D).
I then scp the plugin to my instance prod server, and run "terraform init" (init OK) and then "terraform plan" and I've got this error:
Error: Error asking for user input: 1 error(s) occurred:
* provider.libvirt: plugin exited before we could connect

I suppose it's a terraform error, do i have to update the version?
Thanks

**Comment by inercia** [comment]
> I then scp the plugin to my instance prod server, and run "terraform init" (init OK) and then "terraform plan" and I've got this error:
> Error: Error asking for user input: 1 error(s) occurred:
> 
> * provider.libvirt: plugin exited before we could connect
> 
> I suppose it's a terraform error, do i have to update the version?

I would try to run the plan [with debug logs](https://www.terraform.io/docs/internals/debugging.html), like `TF_LOG=1 terraform plan`. This will print a lot of information to the _stderr_ and then you will have to figure out from those logs what is happening...

**Comment by MalloZup** [comment]
fixed closing

**Comment by MalloZup** [comment]
thx @Isma399 :rocket:
