### ISSUE TITLE
virError

### ISSUE THREAD

**Issue by kee001** [dmacvicar/terraform-provider-libvirt#551]
##  System Information
libvirt_domain.domain-ubuntu: Error defining libvirt domain: virError(Code=27, Domain=20, Message='XML error: file '/dev/urandom' is not a supported random source')
---
control:
Terraform version v0.11.11
---
server:
Ubuntu 16.04
libvirt versions 1.3.1

**Comment by kee001** [comment]
virError

**Comment by MalloZup** [comment]
@kee001 please follow http://manpages.ubuntu.com/manpages/xenial/man4/random.4.html.
Your error is more on your System side. We can keep this issue open. 
We changed time ago from `random` to `urandom`.

**Comment by abbbi** [comment]
I think its an too old libvirt version. Support vor /dev/urandom might not have been added in the libvirt version OP is running. I have had the same issue on Ubuntu 16.04.2 LTS with libvirt 1.3.1-1ubuntu10.24 installed.

Apparently there is no way to change this behavior in libvirt other than updating it to a newer version.

**Comment by kee001** [comment]
> @kee001 thx for issue. Can you please try to follow http://manpages.ubuntu.com/manpages/xenial/man4/random.4.html and see if it solves for you?
> Your error is more on your System side. Imho depending on the OS. We can keep this issue open.
> We changed time ago from `random` to `urandom`

Thanks for the feedback! 
server:
# systemctl status libvirt-bin 
Feb 10 02:51:47 server6 libvirtd[2107]: XML error: file '/dev/urandom' is not a supported random source

**Comment by abbbi** [comment]
> # server: systemctl status libvirt-bin
> Feb 10 02:51:47 server6 libvirtd[2107]: XML error: file '/dev/urandom' is not a supported random source

yes, you either neet to update your libvirt version or override the default random source to /dev/random using the xslt feature.

**Comment by MalloZup** [comment]
Closing thx

**Comment by jjjbushjjj** [comment]
> 
> 
> > # server: systemctl status libvirt-bin
> > Feb 10 02:51:47 server6 libvirtd[2107]: XML error: file '/dev/urandom' is not a supported random source
> 
> yes, your libvirt verison is too old and does not yet support /dev/urandom as random source. You either need to update your libvirt version or override the default random source to /dev/random using the xslt feature. (https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/xslt)

Could you provide xsl for it please?

**Comment by NZSmartie** [comment]
A work around for those stuck with an older version of libvirt may set the environment variable `TF_LIBVIRT_RNG_DEV`
```bash
export TF_LIBVIRT_RNG_DEV=/dev/random
```
source: https://github.com/dmacvicar/terraform-provider-libvirt/blob/753afd8a074e74334821006e4b4e321e63214ff7/libvirt/domain_def.go#L86-L90

**Comment by kkhamruddin-pk** [comment]
> v1.3.4

How to upgrade libvirt v1.3.1 to v1.3.4 in ubuntu 16.04?

**Comment by MalloZup** [comment]
@kkhamruddin-pk I'm using `openSUSE` Linux. On ubuntu I dunno personally. I might thing you need to upgrade the distro version, but take this as just a suggestion .
