### ISSUE TITLE
internal error: Cannot find suitable emulator for x86_64 and An error occurred, but the cause is unknown

### ISSUE THREAD

**Issue by Klaven** [dmacvicar/terraform-provider-libvirt#554]
### Linux distribution

``` openSUSE Tumbleweed ```

### Terraform version
v0.11.11
```sh
terraform -v
```

### Provider and libvirt versions

```sh
terraform-provider-libvirt -version
```
```
terraform-provider-libvirt f820017a88917e698d5d2eddf391ad8382f28920
Compiled against library: libvirt 5.0.0
Using library: libvirt 5.0.0
2019/02/20 14:15:44 virError(Code=1, Domain=10, Message='internal error: Cannot find suitable emulator for x86_64')
```

```
rpm -q qemu
qemu-3.1.0-3.3.x86_64
```

## Checklist

- [x] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [x] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [x] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [x] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

running `terraform-provider-libvirt -version` provides the following output

```terraform-provider-libvirt f820017a88917e698d5d2eddf391ad8382f28920
Compiled against library: libvirt 5.0.0
Using library: libvirt 5.0.0
2019/02/20 14:15:44 virError(Code=1, Domain=10, Message='internal error: Cannot find suitable emulator for x86_64')
```

### Setup

It also fails to run the scripts found here:

https://github.com/Klaven/automation/blob/master/caasp-kvm/cluster.tf.erb

with the error 
```Error: Error applying plan:

1 error(s) occurred:

* libvirt_domain.admin: 1 error(s) occurred:

* libvirt_domain.admin: virError(Code=1, Domain=0, Message='An error occurred, but the cause is unknown')
```

(Please provide the full _main.tf_ file for reproducing the issue (Be sure to remove sensitive information)

### Steps to Reproduce Issue

run `terraform-provider-libvirt -version` I think both errors are related.

Notes: originally `terraform-provider-libvirt -version` complained that it was compiled against library: libvirt 4.0.0 but using 5.0.0. I built it on my computer to update it to being compiled against 5.0.0. all the other errors stayed the same.

(Include debug logs if possible and relevant).

___
## Additional information:

This all worked yesterday and then I updated via zypper these packages and now they do not work. please let me know if you need anything else from me please let me know.

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by MalloZup** [comment]
@Klaven we builded 2 days ago pkgs https://build.opensuse.org/package/show/systemsmanagement:terraform:unstable/terraform-provider-libvirt .

you migh retry with `terraform-provider-libvirt -version` i think we solved 1 part of the issue, the 2nd part could be a libvirt problem related to 5.0 tubleweed and other ecosystems pkgs

**Comment by Klaven** [comment]
I have sadly moved off tumbleweed due to needing to get work done so I cannot test this.

**Comment by MalloZup** [comment]
@Klaven I'm closing this since I have tested on Tw recenlty was ok and is more on pkg side then here. thx for issue
