### ISSUE TITLE
macOS Build Failure

### ISSUE THREAD

**Issue by prologic** [dmacvicar/terraform-provider-libvirt#559]
Hi,

Trying to build this on macOS fails with the following build error:

```
~/Contributions/terraform-provider-libvirt
 (master) 0
$ make
go fmt ./libvirt .
go run golang.org/x/lint/golint -set_exit_status ./libvirt .
go vet ./libvirt
# github.com/dmacvicar/terraform-provider-libvirt/libvirt
libvirt/resource_libvirt_network.go:332:3: Printf format %s has arg network of wrong type *github.com/libvirt/libvirt-go.Network
libvirt/resource_libvirt_network.go:351:3: Printf format %s has arg network of wrong type *github.com/libvirt/libvirt-go.Network
libvirt/helpers_test.go:121:3: Printf format %s has arg virConn of wrong type *github.com/libvirt/libvirt-go.Connect
make: *** [vet-check] Error 2
```

You can verify this by following the same steps in the [README](/README.md)

Aside from that:

```#!bash
$ brew install libvirt
```

To get the libvirt C libraries.

Let me know if I can help any further; if I have time I'l try to put up a PR to fix this.

**Comment by MalloZup** [comment]
hi @prologic . thx for issue. Feel free to spend a PR for this if you have time ! :+1: thx.

**Comment by joakimfors** [comment]
This hack fixes the compile issues (at least for me): https://github.com/joakimfors/terraform-provider-libvirt/commit/9f614cf1d21f674592b9cde96b5a3d038074f20c

**Comment by 2stacks** [comment]
Same issue on Ubuntu 16.04.  Was able to compile after making these changes.

**Comment by prologic** [comment]
> This hack fixes the compile issues (at least for me): [joakimfors@9f614cf](https://github.com/joakimfors/terraform-provider-libvirt/commit/9f614cf1d21f674592b9cde96b5a3d038074f20c)

Can you put up a PR? :)

**Comment by MalloZup** [comment]
thix is merged! thx
