### ISSUE TITLE
Support storage pool resource

### ISSUE THREAD

**Issue by zeenix** [dmacvicar/terraform-provider-libvirt#562]
[Openshift 4.0 Installer](https://github.com/openshift/installer/) currently uses the `default` storage pool. If this pool doesn't exist, it can't do anything but error out. Since the `default` is not guaranteed by libvirt (it's a `virt-install` and `virt-manager` thing), it'd be useful for users like Openshift Installer to be able to be able to create the pool if it doens't exist already. I already have a WIP patch to add storage pool resource, which I'm hopefully going to finish up and submit soon in a PR.

Please note that while my use case is Openshift 4.0 Installer, this issue is not unique to that, as you can see from #446 and #75.

**Comment by MalloZup** [comment]
thx @zeenix  for bringing this up. we have actually another issue regarding this. Imho we can continue the follow up here: https://github.com/dmacvicar/terraform-provider-libvirt/issues/435

**Comment by MalloZup** [comment]
i'm closing this as duplicata. but any helps is welcome in this direction. thx! and cu on the other issue :rocket:
