### ISSUE TITLE
Ubuntu example file fail at cloud init

### ISSUE THREAD

**Issue by bbichero** [dmacvicar/terraform-provider-libvirt#566]
System Information
------
### Linux distribution
`Debian buster`

### Terraform version
`Terraform v0.11.13`

### Provider and libvirt versions

`terraform-provider-libvirt -version`
```
terraform-provider-libvirt 0.5.1
Compiled against library: libvirt 4.0.0
Using library: libvirt 5.0.0
Running hypervisor: QEMU 3.1.0
Running against daemon: 5.0.0
```

Description of Issue/Question
------
I just simply execute terraform command to test example file [ubuntu.tf](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/ubuntu/ubuntu-example.tf)
I executed : 
```
terraform init
terraform plan
terraform apply
```

Then I connect to VM virsh console:   
`virsh console ubuntu-terraform`

After 10 secondes and a lot of output I got:
```
[   12.542667] cloud-init[942]: 2019-03-18 14:58:44,847 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 3 column 12: "mapping values are not allowed here
[   12.547807] cloud-init[942]:   in "<unicode string>", line 3, column 12:
[   12.556249] cloud-init[942]:       ethernets:
[   12.558369] cloud-init[942]:                ^"
[   12.562659] cloud-init[942]: 2019-03-18 14:58:44,850 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloudNet'> failed
```
The error point to this file : 
https://github.com/dmacvicar/terraform-provider-libvirt/blob/ee4094d001fcc8eb49d5d28d1abebb30176c3db5/examples/ubuntu/network_config.cfg#L1-L5

### Steps to fix issue
I rewrite the file with this example : [Networking Config](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#network-config-v1)

I got now : 
```
network:
  version: 2
  config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp
```
And everything is working
Do I need to made a pull request with this file ?
Thanks

**Comment by MalloZup** [comment]
@bbichero  thank you. Yes, feel free to send a pr for fixing the example

**Comment by MalloZup** [comment]
bonne journee

**Comment by bbichero** [comment]
Ok thanks, before sending my pr I will check the others examples too.
Can you exaplain me the goal of the other example please ?
I don't see what `count`, `format` or `boot` does ...
The `boot` example doenns't seems to boot at all.

🇫🇷 Bonne journée :)

**Comment by MalloZup** [comment]
Each `example` was made in order to showcase some features. If you think that other example need fix/correction feel free to spend PR also for that.

`count` example e.g it showcase that you can use the variable count to create XX domain etc.. You need to read the example and the doc together .hth

**Comment by bbichero** [comment]
Sorry for that I didn't see the `website/docs` directory.
I can close this issue.
