### ISSUE TITLE
Conditional domain startup

### ISSUE THREAD

**Issue by asmorodskyi** [dmacvicar/terraform-provider-libvirt#576]
We trying to cover scenario where we need to start Windows domain controller and few hosts in network which it manages . Obviously hosts need to be started only after Windows DC is up and running . Is there any way to instruct terraform to start domains only after another domain started and some conditions are met ?

**Comment by MalloZup** [comment]
@asmorodskyi hi! look here:

https://learn.hashicorp.com/terraform/getting-started/dependencies.html

`depends_on`.

For such question please use the `gitter` chat since aren't related to libvirt specificity.

Thx! :sun_with_face:
