### ISSUE TITLE
Enhancement: Support for tags in libvirt_domain resources

### ISSUE THREAD

**Issue by lhw** [dmacvicar/terraform-provider-libvirt#583]
Some of the more popular providers offer the tags block in VM resources (e.g. AWS, Azure, vSphere). Quite a few tools make use of these to categorize the machines in internal databases etc.
I thought it would be a good feature to add. I think we could use the `libvirt.DomainMetadata` to add a metadata structure for tf-libvirt. Like

```terraform
resource "libvirt_domain" "example" {
  tags {
    Type = "master"
  }
}
```
```xml
<domain>
  <metadata>
    <terraform:instance xmlns="https://terraform.io">
      <terraform:tag key="Type">master</terraform:tag>
    </terraform:instance>
  </metadata>
</domain
```
Some additional ideas for metadata from [OpenStack Nova](https://specs.openstack.org/openstack/nova-specs/specs/juno/implemented/libvirt-driver-domain-metadata.html)

I wouldn't mind implementing this feature but wanted to request input first in case somebody is already working on something similar etc.

**Comment by MalloZup** [comment]
@lhw thx for this proposal. :+1:  

I think in the `kvm` context which use-case could we have for the metadata field? E.g which info whoul we store in a concrete use case

thx for you time

**Comment by lhw** [comment]
I don't know what you mean about a kvm context but one common use-case in the wild is to tag certain machines as "master" or "worker" in a kubernetes environment for easier export i.e. to an ansible inventory (That would be our use-case). Others use the tags for staging by tagging certain machines for different stages with different configurations. Again then used by other software using the terraform state.

Some advanced usage can also be seen by the [terraform-label project ](https://github.com/cloudposse/terraform-terraform-label)

**Comment by MalloZup** [comment]
thx for clarification! i will have a look. @dmacvicar  cc

**Comment by MalloZup** [comment]
@lhw i'm ok with this feature and to me you could come up with a PR for this.

To me you can start thinking and coming out with a valid proposal about the `schema` of the resource and we can integrate with it.

e.g the tag definitions. etc .

e.g how will look like it in golang ( https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_volume.go#L40)

**Comment by lhw** [comment]
The default implementation is pretty boring:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_instance.go#L309
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/tags.go#L22
I would suggest we do the same here for `libvirt_domain`. 

XML schema wise I would go with the one above. I'll probably do a PR the next few days when I get around to implementing it.

**Comment by lhw** [comment]
How do you prefer the use of xml templates in this codebase? Should I go the `text/template` route or with just simple string concatenation?

```go
var out bytes.Buffer
tags := d.Get("tags").(map[string]string)

// Like this
const defTagsXML = `
	<terraform:instance xmlns="https://github.com/dmacvicar/terraform-provider-libvirt/">
	{{ range $key, $value := . -}}
		<terraform:tag key="{{ $key }}">{{ $value }}</terraform:tag>
	{{ end -}}
	</terraform:instance>
`
templ := template.Must(template.New("tagsXML").Parse(defTagsXML))
templ.Execute(&out, tags)

// Or like this
out.WriteString("<terraform:instance xmlns=\"https://github.com/dmacvicar/terraform-provider-libvirt/\">")
for key, value := range tags {
	fmt.Fprintf(&out, "<terraform:tag key=\"%s\">%s</terraform:tag>", key, value)
}
out.WriteString("</terraform:instance>")
```

**Comment by MalloZup** [comment]
closing , due to the comment on pr.

**Comment by MalloZup** [comment]
thx for effort
