### ISSUE TITLE
Pool name in volume resource getting ignored

### ISSUE THREAD

**Issue by mahendrakariya** [dmacvicar/terraform-provider-libvirt#584]
### Linux distribution

``` Ubuntu 18.04 ```

### Terraform version

```sh
Terraform v0.11.13
+ provider.libvirt (unversioned)
+ provider.template v2.1.0
```

### Provider and libvirt versions

```sh
terraform-provider-libvirt 0.5.1
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Running hypervisor: QEMU 2.11.1
Running against daemon: 4.0.0
```

## Description of Issue/Question

This plugin is ignoring the pool name for volume and is always looking for `default` pool.

### Setup

```
module "mymodule" {
  source = "github.com/mahakamcloud/terraform-libvirt-vm-double.git"

  instance_name  = "myinstance"
  libvirt_host   = "x.x.x.x"
  source_path    = "ubuntu1804.qcow2"
  mac_address_1  = "xx:xx:xx:xx:xx:xx"
  mac_address_2  = "xx:xx:xx:xx:xx:xx"
  ip_address   = "x.x.1.1"
  network_name_1 = "net1"
  network_name_2 = "net1"
  pool_name      = "mypool"

  user_data = "${data.template_file.user_data.rendered}"
}
```

### Steps to Reproduce Issue

On running `terraform apply` for the above module, we are getting the following error.

```
Error: Error applying plan:

1 error(s) occurred:

* module.myinstance.libvirt_cloudinit_disk.vm_init: 1 error(s) occurred:

* libvirt_cloudinit_disk.vm_init: can't find storage pool 'default'
```

**Comment by MalloZup** [comment]
@mahendrakariya  hi thx for issue! 

are you referring to `cloudinit` disk or `volume` pool? 

we don't have any `pool_name` variable:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/cloudinit.html.markdown#argument-reference

can you post an example without modules and more explit? thx

**Comment by mahendrakariya** [comment]
I should have been more clear.

`pool_name` is a custom variable that [we are using](https://github.com/mahakamcloud/terraform-libvirt-vm-double/blob/master/main.tf).

We are using `libvirt_volume` as below.

```resource "libvirt_volume" "vm_volume" {
  name   = "${var.instance_name}"
  pool   = "${var.pool_name}"
  source = "${var.source_path}"
}

resource "libvirt_cloudinit_disk" "vm_init" {
  name = "${var.instance_name}-init.iso"

  user_data = "${var.user_data}"
}

resource "libvirt_domain" "vm_domain" {
  name      = "${var.instance_name}"
  memory    = "${var.memory_size}"
  vcpu      = "${var.num_cpu}"
  autostart = "${var.autostart}"

  cloudinit = "${libvirt_cloudinit_disk.vm_init.id}"

  ...

}
```

**Comment by MalloZup** [comment]
@mahendrakariya hi thx. for this. can you post the full-error log message?

because you refer to `volume` but the error concern `cloudinit`. thank you :rocket:

**Comment by zeenix** [comment]
@MalloZup i think we can close this one.
