### ISSUE TITLE
Enhancement: Support for network storage volumes

### ISSUE THREAD

**Issue by lhw** [dmacvicar/terraform-provider-libvirt#585]
One common use-case for libvirt_volumes would be using network devices. There is a whole list of different network storage options [available in libvirt](https://libvirt.org/formatdomain.html#elementsDisks).
One example of network devices as backing store for the VM disks would be Ceph RBDs or iSCSI. Which is as far as I can see right now not currently not natively supported. 

There currently is a way to do it with the included XSLT parameter for the volume which I assume was intended for this purpose but that is still a crude way to do it in the end. But I get it as due to the slew of different options available this is sadly not an easy one to implement.

**Comment by MalloZup** [comment]
thx . yes as you stated the `xslt` feature should cover the missing GAP between this provider and the libvirt API. ( https://github.com/dmacvicar/terraform-provider-libvirt#introduction--goals)

**Comment by lhw** [comment]
Doing xslt again after so many years was entertaining. I'll probably make an update to the existing xslt example. But for now here is an example with rbd. I'll look into how this could be implemented in the future. Still have other things to work on currently.

```terraform
data "template_file" "cephdisk" {
  template = "${file("${path.module}/templates/ceph_rbd.xml")}"
  vars {
    diskname = "${format(var.hostname_format, count.index)}.disk"
    ceph_user = "${var.libvirt_ceph_user}"
    ceph_uuid = "${var.libvirt_ceph_uuid}"
    ceph_pool = "${var.libvirt_ceph_pool}"
    ceph_mons = "${join("\n", formatlist("<host name='%s' port='6789' />", var.ceph_mons))}"
  }

  count = "${var.hosts}"
}

resource "libvirt_domain" "coreos-machine" {
  [...]
  xml {
    xslt = "${data.template_file.cephdisk.rendered}"
  }
}
```
```xml
<?xml version="1.0" ?>
<!-- templates/ceph_rbd.xml -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output omit-xml-declaration="yes" indent="yes"/>
  <xsl:template match="node()|@*">
     <xsl:copy>
       <xsl:apply-templates select="node()|@*"/>
     </xsl:copy>
  </xsl:template>

  <xsl:template match="/domain/devices/disk[source/@volume='${diskname}']">
    <disk type='network' device='disk'>
      <xsl:copy-of select="driver" />
      <auth username='${ceph_user}'>
        <secret type='ceph' uuid='${ceph_uuid}' />
      </auth>
      <source protocol='rbd' name="{concat('${ceph_pool}/', source/@volume)}">
        ${ceph_mons}
      </source>
      <xsl:copy-of select="target" />
      <xsl:copy-of select="address" />
    </disk>
  </xsl:template>
</xsl:stylesheet>
```

**Comment by lhw** [comment]
I would like to implement at least the libvirt_domain.disk.rbd in the near future to alleviate the requirement for XSLT in our use-case.
```hcl
resource "libvirt_domain" "test" {
  disk {
    volume_id = "${libvirt_volume.test.id}"
    rbd = {
      user = ""
      uuid = ""
      pool = ""
      mons = [
        ...
      ]
    }
  }
}
```

This should be fairly easy to implement but would still require the `clone` option for the libvirt_volume
