### ISSUE TITLE
Cannot unlink file '/var/lib/libvirt/images/XXXXX': Permission denied

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#6]
* Probably related to https://bugzilla.redhat.com/show_bug.cgi?id=1293804
* Need to be tested in different libvirt versions (eg. Leap)
* For now we use workaround https://bugzilla.redhat.com/show_bug.cgi?id=1293804#c12
  * Does not solve the problem but it makes it happen less often (eg. "sometimes")

**Comment by mauromorales** [comment]
Tested by applying a volume and then destroying it on leap and didn't gave me an error but I wonder if it is necessary to use the volume before being able to reproduce. Here is my libvirt version

```
 $ virsh --version
1.2.18.2
```

Also I remember having a similar issue when using pennyworth and making sure sure my libvirt.conf user and group matched with the `/var/lib/libvirt/qemu` owner.

**Comment by dmacvicar** [comment]
Seems to be fixed in libvirt 1.3.3 in Tumbleweed.
