### ISSUE TITLE
Release v0.5.2

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#603]
Tracking steps.

- [X] Edit release draft
- [X] Tag git
- [X] Run acceptance tests
- [X] Point OBS `_service` to v0.5.2 branch
- [X] Check all targets build
- [X] Download & sign binaries
- [X] Attach binaries & signatures to release draft
- [X] Publish release

(and this gives us a good overview of what we need to automate once we get acceptance tests running on Travis)

**Comment by dmacvicar** [comment]
CentOS 7 is not building in OBS (`nothing provides golang`). I recall this had fixed itself some time ago. Is it back?

**Comment by MalloZup** [comment]
:+1:

**Comment by dmacvicar** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.5.2

**Comment by MalloZup** [comment]
:tada: :clap:
