### ISSUE TITLE
Official Packaged Release 0.6.0 (Terraform 0.12)

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#605]
Tracking steps.

- [x] Update dependencies, doc for using tf 0.12
- [x] Do some manual test experimentation with PR  https://github.com/dmacvicar/terraform-provider-libvirt/pull/602
- [x] Run acceptance tests
- [x] merge once done: https://github.com/dmacvicar/terraform-provider-libvirt/pull/609
- [x] Edit release draft to reflect change when PR merged 
- [x] Tag git
- [x] Point OBS `_service` to v0.6.0 branch
- [ ] Check all targets build
- [ ] Download & sign binaries
- [ ] Attach binaries & signatures to release draft
- [ ] Publish release

**Comment by MalloZup** [comment]
@dmacvicar  I'm Proposing to use `0.6.0` since we upgrade to a Major release with breaking changes etc. Are you ok with that?

**Comment by MalloZup** [comment]
@dmacvicar I just noticed that `terraform init` from v.012 behave different from v.011.

In past I had the libvirt binary in `/usr/bin` and this worked.

Now having it on same dir, it expect to have it on the custom `$USER/.terraform.d/plugins/linux_amd64`


```
 terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "libvirt" not available for installation.

A provider named "libvirt" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
```

We might need to adapt the pkg to install it on that dir.

**Comment by MalloZup** [comment]
fix Chars breaking change in TF12 for Resource-Names: 
https://github.com/dmacvicar/terraform-provider-libvirt/pull/607

**Comment by MalloZup** [comment]
https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

**Comment by MalloZup** [comment]
the only missing step for this is adding the pkg fix to obs

**Comment by MalloZup** [comment]
https://build.opensuse.org/package/show/systemsmanagement:terraform:unstable/terraform-provider-libvirt

retriggering service file with latest changed ( new version)

**Comment by pothos** [comment]
Thanks for communicating the roadmap here. Do you think you can do a 5.3.0 release with the current changes that are compatible with Terraform 0.11, before 0.6.0 is released?

**Comment by MalloZup** [comment]
@pothos for using the TF11 provider the only way is to use this:

https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.5.2

The current master branch will not be backward compatible with `TF11` but this is also the `terraform` way of doing things, so the current master and next 6.0 will be only `TF12`

hope it helps!

If you use the `master` branch it could be backward compatible somehow but you will be on your own, since terraform 0.12 has several breaking changes in hcl and other components...

**Comment by MalloZup** [comment]
Done!

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.6.0
