### ISSUE TITLE
Network: adresses not assigned to VM

### ISSUE THREAD

**Issue by jdnieto** [dmacvicar/terraform-provider-libvirt#61]
When _**network_interface**_ is defined is supposed to be statically assigned an IP with _**addresses**_ key and a list of IPs.
```
network_interface {
    network_name = "ose"
    hostname ="node${count.index}.osc.test"
    mac = "52:54:00:00:00:a${count.index + 1}"
    addresses = ["192.168.100.10${count.index + 1}"]
```

When _**terraform apply**_ is launched the IP for the VM is retrieved via DHCP and is different from the one defined in _**addresses**_

**Comment by flavio** [comment]
Thanks again for the fix
