### ISSUE TITLE
Can you set bridge interface IP address?

### ISSUE THREAD

**Issue by ttruong7** [dmacvicar/terraform-provider-libvirt#612]
When using resource "libvirt_network", is there any way to set the interface IP address.

For example: 
```xml
<network>
  <name>MGMT</name>
  <uuid>e4d356fe-c63e-4fb7-a905-da11a22802e7</uuid>
  <forward mode='nat'/>
  <bridge name='MGMT' stp='on' delay='0'/>
  <mac address='52:54:00:ba:21:68'/>
  <ip family='ipv4' address='192.168.0.100' prefix='24'>
  </ip>
</network>
```
Here I set address 192.168.0.100. 

When I use terraform, it automatically uses 192.168.0.1.  Here's my main.tf:

```hcl
resource "libvirt_network" "mgmt_network" {
  name = "${var.network_name}"

  mode = "nat"
  addresses = ["192.168.0.100/24"]
  dhcp = {
    enabled = false
  }
  bridge = "${var.network_name}"
  autostart = true

  dns = {
    local_only = true
  }
}
```

I also tried 
```hcl
  addresses = ["192.168.0.100/32"]
  dhcp = {
    enabled = false
  }
```

but I get error  
`* libvirt_network.network: Could not set DHCP from adresses 'Netmask seems to be too strict: only -3 IPs available (ipv4)'`

**Comment by goraxe** [comment]
In this context addresses is used to calculate the start and end address of the dhcp range (even though you have turned dhcp off) . 

The first ip address will be reserved to be the gateway address (as well as the top address to be the broadcast address)

Code which does this calculation is here -> https://github.com/dmacvicar/terraform-provider-libvirt/blob/1a01934a7d2043d1775c568aed451249d96f036c/libvirt/network.go#L99

It also does not make a lot of sense to restrict the virtual network to a single ip address (the construct is a network expecting multiple IP addresses to be talking across it, if you had two VMs and your host connected to the virtual network, where would traffic for the IP address go?)

To answer the question 'no its not possible to allocate an ip address to a virtual network bridge'

**Comment by MalloZup** [comment]
@goraxe thx for answer . closing
