### ISSUE TITLE
Confusion on pulling specific Version

### ISSUE THREAD

**Issue by james-crowley** [dmacvicar/terraform-provider-libvirt#620]
### Linux distribution

``` Docker golang:alpine```

### Terraform version

```sh
N/A
```

### Provider and libvirt versions
```
Multiple Versions
```

### Setup

I am working on getting the docker examples, #617,  running but hitting some issues with GO. I am not an expert in GO and it might be a bug in my usage rather then a bug with the provider.

### Steps to Reproduce Issue

```
# Building Libvirt Plugin Docker
FROM golang:alpine

ARG VERSION
ENV VERSION=$VERSION

# Install Needed Packages
RUN apk update \
    && apk upgrade \
    && apk add --no-cache git make pkgconfig libvirt gcc libvirt-dev libc-dev

# Pull Down Needed Projects
RUN go get -u golang.org/x/lint/golint && env GO111MODULE=on go get github.com/dmacvicar/terraform-provider-libvirt@$VERSION

# Set Workdir for bin build
WORKDIR $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt

# Build
RUN make build
```

In this case version can be set to any release version you guys produced. In my testing I been trying to install `v0.5.2` as its the last version before terraform `0.12`. When setting the version to `v0.5.2`, the module seems not to download. Usually I can find the module in `/go/src/github.com/......`. But when I run with `v0.5.2` nothing seems to download. 

I passed in `env GO111MODULE=on` to support the versioning of `go get`. When I remove `env GO111MODULE=on` and the `@v0.5.2`. the module seems to install find, but master is built for `0.12` of terraform. I wanted to be able to select different versions of this provider. 

Maybe I am mixing things up with GO, if so please correct me. Like I stated I am fairly new to GO and the whole module setup. 

I am not sure if this would work, but could  I cd into the providers folder and do a get checkout `v0.5.2`? I am leaning towards no, since the modules this module relies on might be different versions between your releases.

**Comment by james-crowley** [comment]
So, I think I solved the issue. One way I got it to work was to do:

```
go get github.com/dmacvicar/terraform-provider-libvirt
cd $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt
git checkout $VERSION
```

But I think the above might have some issues with changes in dependencies between git  `version`. For example, If you do a `go get` then checkout `v0.5.2`, there is differences in the go dependencies. 

My suggestion would to change the README. Instead of telling people to do `go get github.com/dmacvicar/terraform-provider-libvirt`, change it to how the official Terraform provider plugins handle it.

For example, the [Random Provider](https://github.com/terraform-providers/terraform-provider-random). They uses these install instructions:

```
mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers
git clone git@github.com:terraform-providers/terraform-provider-random
```

Then do the following to grab the version you want and install dependencies:

```
git checkout $VERSION && env GO111MODULE=on go mod download
```

@MalloZup What do you think about this change? It is small but if people are building the plugin manually, they should know how to properly download the correct version.

**Comment by MalloZup** [comment]
@james-crowley  sorry was busy with other stuff.

we can't do like the `Random Provider` because the terraform-libvirt isn't part of the terraform-providers organisations, so it we can't instructs the user to download like that.


A part of the link,  we have currenlty following

``` 
go get github.com/dmacvicar/terraform-provider-libvirt
cd $GOPATH/src/github.com/dmacvicar/terraform-provider-libvirt
make install
```

However feel free to improve the readme. We already covered the 2 cases.

WIth golang  the dependencies are managed in git, so if you change branch it is normal that dependency change.

Also with the go modules, you can either run inside GOPATH with the flags or outsides GOPATH.

It is somehow tricky for newcomers

**Comment by MalloZup** [comment]
if you think that you can improve the Readme on the UX feel free to improve it ! tia

**Comment by MalloZup** [comment]
@james-crowley  I'm assigning yourself to this issue. Feel free to bring it forward ! :round_pushpin:
