### ISSUE TITLE
Add system z (s390x) support for coreos ignition 

### ISSUE THREAD

**Issue by jichenjc** [dmacvicar/terraform-provider-libvirt#624]
### Linux distribution
N/A

### Terraform version
N/A (master)

### Provider and libvirt versions
N/A

## Description of Issue/Question
currently the provider of libvirt is using fw_cfg anyway while from coreos perspective, which means in order to create and add ingition files , it uses fw_cfg unconditionally
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/domain.go#L240

however coreos it supports guestfish and fw_cfg
https://github.com/coreos/coreos-assembler/blob/master/src/cmd-run#L240

so the proposal here is  to have a new method to pass ignition to coreos by 
referring to following implementation
https://github.com/coreos/coreos-assembler/blob/master/src/libguestfish.sh
which means, you can either select fw_cfg or files based on different arch (power and s390x)
### Setup

(Please provide the full _main.tf_ file for reproducing the issue (Be sure to remove sensitive information)

### Steps to Reproduce Issue

(Include debug logs if possible and relevant).

___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

No

**Comment by jichenjc** [comment]
@bjhuangr FYI

**Comment by MalloZup** [comment]
@jichenjc  hi thx! can you create a better description and removing/adapting the template? thx

**Comment by jichenjc** [comment]
@MalloZup ,thanks, I updated with some info I think helpful just now, let me know you need further info ,thanks
