### ISSUE TITLE
flatcar linux: fw_cfg has been updated

### ISSUE THREAD

**Issue by tormath1** [dmacvicar/terraform-provider-libvirt#626]
### Linux distribution

```
arch linux
```

### Terraform version

```sh
$ terraform -v
Terraform v0.12.6
```

### Provider and libvirt versions

```sh
$ terraform-provider-libvirt -version
5c01d18431ea2b9df4870990be6a1736ec6f322a
Compiled against library: libvirt 5.5.0
Using library: libvirt 5.5.0
Running hypervisor: QEMU 4.0.0
Running against daemon: 5.5.0
```
___
## Description of Issue/Question

Hi ! I am using this plugin in order to deploy flatcar linux cluster on libvirt. FYI flatcar linux is a fork of coreOS container linux (https://www.flatcar-linux.org/).

Back in the days, the ignition config file was given to the domain through fw_cfg, but the key value has changed from `opt/com.coreos/config` to `opt/com.flatcar-linux/config`. (https://github.com/flatcar-linux/ignition/issues/2)

It could be nice to specify the value of the key in terraform config file ? 
https://github.com/dmacvicar/terraform-provider-libvirt/blob/5c01d18431ea2b9df4870990be6a1736ec6f322a/libvirt/domain.go#L240-L249

**Comment by MalloZup** [comment]
@tormath1  thx. I think it should be not really difficult to convert it to a variable. thx for issue

**Comment by tormath1** [comment]
Ok, I am on it. :rocket:

**Comment by MalloZup** [comment]
@tormath1 considering this closed by your pr. Feel free to squash commits
