### ISSUE TITLE
Request for xslt documentation

### ISSUE THREAD

**Issue by fritchie** [dmacvicar/terraform-provider-libvirt#628]
If documentation could be provided for changing the disk cache method to none via xslt it would be appreciated.

Relevant issues:

https://github.com/dmacvicar/terraform-provider-libvirt/issues/485

This would in addition to:

https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/v0.12/xslt

**Comment by MalloZup** [comment]
**NOTE** you need to adapt this

`disk_caching.xsl`

```
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output omit-xml-declaration="yes" indent="yes"/>

  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="disk[@type='volume']/driver">
    <xsl:copy>
      <xsl:attribute name="cache">unsafe</xsl:attribute>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>

```


```
resource "libvirt_domain" "foo" {
  name      = "foo"
  memory    = "${var.admin_memory}"
  vcpu      = "${var.admin_vcpu}"
  metadata  = "admin.${var.domain_name},admin,${count.index}"
  cloudinit = "${libvirt_cloudinit_disk.foo.id}"


  # used to add disk -> cache="unsafe"
  xml {
    xslt = "${file("disk_caching.xsl")}"
  }
```

**Comment by MalloZup** [comment]
@fritchie  If you want to adapt and create an example, with this I would not be against.

Otherwise feel free to close the issue thx, after it works. The doc i posted you should work, with some adaption but it show you the :walking_man: way

**Comment by fritchie** [comment]
that works for me, thanks much
