### ISSUE TITLE
Include provisioner remote-exec

### ISSUE THREAD

**Issue by jdnieto** [dmacvicar/terraform-provider-libvirt#63]
There will bee a good option to enhance next version with terraform provisioner remote-exec.
I think will be easy than configure multiple options in libvirt_cloudinit resource.

**Comment by toddnni** [comment]
You can use `remote_exec { }` block inside any resource, but if provider doesn't provide IP you need assign it in `connection { }` block. I have done it with my custom provider. Sorry, I don't know this provider well enough yet, but though that this might be helpful.

**Comment by flavio** [comment]
`remote-exec` is already working with this provisioner. I'm closing this issue, please re-open if I didn't get what you mean.
