### ISSUE TITLE
Error: Failed to instantiate provider "libvirt" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by omerkarabacak** [dmacvicar/terraform-provider-libvirt#633]
### Linux distribution

``` Ubuntu 18.04 ```

### Terraform version

```
Terraform v0.12.7
```

### Provider and libvirt versions

```0.4.4 and 0.5.2
```

If that gives you "was not built correctly", get the Git commit hash from your local provider repository:

```sh
git describe --always --abbrev=40 --dirty
```
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [ ] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

### Setup

(Please provide the full _main.tf_ file for reproducing the issue (Be sure to remove sensitive information)

### Steps to Reproduce Issue

(Include debug logs if possible and relevant).

___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by MalloZup** [comment]
hi @omerkarabacak. Can you please fill the template in more usefull manner? thx

Just looking at you error it seems to me that you have an outdate `libvirt-provider` that doesn't support  a Terraform v12 version. You should update it. 
but is just a guess in the dark, there is not much info in this issue. Marking this is issue as invalid. thx for providing any useful info.

**Comment by windyboy** [comment]
I build binary from master, it works !
