### ISSUE TITLE
Cloudinit requires local_hostname field

### ISSUE THREAD

**Issue by tboerger** [dmacvicar/terraform-provider-libvirt#64]
but the docs are mentioning it as optional.

```
* libvirt_cloudinit.test_ci: "local_hostname": required field is not set
```

**Comment by laycat** [comment]
This is a bit of a frustration: I'm using a common cloud-init resource to set the ssh key across domains. As a workaround for now, I've commented out the hostname declarations for cloud-init and rebuilt.

I've not explored this plugin too much so I can't assess the impact of removing the require for now, but I might get my hands dirty and do this "soon"

**Comment by tboerger** [comment]
I don't think that it got any downsides to make the hostname optional as stated in the docs. But maybe @flavio knows more about it since he has written the cloud-init integration?

**Comment by flavio** [comment]
I don't actually remember why I didn't make the hostname optional. I cannot see any downside in allowing that.

BTW, it would also be nice to revisit how the cloudinit resource is defined. It would be probably easier/more flexible to implement something like https://www.terraform.io/docs/providers/template/d/cloudinit_config.html
