### ISSUE TITLE
cant download centos7 plugins

### ISSUE THREAD

**Issue by wgkevin666** [dmacvicar/terraform-provider-libvirt#641]
##  System Information

i cant download this url
wget https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.5.2/terraform-provider-libvirt-0.5.2.CentOS_7.x86_64.tar.gz

### Linux distribution

``` Centos7```

### Terraform version

```sh
terraform -v
```
v0.12.8
### Provider and libvirt versions

```sh
terraform-provider-libvirt -version
```

If that gives you "was not built correctly", get the Git commit hash from your local provider repository:

```sh
git describe --always --abbrev=40 --dirty
```
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [ ] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

### Setup

(Please provide the full _main.tf_ file for reproducing the issue (Be sure to remove sensitive information)

### Steps to Reproduce Issue

(Include debug logs if possible and relevant).

___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by cavejay** [comment]
I've noticed that there are no longer pre-built binaries for Centos 7/8. Is there a known problem with the generation of the Centos binaries or are no no longer generated due to lack of interest?

**Comment by MalloZup** [comment]
hi @cavejay  normally we have provided this by https://build.opensuse.org/package/show/systemsmanagement:terraform/terraform-provider-libvirt but there is some work to be done for the centos7

**Comment by TinajaLabs** [comment]
Any thoughts on a centos 7 build?  Thanks.

**Comment by wgkevin666** [comment]
i acyually find how to sloved:
$ yum install unzip git libvirt-devel
$ mkdir -p $GOPATH/src/github.com/dmacvicar; cd $GOPATH/src/github.com/dmacvicar
$ go get github.com/dmacvicar/terraform-provider-libvirt
$ go install github.com/dmacvicar/terraform-provider-libvirt
$ cp $GOPATH/bin/terraform-provider-libvirt ~/.terraform.d/plugins

**Comment by TinajaLabs** [comment]
Kevin,
I note you seem to be using centos as your dev platform (using yum install).

I use macos to deploy all my instances into AWS, VMWare, Openstack, etc.  I thought I would need a centos7 plugin so I could *deploy* into centos7.  Can you set me straight on this, please?

Thanks,
Chris.

**Comment by cavejay** [comment]
Hi Chris,

The OS in the plugin name is the OS the plugin is compiled to be run from.
So in your case with macos you would be looking to run a
Terraform-provider-libvirt compiled for macos (Darwin?)

Does this help?

**Comment by TinajaLabs** [comment]
Yes.  It helps.  Thank you for your time.
