### ISSUE TITLE
RFE: Support dnsmasq options

### ISSUE THREAD

**Issue by zeenix** [dmacvicar/terraform-provider-libvirt#642]
Libvirt 5.6 added support for [passing verbatim options](https://libvirt.org/formatnetwork.html#elementsNamespaces) to `dnsmasq`. In Openshift, we'd likely want to use that to create generic DNS records with wildcards. I'm sure there are other uses of this and this is why this new feature was added. I haven't yet figured how this support would/could look like so please share ideas on how you think it should be done.

**Comment by zeenix** [comment]
Perhaps something very simple as:

```
resource "libvirt_network" "net" {
...
  dnsmaq_option = {
     option_name1 = option_value1
     option_name2 = option_value2
  }
}
```

**Comment by zeenix** [comment]
> Remember that we have also the `xlst` feature which let already implement without coding any libvirt functionality.

Right. I didn't think of that. Thanks! :) I'll close this now since if we can avoid adding support for workaround-API like this, that would be great. I'll try with XSLT and re-open if that doesn't work for some reason.

Thanks @MalloZup and @jaypoulz for suggestions.

**Comment by jichenjc** [comment]
@zeenix just for learning reason , so we will try to include the xml file per 
https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/v0.12/xslt given so that we can inject dnsmasq configuration through the xml definition? Thanks

**Comment by zeenix** [comment]
@jichenjc Yes. :)

**Comment by jichenjc** [comment]
@zeenix do you have any info about this effort? Some PR or some issues in other Repo? I want to catch up with this .. thanks

**Comment by zeenix** [comment]
> @zeenix do you have any info about this effort? Some PR or some issues in other Repo? I want to catch up with this .. thanks

If you mean the fix for https://github.com/openshift/installer/issues/1007, then no. I've only been trying out things by manually editting/hardcoding the XML for now. Also let's not discuss Openshift specific issues here. :)

**Comment by jichenjc** [comment]
sure :) thanks for the reminder ~
