### ISSUE TITLE
Error: Error defining libvirt domain: virError(Code=27, Domain=20, Message='XML error: file '/dev/urandom' is not a supported random source')

### ISSUE THREAD

**Issue by kkhamruddin-pk** [dmacvicar/terraform-provider-libvirt#645]
libvirt_volume.ubuntu-qcow2: Still creating... [7m10s elapsed]
libvirt_cloudinit_disk.commoninit: Still creating... [7m10s elapsed]
libvirt_volume.ubuntu-qcow2: Still creating... [7m20s elapsed]
libvirt_cloudinit_disk.commoninit: Still creating... [7m20s elapsed]
libvirt_volume.ubuntu-qcow2: Creation complete after 7m25s [id=/var/lib/libvirt/images/ubuntu-qcow2]
libvirt_cloudinit_disk.commoninit: Creation complete after 7m25s [id=/var/lib/libvirt/images/commoninit.iso;5d836e40-3be2-8ffd-905f-eaacd8da519a]
libvirt_domain.domain-ubuntu: Creating...

Error: Error defining libvirt domain: virError(Code=27, Domain=20, Message='XML error: file '/dev/urandom' is not a supported random source')

  on libvirt.tf line 41, in resource "libvirt_domain" "domain-ubuntu":
  41: resource "libvirt_domain" "domain-ubuntu" {

**Comment by kkhamruddin-pk** [comment]
AM USING libvirt 1.3.1 version. How to fix this issue? any idea?

**Comment by MalloZup** [comment]
@kkhamruddin-pk seems to me a pretty old system.
Can you update you system  and especially libvirt?

**Comment by MalloZup** [comment]
@kkhamruddin-pk this is issue is duplicata with https://github.com/dmacvicar/terraform-provider-libvirt/issues/551

**Comment by MalloZup** [comment]
closing as duplicata. @kkhamruddin-pk feel free to write here or on the channel if you need help thx!
