### ISSUE TITLE
Root permissions file under default storage pool

### ISSUE THREAD

**Issue by tmpm697** [dmacvicar/terraform-provider-libvirt#647]
### Linux distribution

``` archlinux.. ```

### Terraform version

```
v12
```

### Provider and libvirt versions

```
latest
```

___

I'm trying to provision `kvm` via `libvirt` using this plugin under normal user (I don't want to use root).

I have my normal user in group of `/etc/group`: `wheel`, `libvirt` (user in wheel can sudo without password)

I created default storage pool using this comment: https://github.com/simon3z/virt-deploy/issues/8#issuecomment-73111541

I `sudo chmod 644 /var/libvirt/images` and `sudo chown -R myuser:myuser /var/lib/libvirt/images`

Problem is that when I use example `https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/v0.12/ubuntu`.
`terraform init` and `terraform apply` to provison the vm, it create file under /var/lib/libvirt/images with `root:root` owner and give `permission errror`, then I have to re-do `sudo chown -R myuser:myuser /var/lib/libvirt/images` and re-run `terraform apply` to make it work.

How to avoid this kind of issue?

**Comment by MalloZup** [comment]
@tmpm697 you need to setup your user correctly, belonging to `kvm/libvirt` user. Search on the web should be enough doc on this issue.. You don't need root. Hope it helps

**Comment by tmpm697** [comment]
@MalloZup : As I mentioned in #1 post, `myser` already in `libvirt` and I've just added it in `kvm` group too, nothing has changed. If you have corrected them, please share your configs.

**Comment by MalloZup** [comment]
@tmpm697 https://wiki.archlinux.org/index.php/Libvirt#Configuration. I don't have time to post my configuration. It is really the standard one. Please ask help on the question on the channel. Consider that this issue isn't not a terraform-provider-libvirt issue but on the libvirt itself. So you might just ask in any arch Linux forum or libvirt channels. I'm closing this as invalid

**Comment by MalloZup** [comment]
https://gitter.im/terraform-provider-libvirt/Lobby

**Comment by MalloZup** [comment]
This is our channel feel free to ask there otherwise other medium can help 🐧
