### ISSUE TITLE
Second VM always fails to start, but starts if tried manually using `virsh`

### ISSUE THREAD

**Issue by dguitarbite** [dmacvicar/terraform-provider-libvirt#65]
If I am provisioning multiple VM's, the first one boots as expected but the second VM throws an error by default:
```
Error applying plan:

2 error(s) occurred:

* libvirt_domain.saltminion: Error creating libvirt domain: [Code-1] [Domain-10] internal error: qemu unexpectedly closed the monitor: ((null):25956): Spice-Warning **: reds.c:2484:reds_init_socket: reds_init_socket: binding socket to 127.0.0.1:5900 failed
2016-09-11T09:49:37.443038Z qemu-system-x86_64: failed to initialize spice server
* libvirt_domain.saltmaster.1: Error creating libvirt domain: [Code-1] [Domain-10] internal error: process exited while connecting to monitor: ((null):25954): Spice-Warning **: reds.c:2484:reds_init_socket: reds_init_socket: binding socket to 127.0.0.1:5900 failed
2016-09-11T09:49:37.447608Z qemu-system-x86_64: failed to initialize spice server

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I tried manually starting the VM's using virsh and it gracefully boots. I swapped the order and confirmed that it is the second VM. I tried multiple copies of the same VM and the same error again.

libvirt.tf:
```
provider "libvirt" {
    uri = "qemu:///system"
}

resource "libvirt_volume" "opensuse_leap" {

    name = "opensuse_leap"
    source = "http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.1/images/openSUSE-Leap-42.1-OpenStack.x86_64.qcow2"

}

resource "libvirt_volume" "mastervolume" {

    name = "saltmaster-${count.index}"
    base_volume_id = "${libvirt_volume.opensuse_leap.id}"
    count = 1
}

resource "libvirt_volume" "minionvolume" {

    name = "saltminion-${count.index}"
    base_volume_id = "${libvirt_volume.opensuse_leap.id}"
    count = 1
}

resource "libvirt_domain" "saltmaster" {

    name = "saltmaster-${count.index}"
    disk {
        volume_id = "${element(libvirt_volume.mastervolume.*.id, count.index)}"
    }
    count = 1
}

resource "libvirt_domain" "saltminion" {

    name = "saltminion-${count.index}"
    disk {
        volume_id = "${element(libvirt_volume.minionvolume.*.id, count.index)}"
    }
    count = 1
}
```

It could potentially be the issue where this plugin is trying to register the new VM with the same `VNC` endpoint `localhost:5900` which IMHO is unlikely. AFAIK, libvirt should handle this part of the configuration of the given VM.

I am using `Arch Linux` updated to latest versions and there is no problem with other deployment frameworks that I am using to drive VM's in libvirt/KVM. I am quite sure that this issue is not arising from my choice of the distro and environment.

**Comment by dguitarbite** [comment]
It seems to be running as expected on openSUSE-Leap. I am out of distros at present. I am not sure if it is the way I configured Arch, other deployment frameworks that I use seem to run fine though.

**Comment by laycat** [comment]
FWIW I can't reproduce this: terraform successfully creates the domains and both run successfully. @dguitarbite did you resolve your issue, or is it persisting for you?

**Comment by dguitarbite** [comment]
It is pending but only for archlinux. I tried tuning libvirt but it does
not help (allowing more parallel requests to libvirt etc.). Although it
works fine on openSUSE. I will try debugging this issue one more time and
close the issue here. May be we could make a note somewhere for the same.

**Comment by dguitarbite** [comment]
@laycat I think there is something missing from this provider. What I can conclude from monitoring the process after `$ terraform apply` command is that the libvirt domain creation tries to create the domain with same spice endpoint ``<ip_addr>:<port>``. This causes a conflict in case of existing domain with same endpoint, libvirt returns an error which is most probably not being handled properly. Terraform dumps the error and then gives up trying to re-try creation of the domain. Since, I can easily invoke the virsh command to start the same domain which failed to start from Terrraform, I have to conclude that either the XML creation is assuming/hardcoding something or the error handling could be used as a clue to re-try after a short waiting duration. Although this issue is only reproducible on my WS running arch linux, I have tried fine tuning libvirtd.conf and qemu.conf and it does not seem to make any difference. Assuming (flawed logic deviating from facts) that my configuration of libvirt is good enough (arch linux means manual configuration) for other orchestration solutions, I may be missing some dependency which is not a strict requirement for libvirt/kvm/qemu or using some alternative dependency which is not commonly used as defaults by standard distributions, I still can conclude (although not 100% factual, still quite relevant IMHO) that the conflict primarily arises out of this provider or terraform rather than from my side.

Additionally, what I observed that the ``terraform.tfstate`` does not make entries for failed requests which is deviating from the truth. It would be nicer to have the entries with error output defaults rather than nothing. From my observations, this makes it impossible to manually fix what is broken for the time being and then hook it back into Terraform. I am considering tweaking this file manually for the same but something tells me that it would be frustratingly time consuming provided that it works.

Since I cannot proceed ahead with facts, for the time being I am considering working around these issues manually and remembering them for my next arch install to see if I can reproduce the same again. Till then closing this issue.

**Comment by laycat** [comment]
Thanks for the update @dguitarbite, and apologies, my previous comment was anything but clear: that test was on Fedora 23 (with the idea of trying to isolate this to Arch).

I've since recreated this in an Arch environment: I'm convinced this is a valid bug but I'm not sure where it belongs (yet). Some analysis:

Currently the domain definition contains a set entry for spice: https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/domain_def.go#L88

This results in XML being generated with the device entry:
````
<graphics type="spice" autoport="yes"></graphics>
````

I've taken the generated xml in each case and successfully used virsh create, so my thoughts are it's a subtle difference introduced in how the spice port allocation is handled during the machine definition.

Looking at the flow, this plugin uses the libvirt-go layer to call virDomainDefineXML then virDomainCreate (with the error being reported by the virDomainCreate call).

I think that's enough to say this bug exists, but shouldn't be in this plugin. I'm sufficiently interested: I may dig into this further and try and find the root cause.

As a workaround/test I've tried removing the spice definition from the domain definition (here: https://github.com/laycat/terraform-provider-libvirt/commit/9e3b817c624fdf199ee4f72be3ae2b886ab70e51) and successfully recreated the given environment. Feel free to use and build from there.

Separate but related and valid: should spice be hardcoded? Should this be split out into an optional parameter for the domain resource?

Seperate and very much less related (but you brought it up!) I whole-heartedly agree with the frustrations of Terraform not storing error state. I've thought of this before and I came to the conclusion if you fix something manually, Terraform naturally shouldn't care. It only cares about what it controls: if it fails you should clean up, fix it and try again. It would be wonderful if Terraform could do that cleaning for you, but it doesn't know how to fix something it can't successfully define I suppose.

**Comment by dguitarbite** [comment]
> Thanks for the update @dguitarbite <https://github.com/dguitarbite>, and
> apologies, my previous comment was anything but clear: that test was on
> Fedora 23 (with the idea of trying to isolate this to Arch).
>
No worries, thanks for the updates.

> I've since recreated this in an Arch environment: I'm convinced this is a
> valid bug but I'm not sure where it belongs (yet). Some analysis:
>
> Currently the domain definition contains a set entry for spice:
> https://github.com/dmacvicar/terraform-provider-libvirt/blob
> /master/libvirt/domain_def.go#L88
>
> This results in XML being generated with the device entry:
>
> <graphics type="spice" autoport="yes"></graphics>
>
> I've taken the generated xml in each case and successfully used virsh
> create, so my thoughts are it's a subtle difference introduced in how the
> spice port allocation is handled during the machine definition.
>
I agree. I can confirm that this issue is not due to libvirt or qemu.

> Looking at the flow, this plugin uses the libvirt-go layer to call
> virDomainDefineXML then virDomainCreate (with the error being reported by
> the virDomainCreate call).
>
Yes, although I was wondering if we could save the state at this point with
the domain state as shutoff or running:false. Then trying to launch the
domain(s). Another idea is to add parallel option where it tries domain
creation in parallel or in a sequence.

> I think that's enough to say this bug exists, but shouldn't be in this
> plugin. I'm sufficiently interested: I may dig into this further and try
> and find the root cause.
>
> As a workaround/test I've tried removing the spice definition from the
> domain definition (here: laycat@9e3b817
> <https://github.com/laycat/terraform-provider-libvirt/commit/9e3b817c624fdf199ee4f72be3ae2b886ab70e51>)
> and successfully recreated the given environment. Feel free to use and
> build from there.
>

Thanks I will use this build.


> Separate but related and valid: should spice be hardcoded? Should this be
> split out into an optional parameter for the domain resource?
>

I think spice could be an optional parameter for the domain resource.
Additionally I have strong belief that libvirt should automatically setup
spice xml entries (not 100% sure at present). Since libvirt tolerates
minimal XML for domain definition and adds the rest on top by itself.

> Seperate and very much less related (but you brought it up!) I
> whole-heartedly agree with the frustrations of Terraform not storing error
> state. I've thought of this before and I came to the conclusion if you fix
> something manually, Terraform naturally shouldn't care. It only cares about
> what it controls: if it fails you should clean up, fix it and try again. It
> would be wonderful if Terraform could do that cleaning for you, but it
> doesn't know how to fix something it can't successfully define I suppose.
>

I do agree with this, it is quite frustrating. But I can at the same time
(I hate myself) understand why terraform does not provide this feature (at
least yet) while trying to be a generic deployment tool. I should not have
brought this up here though.

Thanks for going through the trouble to reproduce this on arch!

**Comment by mssola** [comment]
For reference, I'm using openSUSE Tumbleweed and I encountered this same issue. The "solution" was downgrading libvirt from 2.2 to 1.2.18 (the version I had installed before upgrading to 2.2). In openSUSE Leap, the version is still 1.2.18, so there shouldn't be any issues there.
