### ISSUE TITLE
mkisofs not available in debian

### ISSUE THREAD

**Issue by bigon** [dmacvicar/terraform-provider-libvirt#663]
Hello,

cloudinit requires `mkisofs` but it is not available in debian anymore

It seems that `genisoimage` is replacing it and looks like the parameters are compatible

**Comment by MalloZup** [comment]
@bigon  thx for issue. ! we might need some help and research on this how we can consolidate this among all the distros (opensuse/centos/debian/arch) on provider. If you want to drive this, feel free to ping me in any ways , I will glad to help .  (here or in the chat)

It is not an easy topic. We could even consider to have a special switch for debian in case of implementaition, but I would like to have a research on our friends linux distro (gentoo/opensuse/arch/debian/centos etc) to make all distro same and not only beeing debian or X driven.

**Comment by bigon** [comment]
FTR https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=680949

**Comment by MalloZup** [comment]
closing in favor of old one. @bigon https://github.com/dmacvicar/terraform-provider-libvirt/issues/465#event-2796911277

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/issues/465
