### ISSUE TITLE
Injecting iptables rule after libvirt network is created with terraform 0.11

### ISSUE THREAD

**Issue by pablochacin** [dmacvicar/terraform-provider-libvirt#664]
### Linux distribution

``` openSUSE Leap 15. ```

### Terraform version

v0.11.14

### Provider and libvirt versions

Compiled against library: libvirt 5.1.0
Using library: libvirt 5.7.0
Running hypervisor: QEMU 4.0.0
Running against daemon: 5.7.0

## Description of Issue/Question

I have the following scenario: I'm using terraform for creating multiple VMs with libvirt. VMs are attached to a NAT virtual network. As part of the VMs creation, some commands are executed on each VM by means of ssh. This works perfectly fine if VMs are created on the same machine where terraform runs.

I want also to be able to run terraform in my desktop and get the VMs created in another machine with more resources. I did this changing qemu's uri to point to the remote server. The VM creation works fine but when terraform tries to ssh into the VM from my machine, it fails because by default libvirt doesn't expose VMs to external access.

Therefore, I created an additional resource to run a command in the remote machine adding the rule `sudo iptables -I FORWARD 1 -d 10.17.0.0/22 -p tcp --dport 22 -j ACCEPT`  to the iptables after the virtual network is created and before the VMs are accessed. I control the ordering by explicitly setting the dependencies. 

This kind of works because the rule is added, BUT what I'm seeing is that the rule is consistently added AFTER the rules added by libvirt, as shown below:

```
1    ACCEPT     all  --  0.0.0.0/0            10.17.0.0/22         ctstate RELATED,ESTABLISHED
2    ACCEPT     all  --  10.17.0.0/22         0.0.0.0/0           
3    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
4    REJECT     all  --  0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
5    REJECT     all  --  0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
6    ACCEPT     tcp  --  0.0.0.0/0            10.17.0.0/22         tcp dpt:22
```

What I don't understand is why the iptables rule is created after the rules injected by libvirt if the iptables command is executed after the network is created and before the ssh to the Vms is executed (I have checked this in the terraform output).

### Setup
Use the code below as a reference. Please notice it is edited and incomplete. Only relevant parts are shown.

```
resource "libvirt_network" "network" {
  name   = "${var.stack_name}-network"
  mode   = "${var.network_mode}"  
  domain = "${var.dns_domain}"    

  dns = {
    enabled = true
  }

  addresses = ["${var.network_cidr}"] 
}

resource "null_resource" "iptables" {
  depends_on = ["libvirt_network.network"]

  connection {
    host     = <remote server>
    password = "******"
    user     = <ssh user>
    type     = "ssh"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo iptables -I FORWARD 1 -d ${var.network_cidr} -p tcp --dport 22 -j ACCEPT",
    ]
  }
}

resource "libvirt_domain" "vm" {

  depends_on = ["null_resource.iptables"]
  count = "${vars.vms}" 
   ... 
}

resource "null_resource" "config" {
  depends_on = ["libvirt_domain.vm"]

  connection {
    host = "${element(libvirt_domain.vm.*.network_interface.0.addresses.0, count.index)}"
    ...
  }
  
  provisioner "remote-exec" {   <-- this is the remote exec on vm    
   
  }
}

```

**Comment by FFY00** [comment]
This can be done with qemu.

You can pass the arguments to libvirt:
```
<qemu:commandline>
  <qemu:arg value='-net'/>
  <qemu:arg value='user,hostfwd=tcp::22222-:22,hostfwd=tcp::8000-:80'/>
</qemu:commandline>
```

@MalloZup would be possible to implement this?

**Comment by pablochacin** [comment]
@FFY00 It seems that libvirt [already supports this without using qemu command line arguments](https://wiki.libvirt.org/page/QEMUSwitchToLibvirt#-net).

With respect to what you suggest, if I understand it correctly, [this allows only port forwarding](https://wiki.qemu.org/Documentation/Networking#Advanced_user_networking_options). I need to route connections to multiple VMs. Not sure how to accomplish this.

**Comment by pablochacin** [comment]
This happens to be a problem with libvirt.
