### ISSUE TITLE
Unable to pass disk map to disk in resource domain 

### ISSUE THREAD

**Issue by jslinuxta** [dmacvicar/terraform-provider-libvirt#665]
##  System Information
Centos 7.7
### Linux distribution
Centos 7.7
``` openSUSE 42.2/ Centos7/ Ubuntu.. ```

### Terraform version
Terraform v0.12.14
```sh
terraform -v
```

### Provider and libvirt versions
terraform-provider-libvirt 0.6.0+git.1569597268.1c8597df
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.5.0
Running hypervisor: QEMU 2.12.0
Running against daemon: 4.5.0

```sh
terraform-provider-libvirt -version
```

If that gives you "was not built correctly", get the Git commit hash from your local provider repository:

```sh
git describe --always --abbrev=40 --dirty
```
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

  - [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

Per terraform-provider-libvirt , should be able to pass a list of disks as parameter, but it is not working. 

### Setup

(Please provide the full _main.tf_ file for reproducing the issue (Be sure to remove sensitive information)
```hcl
variable "servercount" {
  type = number
  default = 1
  }
variable "ddsize" {
   type =  number
  default = 21474836480
}
variable "cpu" {
  type =  number
   default = 2
}
variable "mem" {
  type =  number
   default = 2048
}
variable "servname" {
   type =  string
   default = "server"
}
variable "disks" {
   type =  number
   default = 2
}

locals {
  servers = {
    for s in range(var.servercount) : "${var.servname}-${s}" => {
        dd  = var.disks
        ddsize = var.ddsize
        cpu = var.cpu
        mem  = var.mem
        name = "${var.servname}-${s}"
        osdisk = "${var.servname}-${s}-os.qcow2"
        pname = var.servname
        diskmap = [ for n in range(var.disks):  { 
        volume_id = "${libvirt_volume.serverdata["${var.servname}-${s}-${n}"].id}"} ]
        index = s

        }

  }
   disks = flatten([
    for s in range(var.servercount) : [
        for c in range(var.disks) : "${var.servname}-${s}-${c}"

        ]
    ])
}

provider "libvirt" {
  uri = "qemu:///system"
  }

resource "libvirt_volume" "server-os" {
  for_each = local.servers
  name = lookup(each.value, "osdisk", "*")
  pool = "data2"
  source = "/data2/images/centos7hostb.qcow2"
  format = "qcow2"
}

resource "libvirt_volume" "server-data" {
  for_each = toset(local.disks)
  name = "${each.key}-data.qcow2"
  pool = "data2"
  size =  var.ddsize
  format = "qcow2"
}
resource "libvirt_domain" "server-vm" {
for_each = local.servers

  name   = each.key
  memory = each.value["mem"]
  vcpu   = each.value["cpu"]
  network_interface {
  bridge = "br0"
}

disk {
  volume_id = "/data2/images/${lookup(each.value, "osdisk", "${each.key}-osdisk.qcow2")}"
}
disk = [ each.value["diskmap"] ]

console {
type = "pty"
target_type = "serial"
target_port = "0"
}

graphics {
type = "spice"
listen_type = "address"
autoport = true
}
depends_on = [
    libvirt_volume.server-os,
        libvirt_volume.server-data,

          ]
}


output "localvars" {
   value = local.servers
}
output "datadisks" {
   value = local.disks
}

```
### Steps to Reproduce Issue
1. try to pass list of disks.
(Include debug logs if possible and relevant).
2. i get below error.

 ```hcl
Error: Unsupported argument
 on main.tf line 85, in resource "libvirt_domain" "server-vm":
  85: disk = [ each.value["diskmap"] ]

An argument named "disk" is not expected here. Did you mean to define a block
of type "disk"?
```

3. should work as described in documentation. 
___
## Additional information:
Could it be due to changes in terraform v 0.12 ?
https://www.terraform.io/docs/configuration/syntax.html#arguments-and-blocks

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?
selinux is set to permissive.

**Comment by jslinuxta** [comment]
diskmap as created by variables
datadisks = [
  "server-0-0",
  "server-0-1",
]
localvars = {
  "server-0" = {
    "cpu" = 2
    "dd" = 2
    "ddsize" = 21474836480
    "diskmap" = [
      {
        "volume_id" = "/data2/images/server-0-0-data.qcow2"
      },
      {
        "volume_id" = "/data2/images/server-0-1-data.qcow2"
      },
    ]
    "index" = 0
    "mem" = 2
    "name" = "server-0"
    "osdisk" = "server-0-os.qcow2"
    "pname" = "server"
  }
}

**Comment by MalloZup** [comment]
@jslinuxta thx for issue . can you format better the hcl code?

```hcl
"volume_id" = "/data2/images/server-0-1-data.qcow2"
},
]
"index" = 0
"mem" = 2
"name" = "server-0"
"osdisk" = "server-0-os.qcow2"
"pname" = "server"
}
}
```

**Comment by jslinuxta** [comment]
done, thx

**Comment by MalloZup** [comment]
@jslinuxta take look here:

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/modules/hana_node/main.tf#L21

**Comment by jslinuxta** [comment]
Thanks @MalloZup 
My use case is achieved by using dynamic block.
e.g.
```hcl
variable "servercount" {
  type = number
  default = 1
  }
variable "ddsize" {
  type =  number
  default = 21474836480
}
variable "cpu" {
  type =  number
  default = 2
}
variable "mem" {
  type =  number
  default = 2048
}
variable "servname" {
  type =  string
  default = "server"
}
variable "disks" {
  type =  number
  default = 3
}

locals {
  servers = {
    for s in range(var.servercount) : "${var.servname}-${s}" => {
        dd  = var.disks
        ddsize = var.ddsize
        cpu = var.cpu
        mem  = var.mem
        name = "${var.servname}-${s}"
        pname = var.servname
        diskmap = [ for n in range(var.disks):  { volume_id = "${libvirt_volume.server-data["${var.servname}-${s}-${n}"].id}"} ]
        index = s

    }

  }
  disks = flatten([
    for s in range(var.servercount) : [
    for c in range(var.disks) : "${var.servname}-${s}-${c}"  ]
  ])
}

provider "libvirt" {
  uri = "qemu:///system"
  }

resource "libvirt_volume" "server-os" {
  for_each = local.servers
  name = "${lookup(each.value, "name", "osdisk.qcow2")}-os.qcow2"
  pool = "data2"
  source = "/data2/images/centos7hostb.qcow2"
  format = "qcow2"
}
resource "libvirt_volume" "server-data" {
  for_each = toset(local.disks)
  name = "${each.value}-data.qcow2"
  pool = "data2"
  size =  var.ddsize
  format = "qcow2"
}

resource "libvirt_domain" "server-vm" {
for_each = local.servers

  name   = each.key
  memory = each.value["mem"]
  vcpu   = each.value["cpu"]
  network_interface {
  bridge = "br0"
  }

disk {
  volume_id = libvirt_volume.server-os[ each.key ].id
  }
dynamic "disk" {
  iterator = datadisksrv
  for_each  = each.value["diskmap"]
content  {
  volume_id = datadisksrv.value["volume_id"]

    }
    }

console {
type = "pty"
target_type = "serial"
target_port = "0"
}

graphics {
type = "spice"
listen_type = "address"
autoport = true
  }
depends_on = [
    libvirt_volume.server-os,
    libvirt_volume.server-data,  ]
}


output "localvars" {
  value = local.servers
}
output "localdisks" {
value = local.disks
}
```

**Comment by craigafinch** [comment]
I have a simpler way to reproduce the bug without using dynamic generation. The file below produces the same error:

```hcl
resource "libvirt_volume" "sda" {
  name = "sda.qcow2"
  pool = "default"
  size = "8589934592"
  format = "qcow2"
}

resource "libvirt_volume" "sdb" {
  name = "sdb.qcow2"
  pool = "default"
  size = "68719476736"
  format = "qcow2"
}

resource "libvirt_domain" "my-vm" {
  name   = "my-vm"
  memory = "2048"
  vcpu   = 2

  network_interface {
    bridge = "br0.13"
  }

  disk = [
    {
      volume_id = "${libvirt_volume.sda.id}"
    },
    {
      volume_id = "${libvirt_volume.sdb.id}"
    }
  ]

  boot_device {
    dev = ["hd", "network"]
  }

  console {
    type = "pty"
    target_type = "serial"
    target_port = "0"
  }
  graphics {
    type = "spice"
    listen_type = "address"
    autoport = true
  }
  video {
    type = "vga"
  }
}
```

**Comment by remoe** [comment]
I can confirm this. The feature comes from:

https://github.com/dmacvicar/terraform-provider-libvirt/pull/83
I can't find a test-code here:
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/domain.go

for this feature.

**Comment by MalloZup** [comment]
might need to check. thx for issue and reproduction guys! :cupid:

**Comment by jon4hz** [comment]
I just had the same error. I could fix it by replacing disk = [{...}] with disk {...}

**Comment by sferich888** [comment]
> I just had the same error. I could fix it by replacing disk = [{...}] with disk {...}

Can you show an example of what you did? How did you supply multiple disjs with just, {..}? 

Or did you supply {..},{..}?

**Comment by jon4hz** [comment]
It's not a very beautiful solution but it's the only way I could get it to work.

    disk {
        volume_id = libvirt_volume.volume[count.index].id
        scsi = true
    }
    disk {
        file = "/home/admin/Downloads/ubuntu-18.04.3-live-server-amd64.iso"
    }

**Comment by sferich888** [comment]
I think the issue here is described by https://github.com/hashicorp/terraform/issues/20505#issuecomment-468392320 with the core fix being https://github.com/hashicorp/terraform/pull/20837 (some opt in syntax model). 

@apparentlymart may be a good contact for figuring out if this is the case; and/or what needs to be done to adjust this provider code.

**Comment by sferich888** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/707 I think may resolve this.

**Comment by MalloZup** [comment]
I'm closing this issue thx to @sferich888 please reopen if latest fix doesn't solve it. thx to all people! :flower_playing_cards:

**Comment by frgomes** [comment]
For the benefit of people landing here, trying to find a relatively simple way to provision several disks:

```
variable "volumes" {
  description = "volumes"
  type = list(object({ label=string, size=number }))
  default = [
    {
      label = "data00"
      size = 10240000
    }
  ]
}
```

```
resource "libvirt_volume" "volume" {
  for_each = { for vol in var.volumes: vol.label => vol }
  name   = format("%s-%s-%s.qcow2", var.network_name, var.hostname, each.key)
  pool   = "${var.pool_name}"
  size   = each.value.size
  format = "qcow2"
}
```

```
resource "libvirt_domain" "domain" {
  ...
  disk {
    volume_id = libvirt_volume.system.id
  }

  dynamic "disk" {
    for_each = tolist([ for vol in var.volumes: {
      volume_id = lookup(libvirt_volume.volume, vol.label).id
    }])
    content {
      volume_id = disk.value.volume_id
    }
  }
...
}
```
