### ISSUE TITLE
Interpolation-only expressions are deprecated

### ISSUE THREAD

**Issue by hvad** [dmacvicar/terraform-provider-libvirt#673]
### Linux distribution

Fedora 31

### Terraform version

0.12

### Provider and libvirt versions

0.6 for Fedora 28

___

## Description of Issue/Question

Warning: Interpolation-only expressions are deprecated

  on main.tf line 23, in resource "libvirt_domain" "centos7":
  23:     volume_id = "${libvirt_volume.centos7-qcow2.id}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

### Setup
main.tf 

provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_volume" "centos7-qcow2" {
  name = "centos7.qcow2"
  pool = "images"
  source = "/var/lib/libvirt/images/centos.qcow2"
  format = "qcow2"
}

resource "libvirt_domain" "centos7" {
  name   = "centos7"
  memory = "1024"
  vcpu   = 1

  network_interface {
    network_name = "default"
  }

  disk {
    volume_id = "${libvirt_volume.centos7-qcow2.id}"
  }

  console {
    type = "pty"
    target_type = "serial"
    target_port = "0"
  }

}

### Steps to Reproduce Issue

terraform plan
___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
No SELinux or Apparmor

**Comment by MalloZup** [comment]
@hvad can you add more detail to your issue and problem? TIA :pray:

**Comment by hvad** [comment]
Hello, 
What do need ? it's a warning on terraform 0.12.   
${ is deprecated syntax used on 0.11 version. If i replace ${ by syntax for 0.12 this module don't work.
Bye

**Comment by MalloZup** [comment]
@hvad I can't understand one thing. Are using a `main.tf` from our examples? Which module are you referring?

**Comment by hvad** [comment]
Hi,
Sorry when i talk about module it's for terraform-provider-libvirt.  
If i use " volume_id = "${libvirt_volume.centos7-qcow2.id}"" on my main.tf then i have  "Warning: Interpolation-only expressions are deprecated" because ${ is depracated on terraform version 0.12.

**Comment by MalloZup** [comment]
@hvad  I'm stil not getting this issue.

The warning you get is a `terraform` warning upstream which the provider cannot fix.

The warning refer to the HCL language which we don't maintain here.

closing for this. If you have any question feel free to piing me
