### ISSUE TITLE
Is it possible to launch a custom image on KVM by using terraform provider libvirt

### ISSUE THREAD

**Issue by Antonynixson** [dmacvicar/terraform-provider-libvirt#696]
Hello there,

I'm a newbie to this KVM and libvirt, so pardon me if this sounds silly, i just want to know is it possible to launch a custom images as VM on KVM using this provider ?

example,
i have clone of a VM which i took from a KVM, now i want to launch that cloned vm to another KVM, is this possible ? can anyone please let me know.

Thanks,
Antonynixson

**Comment by MalloZup** [comment]
hi @Antonynixson  you can have base volumes from this you can have different VMs

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/volume.html.markdown#example-usage

**Comment by Antonynixson** [comment]
Hello @MalloZup

Thanks for help. i will check this, as of now i will close this case
