### ISSUE TITLE
Is it possible to Assign a static IP to a VM on KVM by using Terraform

### ISSUE THREAD

**Issue by Antonynixson** [dmacvicar/terraform-provider-libvirt#697]
Hello there,

I just want to know is it possible to launch a custom image as VM  **with Static IP address** on KVM using this provider ?

Thanks,
Antonynixson

**Comment by mateuszbanasiewicz** [comment]
yes and no... becouse if you use resource libvirt_domain -> network_interface (https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown) you can set that VM will be have static IP address. After every boot you will be have this same IP address. But it is not static IP which is configured on network interface in OS. This solution is realized by internal KVM DHCP for network. It is constant connection between MAC na IP address. :)

**Comment by Antonynixson** [comment]
Hello @mateuszbanasiewicz 

Thanks for the replay, i understood.
