### ISSUE TITLE
Is it possible to attach multiple network interface into a guest VM by using this provider ?

### ISSUE THREAD

**Issue by Antonynixson** [dmacvicar/terraform-provider-libvirt#700]
Hello there,

Can anyone please let me know, is there any possibility to attach multiple network interface into a guest VM ?

By using the below parameters i can attach two network interface into a guest VM through virsh command,
`--network=bridge=br0,model=virtio --network network=default
`

**how can i achieve the same using terraform ?**

Thanks,
Antonynixson

**Comment by MalloZup** [comment]
yes it is possible.

Check out our tests:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/db13b678ab16fe9dca024c3daea6e56fb4cc4ae2/libvirt/resource_libvirt_domain_test.go#L578

hope it helps, let me know.! closing!
