### ISSUE TITLE
Could not get the output IP of the VM on first terraform apply

### ISSUE THREAD

**Issue by Antonynixson** [dmacvicar/terraform-provider-libvirt#702]
Hello there,

i'm facing a weird issue.

i'm trying to launch a VM using the terraform, 
yes i can able to launch a VM with DHCP on my KVM, 

**but when i run terraform apply it will lauch a VM only !!**

**if i run terraform apply again it will get the IP !!**

_i want IP of the VM with the first apply ?!_ 
**is it possible ? can anyone please help me ?**

### **Please find my code below**

```
# instance the provider
provider "libvirt" {
  uri = "qemu+ssh://root@192.168.230.11/system"
}

# We fetch the latest ubuntu release image from their mirrors
resource "libvirt_volume" "ubuntu-qcow2" {
  name = "ubuntu-qcow2"
  pool   = "images"
  source = "https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  format = "qcow2"
}

resource "libvirt_network" "vm_network" {
  name      = "vm_network"
  autostart = "true"
  addresses = ["192.168.123.0/24"]
  dhcp {
    enabled = true
  }
}

# Create the machine
resource "libvirt_domain" "domain-ubuntu" {
  name   = "ubuntu-terraform"
  memory = "512"
  vcpu   = 1


  network_interface {
    network_id   = "${libvirt_network.vm_network.id}"
    network_name = "vm_network"
  }


  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
    type        = "pty"
    target_type = "virtio"
    target_port = "1"
  }

  disk {
    volume_id = libvirt_volume.ubuntu-qcow2.id
  }

  graphics {
    type        = "spice"
    listen_type = "address"
    autoport    = true
  }
}

terraform {
  required_version = ">= 0.12"
}


output "ip" {
 value = "${libvirt_domain.domain-ubuntu.network_interface[0].addresses[0]}"
}
```

Thanks,
Antonynixson

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/19c23424ccfdecf6dfcbdd87783bf835ba5f585e/examples/v0.12/count/main.tf#L25

**Comment by MalloZup** [comment]
@Antonynixson hi! for such question, you can ask in the chat:

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown#handling-network-interfaces

check for wait_for_lease.

also other examples:

https://github.com/SUSE/ha-sap-terraform-deployments/blob/be49f2ef3391e00ea2157f8d0a16ffbbbb0b9579/libvirt/modules/monitoring/main.tf#L24

after you get the IP, you create an output variable like this

https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/outputs.tf#L7

I'm closing . If you need help just ping me
