### ISSUE TITLE
No bootable device multiple disks with one disk file iso

### ISSUE THREAD

**Issue by tmpm697** [dmacvicar/terraform-provider-libvirt#713]
### Linux distribution

``` archlinux latest ```

### Terraform version

```sh
Terraform v0.13.0-dev
```

### Provider and libvirt versions

```sh
from aur/terraform-provider-libvirt-git: 95a406b6b2243a84e6211b41bcb309f600cfaa14-dirty
```
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question
I setup two disks, one of them is `.iso` to boot and install OS on the other one. But it results to "No bootable device" even though I put `.iso` first in `.tf` file -- I doubt it doesn't matter the order.

### Setup

```
resource "libvirt_volume" "myosdisk-qcow2" {
  name   = "myosdisk"
  pool   = "default"
  size   = 40000000000
  format = "qcow2"
}

#....

  disk {
    file = "/var/lib/libvirt/images/myisofile.iso"
  }
  disk {
    volume_id = libvirt_volume.myosdisk-qcow2.id
  }
```

I expect the produced running vm be bootable.

**Comment by MalloZup** [comment]
@tmpm697  thx for issue. Can you try your example by inverting the order , putting the `iso` at the end of the list, because I suspect the list order matters since we iterate over. thx

**Comment by tmpm697** [comment]
@MalloZup It gave the same result: `No bootable device`.

**Comment by MalloZup** [comment]
@tmpm697 could you make your Terraform files and iso image reproducible?

So i could downlad them from somewhere and run terraform apply to reproduce it?

Thx

**Comment by LangError** [comment]
Not that I like necro'ing threads, but I experienced the same issue and wanted to share a solution.
In your `libvirt_domain` resource, specify a desired boot order with `boot_device`.
For example, to boot from an iso and set disk and network boot as backup:
`boot_device { dev = [ "cdrom", "hd", "network" ] }`

You can find this in the documentation [here](https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/domain.html.markdown#define-boot-device-order) although it doesn't show the `"cdrom"` option.

**Comment by tmpm697** [comment]
Thanks @LangError ,  seem reasonable, I'll give a try later.
