### ISSUE TITLE
Release 0.6.2

### ISSUE THREAD

**Issue by dmacvicar** [dmacvicar/terraform-provider-libvirt#719]
Tracking issue to release 0.6.2

Right now I am facing the following issues when running the testsuite locally:

```
=== RUN   TestAccLibvirtDomain_NetworkInterface
--- FAIL: TestAccLibvirtDomain_NetworkInterface (314.62s)
    testing.go:635: Step 0 error: errors during apply:

        Error: Error: couldn't retrieve IP address of domain.Please check following:
        1) is the domain running proplerly?
        2) has the network interface an IP address?
        3) Networking issues on your libvirt setup?
         4) is DHCP enabled on this Domain's network?
        5) if you use bridge network, the domain should have the pkg qemu-agent installed
        IMPORTANT: This error is not a terraform libvirt-provider error, but an error caused by your KVM/libvirt infrastructure configuration/setup
         timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)
```

//cc @MalloZup

**Comment by MalloZup** [comment]
@pablochacin @flavio CC

**Comment by MalloZup** [comment]
I don't have the failure locally.

However we could perhaps change the test to use a more canonical `pts` like `/dev/pts`/0`  (I'm not an expert there but I assume the `/dev/pts/0` could be more present then the `2`)

**Comment by pablochacin** [comment]
I don't have it either. Maybe something related to the OS version?  I was testing with OpenSuse leap 15.1.

**Comment by MalloZup** [comment]
I remember in past I had similar issue. ( I'm using also leap 15.1).
The question here is if we could assume like `pts/0` is kind universal among version of OS

**Comment by pablochacin** [comment]
I'm not 100% sure I understand the purpose of the tests, but the selection of the source seems rather irrelevant. Why not using the `pts` associated with the process that starts the test? It is associated with the `fd 0` of the process:
```
[~]$ readlink /proc/self/fd/0
/dev/pts/13
```

**Comment by MalloZup** [comment]
We could implement this dynamical lookup in the test yes. Should be 2/3 lines of code

**Comment by pablochacin** [comment]
I could do it, but I cannot test it solves the issue because I don't have this error locally.

**Comment by MalloZup** [comment]
yop if it works, we can assume it is working . :) the approach seems quite logic to me ;)

**Comment by dmacvicar** [comment]
The failure went away in my machine. Basically `/dev/pts/2` now exists.

I would still make the test more robust.

**Comment by dmacvicar** [comment]
Now focusing on the network one

**Comment by dmacvicar** [comment]
> readlink /proc/self/fd/0

I think the issue is that the test creates two consoles

**Comment by dmacvicar** [comment]
The network test also fails randomly, so it is also a problem of robustness/timeouts etc.

**Comment by pablochacin** [comment]
One last thing: the test uses two pts for two different consoles, not sure how to ensure that constrain. :thinking:

**Comment by pablochacin** [comment]
> > readlink /proc/self/fd/0
> 
> I think the issue is that the test creates two consoles

yes, I had realized that. Maybe the solution could be creating the two pts as described [here](http://man7.org/linux/man-pages/man4/pts.4.html), but there is not wrapping for the `tpsname` function they propose to use.

**Comment by pablochacin** [comment]
> The network test also fails randomly, so it is also a problem of robustness/timeouts etc.

Ok, let me know if I can help. I ran the tests multiple times and didn't get any such error.

**Comment by pablochacin** [comment]
For me, the one that fails consistently is this 
```
--- FAIL: TestAccLibvirtDomain_BlockDevice (0.07s)
    resource_libvirt_domain_test.go:359: Error searching for available loop device: exit status 1
```

I will take a closer look.

**Comment by pablochacin** [comment]
> For me, the one that fails consistently is this
> 
> ```
> --- FAIL: TestAccLibvirtDomain_BlockDevice (0.07s)
>     resource_libvirt_domain_test.go:359: Error searching for available loop device: exit status 1
> ```
> 
> I will take a closer look.

fixed https://github.com/dmacvicar/terraform-provider-libvirt/pull/722

**Comment by pablochacin** [comment]
> The failure went away in my machine. Basically `/dev/pts/2` now exists.
> 
> I would still make the test more robust.

Fixed in https://github.com/dmacvicar/terraform-provider-libvirt/pull/724

**Comment by dmacvicar** [comment]
I have things passing now. I will push a release! thanks a lot for the help guys!

**Comment by MalloZup** [comment]
done thx!
