### ISSUE TITLE
IDE controllers are unsupported for q35

### ISSUE THREAD

**Issue by anatolinicolae** [dmacvicar/terraform-provider-libvirt#737]
Provisioning via cloud-init is not correctly working on pc-q35 as the disk type is IDE. Is there a way to correctly create the disk as SATA or SCSI somehow?

https://github.com/dmacvicar/terraform-provider-libvirt/blob/51360982064c2e6447d1af075409ee9243dcfe30/libvirt/domain.go#L202-L213

**Comment by MalloZup** [comment]
@anatolinicolae hi thx for issue.

If we are hardcoding I think what we could do is to provide a parameter for the cloudinit type..

I personally dunno, if it could work, but we have also another feature which avoid the need of creating patch.

https://github.com/dmacvicar/terraform-provider-libvirt/blob/19c23424ccfdecf6dfcbdd87783bf835ba5f585e/website/docs/r/volume.html.markdown#altering-libvirts-generated-volume-xml-definition

we can alter disks with xslt/xml. I think that with this feature you can alter the cloudinit-disk

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/blob/19c23424ccfdecf6dfcbdd87783bf835ba5f585e/examples/v0.12/xslt/main.tf#L5

**Comment by MalloZup** [comment]
let me know how it goes

**Comment by anatolinicolae** [comment]
The suggestion actually worked. Applying the following xsl correctly defines the VM:
```xml
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes" indent="yes"/>
    <xsl:template match="node()|@*">
        <xsl:copy>
            <xsl:apply-templates select="node()|@*"/>
        </xsl:copy>
    </xsl:template>

    <xsl:template match="/domain/os/type/@machine">
        <xsl:attribute name="machine">
            <xsl:value-of select="'pc-q35-rhel7.6.0'"/>
        </xsl:attribute>
    </xsl:template>

    <xsl:template match="/domain/devices/disk/target/@bus">
        <xsl:attribute name="bus">
            <xsl:value-of select="'sata'"/>
        </xsl:attribute>
    </xsl:template>

    <xsl:template match="/domain/devices/disk/wwn" />

</xsl:stylesheet>
```
