### ISSUE TITLE
terraform destroy does not destroy inactive networks it leaves behind when creation fails

### ISSUE THREAD

**Issue by captainwasabi** [dmacvicar/terraform-provider-libvirt#739]
### Linux distribution

Centos7.8

### Terraform version

Terraform v0.12.25

### Provider and libvirt versions

./terraform-provider-libvirt 0.6.2+git.1585292411.8cbe9ad0
Compiled against library: libvirt 4.1.0
Using library: libvirt 4.5.0
Running hypervisor: QEMU 1.5.3
Running against daemon: 4.5.0

### Description

I'm not including exact steps because they might vary from system to system.

I guess what I would say is special /different about this which might be the literal cause of this issue is that I already have some libvirt networks setup on the host. I inadvertently used the same ip address space in the terraform network as was being used by one of the other libvirt networks, this caused the network creation to fail.  However, it actually partially created the network, it shows up in virsh net-list --all.  I ran terraform destroy and it destroyed everything, but, after I fixed the issue and applied it again, it failed creating the network stating that it already existed.  Since terraform failed I would have expected for it to undefine whatever it had done.

I tried refreshing the state, manually removing the network from the state (which it wasn't even in the state because it failed to create, but I did it anyway), etc.

I had to virsh net-undefine network-name by hand to get it to work.

Another effect of having existing libvirt networks is that I had to explicitly declare what bridge to use even though I'm not using bridged mode.  This was also causing network creation to fail because virbr# already existed.  Again, had to undefine the partially created network by hand. (I think this would be related to #703 )

I know this might not be considered a bug, since best-practice would be to start with a clean host, but it was unexpected behavior that I thought was worth documenting somewhere.

**Comment by MalloZup** [comment]
@captainwasabi thx for issue. I had also similar issue, I will let the issue open, we might need to research how we can improve it

**Comment by MalloZup** [comment]
@captainwasabi  can you provide me a clear howto reproduce . We might need to fix this. thx!

**Comment by MalloZup** [comment]
@captainwasabi if you can reproduce, can you attach the log with 

`TF_LOG=DEBUG terraform apply`? thx

**Comment by MalloZup** [comment]
@captainwasabi can you test this issue with this patch and providing me feedback? thx!

**Comment by captainwasabi** [comment]
will do as soon as I get a chance.

I assume this happens with all resources.  had a domain where the same thing happened.  I tried sharing a filesystem with the host (passthrough) and it failed to start the domain (centos host doesn't support f9 :( ). but it created it.  virsh list --all showed it.  ran destroy, removed the filesystem clause, applied and it failed saying the vm existed already, but it wasn't in the terraform state.  Same thing as the network issue.

**Comment by MalloZup** [comment]
@captainwasabi  lets focus on the `network` if we find the same thing is happening for domain we can open an issue for domain and other resource.

Afaik the domain resource has other mechanism. we can fix this one first then check the others.

**Comment by MalloZup** [comment]
I will also try from my side to do some test with the patch, but I think it should fix (https://github.com/dmacvicar/terraform-provider-libvirt/pull/742)

**Comment by MalloZup** [comment]
@captainwasabi  I could not reproduce even without the patch.
I guess we need a clear way to reproduce this. RIght now I could not

**Comment by captainwasabi** [comment]
create a libvirt network by hand using:

<network>
  <name>br-dev</name>
  <bridge name='br-dev' stp='on' delay='0'/>
  <ip address='10.101.2.0' netmask='255.255.255.0'>
  </ip>
</network>

then create a network using terraform that uses that same network address
When the plan is applied the terraform creation will fail, but the network will have actually been created in libvirt as can be seen by doing "virsh net-list --all"
terraform state list does not find it because it failed
terraform destroy doesn't.
fix the address in the .tf so it's not using the same network
try to apply the plan, fails saying that the network already exists.
virsh net-undefine the network that you could see from the net-list above
then apply the plan, it succeeds.

This is kinda from memory.  if you need more detail or want to see a capture of the config files and output of the commands I'll get to that when I can.  (I'll have to spin up a clean server)

**Comment by MalloZup** [comment]
@captainwasabi ok now i get it thx

**Comment by MalloZup** [comment]
@captainwasabi  ok so I think I have fixed this.

The fix is following:

if the user try to create a network which has already an ip, and libvirt create an `artifact` broken network, we remove it.

Example:
- network A exist already
- I created network B via terraform (with same adress)

the provider fail with error `Error creating libvirt network: virError(Code=1, Domain=0, Message='internal error: Network is already in use by interface br-dev')`

- now the user should change the IP on terraform

( behind the hood we remove the `broken network`)
- if the user change IP everyting works

**Comment by MalloZup** [comment]
can you try this patch
https://github.com/dmacvicar/terraform-provider-libvirt/pull/742

I alredy tested it
@captainwasabi

**Comment by captainwasabi** [comment]
Sorry, I'm in crunch time for a major deployment.  learning ansible and terraform at the same time and making them work together.  just looking at the code, the  network.Destroy() is going to fail because the network isn't started, as long as that isn't going to kick you out of that code section, and network.Undefine() gets called anyway, I'm sure that this will work for me.  

Just to mention again that I also had the same issue with domains.  it failed in a particular way where it was setting stuff up but couldn't do the filesystem {} because Centos doesn't support the f9 filesystem type.  I've had other errors, like the domain name already existing, that fail out and don't have a problem.

**Comment by captainwasabi** [comment]
how do I get a build with this patch?

**Comment by MalloZup** [comment]
@captainwasabi the patch is avail on un-released build. 

So you need to build from devel `master` branch 
https://github.com/dmacvicar/terraform-provider-libvirt#requirements
