### ISSUE TITLE
IPv4/IPv6 Network wrong DHCP range

### ISSUE THREAD

**Issue by johscheuer** [dmacvicar/terraform-provider-libvirt#752]
### Linux distribution

``` Ubuntu 20.04 LTS (Focal Fossa)```

### Terraform version

```sh
 terraform -v
Terraform v0.12.26
+ provider.libvirt v0.6.2
+ provider.template v2.1.2
```

### Provider and libvirt versions

```sh
../.terraform.d/plugins/terraform-provider-libvirt_v0.6.2 8cbe9ad08b26eb53ae212c28aca40f1eff5d7350
Compiled against library: libvirt 6.4.0
Using library: libvirt 6.4.0
```
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [ ] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

I tried to setup a local development environment and I wanted to test some IPv4/IPv6 Dualstack settings. For setting up the network I wanted to follow the examples: https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/network.markdown but I get the following error by libvirt:

```bash
Error: Error defining libvirt network: virError(Code=1, Domain=0, Message='internal error: range fd4a:ffff:ffff::2 - fd4a:ffff:ffff::ffff:ffff:ffff:fffe is too large (> 65535)') -   <network>
      <name>k8snet</name>
      <forward mode="nat"></forward>
      <bridge name="k8snet-br" stp="on"></bridge>
      <domain name="k8s.local" localOnly="yes"></domain>
      <dns enable="yes"></dns>
      <ip address="172.16.0.1" family="ipv4" prefix="24">
          <dhcp>
              <range start="172.16.0.2" end="172.16.0.254"></range>
          </dhcp>
      </ip>
      <ip address="fd4a:ffff:ffff::1" family="ipv6" prefix="64">
          <dhcp>
              <range start=fd4a:ffff:ffff::2" end="fd4a:ffff:ffff::ffff:ffff:ffff:fffe"></range>
          </dhcp>
      </ip>
  </network>

  on network.tf line 1, in resource "libvirt_network" "kube_network":
   1: resource "libvirt_network" "kube_network" {
```

So from my point of view there are two things that we can fix (correct me if I'm wrong):

- Ensure that the DHCP range generated by the provider is > 65535
- Allow to set the DHCP mode value of `enabled` to `ipv4` (or `ipv4only`), this would be an addition and wouldn't break the current behaviour. We could also add `ipv6` or `ipv6only` for consistency.

### Setup

(Please provide the full _main.tf_ file for reproducing the issue (Be sure to remove sensitive information)

```hcl
resource "libvirt_network" "kube_network" {
  autostart = true
  name = "k8snet"
  mode = "nat"
  domain = "k8s.local"
  addresses = ["172.16.0.0/24", "fd4a:ffff:ffff::1/64"]
  bridge = "k8snet-br"
  dns {
    enabled = true
    local_only = true
  }
}
resource "libvirt_domain" "master" {
  name       = "master"
  memory     = "4096"
  vcpu       = 2
  qemu_agent = true
  autostart  = true

  network_interface {
    network_name   = libvirt_network.kube_network.name
    wait_for_lease = true
  }

  # IMPORTANT: this is a known bug on cloud images, since they expect a console
  # we need to pass it
  # https://bugs.launchpad.net/cloud-images/+bug/1573095
  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }

  console {
    type        = "pty"
    target_type = "virtio"
    target_port = "1"
  }

  disk {
    volume_id = libvirt_volume.master.id
  }

  graphics {
    type        = "spice"
    listen_type = "address"
    autoport    = true
  }
}
```

### Steps to Reproduce Issue

(Include debug logs if possible and relevant).

See above.
___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

I use terraform from my Mac to work against a remote Ubuntu server.

If you think the proposed changes make sense I'm happy to contribute the code changes.

**Comment by MalloZup** [comment]
@johscheuer do we solved this by PR?

**Comment by johscheuer** [comment]
Solved by https://github.com/dmacvicar/terraform-provider-libvirt/pull/753
