### ISSUE TITLE
Support for osinfo/guest_id

### ISSUE THREAD

**Issue by gthieleb** [dmacvicar/terraform-provider-libvirt#756]
I digged through the documentation but could not find anything related about setting the `osinfo` related attributes.
Is it possible with libvirt plugin to define the os information? In vsphere plugin this is called `guest_id`. 

E.g.
```
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://ubuntu.com/ubuntu/20.04"/>
    </libosinfo:libosinfo>
  </metadata>
```

**Comment by MalloZup** [comment]
@gthieleb you can use XML for injecting this. SEE:

https://github.com/SUSE/ha-sap-terraform-deployments/blob/0ed22a718e76fac577eb5749de9a71fe5d9ad4e1/libvirt/modules/shared_disk/main.tf#L7

as 
example
and check our doc for this

https://github.com/dmacvicar/terraform-provider-libvirt/blob/7ed02c5aa9bcc76434fb6d36c0de6f3a3474bdf9/website/docs/r/domain.html.markdown#altering-libvirts-generated-domain-xml-definition

**Comment by MalloZup** [comment]
@gthieleb did you find anything?

**Comment by mvrk69** [comment]
Hi, i'm looking for the same thing, but couldn't find a way yet, i tried like this:

`<?xml version="1.0" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output omit-xml-declaration="yes" indent="yes"/>
  <xsl:template match="node()|@*">
     <xsl:copy>
       <xsl:apply-templates select="node()|@*"/>
     </xsl:copy>
  </xsl:template>

  <xsl:template match="/domain">
    <xsl:copy>
	<xsl:apply-templates select="node()|@*"/>
            <xsl:element name ="metadata">
                <xsl:element name="libosinfo:libosinfo">
                    <xsl:attribute name="xmlns:libosinfo">"http://libosinfo.org/xmlns/libvirt/domain/1.0"</xsl:attribute>
                    <xsl:element name="libosinfo:os">
                        <xsl:attribute name="id">"http://redhat.com/rhel/9.0"</xsl:attribute>
                    </xsl:element>
                </xsl:element>
            </xsl:element>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
`
but i get Error: error applying XSLT stylesheet: exit status 5

@gthieleb you found a solution?

**Comment by jobcespedes** [comment]
The following worked for me:
```xls
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output omit-xml-declaration="yes" indent="yes"/>
  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="/domain">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*" />
      <xsl:element name="metadata">
        <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
          <xsl:element name="libosinfo:os">
            <xsl:attribute name="id">http://fedoraproject.org/coreos/stable</xsl:attribute>
          </xsl:element>
        </libosinfo:libosinfo>
      </xsl:element>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>
```

**Comment by mvrk69** [comment]
> The following worked for me:
> 
> ```
> <?xml version="1.0" ?>
> <xsl:stylesheet version="1.0"
>                 xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
>   <xsl:output omit-xml-declaration="yes" indent="yes"/>
>   <xsl:template match="node()|@*">
>     <xsl:copy>
>       <xsl:apply-templates select="node()|@*"/>
>     </xsl:copy>
>   </xsl:template>
> 
>   <xsl:template match="/domain">
>     <xsl:copy>
>       <xsl:apply-templates select="node()|@*" />
>       <xsl:element name="metadata">
>         <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
>           <xsl:element name="libosinfo:os">
>             <xsl:attribute name="id">http://fedoraproject.org/coreos/stable</xsl:attribute>
>           </xsl:element>
>         </libosinfo:libosinfo>
>       </xsl:element>
>     </xsl:copy>
>   </xsl:template>
> 
> </xsl:stylesheet>
> ```

Thank you, i tried like that and works fine.
