### ISSUE TITLE
Add support for managed storage pools

### ISSUE THREAD

**Issue by moio** [dmacvicar/terraform-provider-libvirt#76]
Currently storage pools are left to be managed manually, it would be good to have them managed through the plugin.

**Comment by dmacvicar** [comment]
I don't think destroying pools is a common use-case outside of development/testing, but I think adding support for this is very self-contained.

**Comment by dmacvicar** [comment]
Ok, now I remember why it was intentionally left out. Pools can be of various types: dir, fs, netfs, disk, iscsi, logical, scsi, and every type has different attributes. The original intention of this provider was to mimic a "cloud" environment and avoid exposing all libvirt features and become a HCL -> XML 1:1 mapping.

So supporting pools means you have to expose all functionality, or restrict yourself to a few and document that. Do you think it is worth the additional complexity?

**Comment by inercia** [comment]
I don't know if managing pools could be considered part of the typical use case, so I think I agree with @dmacvicar: I wouldn't include all the logic for managing pools unless it is really necessary.

**Comment by moio** [comment]
OK, I agree to close this issue for now.
