### ISSUE TITLE
Are Hugepages possible?

### ISSUE THREAD

**Issue by ElCoyote27** [dmacvicar/terraform-provider-libvirt#760]
Hi,
I was trying to launch a simple KVM guest with static hugepages (supported by Fedora and RHEL/Centos) but all of my attempts have failed.. Is it curently possible to get this to work?

Works (without hugepages):
```
provider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_domain" "terraform_test" {
  name          = "terraform_test"
  memory        = "512"
  vcpu          = 2
  }
}
```

Does not work (not sure if the syntax works as an erreor is reported during apply):
```
rovider "libvirt" {
  uri = "qemu:///system"
}

resource "libvirt_domain" "terraform_test" {
  name          = "terraform_test"
  memory        = "512"
  vcpu          = 2
  memoryBacking {
    hugepages = 2024
  }
}
```
Having hugepages would help with larger VMs and hosts with lots of memory. It is sufficient to add this to the guest's XML (defaults to 2mb pages unless a custom hugepage size is desired - 1G):
```
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
```

**Comment by MalloZup** [comment]
@ElCoyote27  You might look at this feature:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/19c23424ccfdecf6dfcbdd87783bf835ba5f585e/website/docs/r/volume.html.markdown#altering-libvirts-generated-volume-xml-definition

you can alter the  domain XML  with this and add it.

let  me  know

**Comment by ElCoyote27** [comment]
@MalloZup That looks promising but I'm having a hard time locating an example.
Something like this?
```resource "xml" {
  xslt = .....
}```

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/v0.12/xslt check this

**Comment by MalloZup** [comment]
@ElCoyote27 is your question solved? in case feel free to close tia

**Comment by ixevix** [comment]
I have the same need. But where to start figuring out how to use this xslt?

**Comment by MonolithProjects** [comment]
@ixevix you can take a look on how i did it in my Terraform Module https://github.com/MonolithProjects/terraform-libvirt-vm

**Comment by ixevix** [comment]
> @ixevix you can take a look on how i did it in my Terraform Module https://github.com/MonolithProjects/terraform-libvirt-vm

Works great! Thanks!
