### ISSUE TITLE
WIP: Terraform libvirt provider New 0.6.3 Release Draft/Plan

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#764]
##  Current Draft:

# Highlights:

## Network:
- Permit creation of multiple libvirt networks  (https://github.com/dmacvicar/terraform-provider-libvirt/pull/740)
- Make static IP addresses permanent across reboots (https://github.com/dmacvicar/terraform-provider-libvirt/pull/763)
- handle correctly network failures by creation phase (https://github.com/dmacvicar/terraform-provider-libvirt/pull/742)
- Add dev attribute to network configuration (https://github.com/dmacvicar/terraform-provider-libvirt/pull/725)
- increase  timeout/delay for  qemu-guest-agent (https://github.com/dmacvicar/terraform-provider-libvirt/pull/732)
- Adjust generated dhcp to match libvirt limitation of max 65535 addresse (https://github.com/dmacvicar/terraform-provider-libvirt/pull/753)

## Domain:

- Fix cannot find machine type after Terraform destroy (https://github.com/dmacvicar/terraform-provider-libvirt/pull/726)

## Multi-arch support

- Skip display setup for aarch64 as well ( https://github.com/dmacvicar/terraform-provider-libvirt/pull/743)

# contributors:
 
@vmorris @itwars @dancysoft @Xachman @dirkmueller @MalloZup @johscheuer

# TODOS:

- [ ] run tests locally
- [ ] update obs package

**Comment by vmorris** [comment]
I was hoping to make the contributor list with my fix for #703 :sweat_smile:

**Comment by MalloZup** [comment]
@vmorris  oh sorry, adding you now!

**Comment by dmacvicar** [comment]
With https://github.com/dmacvicar/terraform-provider-libvirt/pull/785 I have made the testsuite pass again.

* I have the suspicion that https://github.com/dmacvicar/terraform-provider-libvirt/pull/740 is the wrong fix. So we may need more time to release.

**Comment by MalloZup** [comment]
@dmacvicar  I think we could remove all the release blocker for a 0.6.3 afaik.

We need on the `pkging` side to update the provider to be installed on the new path  for terraform v13. But for a github release isn't mandatory, only for the rpm pkgs etc.

**Comment by MalloZup** [comment]
I'm closing this since we discussed a bit. no need to track it
