### ISSUE TITLE
Terrafrom 0.13.1 modules can't find libvirt provider

### ISSUE THREAD

**Issue by tigerpaws2** [dmacvicar/terraform-provider-libvirt#779]
##  System Information
Polywell  i7, 32Gb, 500Gb NMVE drive

### Linux distribution

```Fedora 31 Server  ```

### Terraform version
```
Terraform v0.13.1
```

### Provider and libvirt versions
```
/demo3/.terraform/plugins/registry.terraform.io/hashicorp/libvirt/0.6.2/linux_amd64/terraform-provider-libvirt 0.6.2+git.1585292411.8cbe9ad0
Compiled against library: libvirt 4.1.0
Using library: libvirt 5.6.0
Running hypervisor: QEMU 4.1.1
Running against daemon: 5.6.0
``` 
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [x] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [ ] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question
This is a simple situation. If you are using terraform 0.13.1, and you install the libvirt provider as described in the README, it works fine until you try to use a module that needs libvirt. At that point, terraform can no longer find the libvirt provider. 
```
[mike@polly demo3]$ tf13 init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed dmacvicar/libvirt v0.6.2
- Using previously-installed hashicorp/template v2.1.2
- Finding latest version of hashicorp/libvirt...

Error: Failed to install provider

Error while installing hashicorp/libvirt: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/libvirt
```

### Setup

I copied the libvirt provider to the correct place as specified in the README for terrafrom 13 on this site. That works fine as long as there is no module.  After some pain, I realised that terraform copied the providers into each project in the .terraform directory, so I manually copied:
```
.terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.2/linux_amd64/terraform-provider-libvirt
```
to
 ```
.terraform/plugins/registry.terraform.io/hashicorp/libvirt/0.6.2/linux_amd64/terraform-provider-libvirt
```

and that made everything work again. 

### Steps to Reproduce Issue
Install the libvirt provider for terraform 0.13.1
Generate a main.tf file that has a module that requires libvirt

An example is at https://gitlab.com/tigerpaws/terraform-libvirt-presentation: demo3
___
## Additional information:

This seems a bug in terraform 0.13.1 to me. However, additional information in the README might be helpful, either that, or have the provider installed in the terrform registry.

**Comment by tigerpaws2** [comment]
Seems this problem and solution were already described in #747. Sorry about that. Should this ticket be closed?

**Comment by MalloZup** [comment]
@tigerpaws2  no worries I will close. 
  :rose: have fun

**Comment by hhue13** [comment]
Hello @MalloZup and @tigerpaws2 ,
I'm facing exactly the same issue when running on terraform 0.14.4 using the provider 0.6.3 build from git (last commit applied is: 2b60d7626ff8baa32d784a0b07d51ef195f1b936).

```
[hhuebler@hhuelinux rhcos]$ tf init
Initializing modules...
- ignition_module in modules/ignition

Initializing the backend...

Initializing provider plugins...
- Finding dmacvicar/libvirt versions matching "0.6.3"...
- Finding latest version of hashicorp/libvirt...
- Installing dmacvicar/libvirt v0.6.3...
- Installed dmacvicar/libvirt v0.6.3 (unauthenticated)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/libvirt: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/libvirt

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

[hhuebler@hhuelinux rhcos]$ tf providers

Providers required by configuration:
.
├── provider[registry.terraform.io/dmacvicar/libvirt] 0.6.3
└── module.ignition_module
    └── provider[registry.terraform.io/hashicorp/libvirt]

[hhuebler@hhuelinux rhcos]$ tf version
Terraform v0.14.4
```
 Couldn't figure out why the provider `hashicorp/libvirt` is requested here. I tried to copy the provider as suggested by @tigerpaws2  above but that did not fix the problem.

**Comment by hhue13** [comment]
Found a work-around of this now. Need to add the provider block in the module itself:
```
terraform {
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "0.6.3"
    }
  }
}

provider "libvirt" {
    uri = "qemu:///system"
}
```
although that should not be required as per https://learn.hashicorp.com/tutorials/terraform/module-create?in=terraform/modules which states:

```
You will notice that there is no provider block in this configuration. When Terraform processes a module block, it will inherit the provider from the enclosing configuration. Because of this, we recommend that you do not include provider blocks in modules.
```
A bug in terraform?
