### ISSUE TITLE
Terraform provider registry

### ISSUE THREAD

**Issue by terrycain** [dmacvicar/terraform-provider-libvirt#781]
Do you have any plans to push this provider to the official Terraform provider registry? Registry [here](https://registry.terraform.io/)

For what its worth, its pretty easy to do, took me around 10mins for one I wrote. Pretty much you just copy their github action, setup a gpg key and then make a tag :smile:

**Comment by MalloZup** [comment]
HI@terrycain!  that is not pretty much easy at is seems , since here the scope is more ABI/API of libvirt. for more details check this 

https://github.com/dmacvicar/terraform-provider-libvirt/issues/747#issuecomment-678575669

closing as duplicate
