### ISSUE TITLE
mounting host's volume to virtual machine

### ISSUE THREAD

**Issue by laimison** [dmacvicar/terraform-provider-libvirt#782]
Hi,

Is there a way to mount directory to virtual machine from host using terraform-provider-libvirt for KVM?

I have to add this `filesystem` block after Terraform provisoned resources:

```
<domain type='kvm'>
  ....
  <devices>
    ....
    <filesystem type='mount' accessmode='passthrough'>
      <source dir='/app/prod/kvm/shared'/>
      <target dir='test'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </filesystem>
  </devices>
  ....
</domain>
```

If provider is not ready yet for this, any suggestions by using `local-exec` or any other tool?

At least when I run `terraform plan` after these additional change, the state is happy and tells me `No changes. Infrastructure is up-to-date.`

**Comment by MalloZup** [comment]
hi @laimison  you can add this with `xslt` xml block https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/website/docs/r/volume.html.markdown#altering-libvirts-generated-volume-xml-definition and an example here:
https://github.com/dmacvicar/terraform-provider-libvirt/tree/master/examples/v0.13/xslt or https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/modules/drbd_node/shareable.xsl https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/libvirt/modules/drbd_node/shareable.xsl


If you want to use still `local-exec` like somehow with `virsh` or whatever fit for you, you can add  a trigger

```

resource "null_resource" "local-exec" {
  count = 1
  triggers = {
    drbd_ids = libvirt_domain.drbd_domain[count.index].id      // id of what you expect etc
  }
```

**Comment by laimison** [comment]
Hi @MalloZup thanks. I have just started to learn KVM three days ago. So solved in a bit different way which could have downsides that I'm not aware of. I will look on how you suggest to solve.

My way is this:

main.tf

```
resource "libvirt_domain" "eranet-node-1" {
  ....
  provisioner "local-exec" {
    command = "virsh attach-device node-1 filesystem-node-1.xml --config && virsh destroy node-1 --graceful && virsh start node-1"
  }
}
```

filesystem-node-1.xml

```
<filesystem type='mount' accessmode='passthrough'>
  <source dir='/app/prod/kvm/shared'/>
  <target dir='test'/>
  <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
</filesystem>
```

cloud-init.cfg

```
....
runcmd:
  - ['sh', '-c', 'mkdir -p /app']
  - ['sh', '-c', 'echo "test /app 9p _netdev,trans=virtio,version=9p2000.L 0 0" >> /etc/fstab']
```

**Comment by MalloZup** [comment]
on `kvm` you can pass `remote uri` also in virsh.

So in different layers you can run remote:

1) on `terraform-libvirt` : https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/examples/v0.13/boot/libvirt.tf#L13
```"qemu+ssh://foo@myserver-name/system"```
  this can spawn libvirt instance on remote KVM server from X bastion server

2) if you want to use `local-exec` , you could pass remote with -c optin
```virsh -c test:///default list```

3) you can also use `remote-exec` as last ressort https://www.terraform.io/docs/provisioners/remote-exec.html

**Comment by MalloZup** [comment]
you need to configure your remote kvm server to accept remote connections etc. for that there is on web doc

**Comment by laimison** [comment]
That's cool. terraform-provider-libvirt can manage it perfectly and even few options available. Many thanks for your great work. 

Off topic, but in terms of final goal to have a shared directory between host and guest, I decided not to go ahead, because of guest issues writing to 9P share https://serverfault.com/questions/342801/read-write-access-for-passthrough-9p-filesystems-with-libvirt-qemu . So it's nothing to do with Terraform. This is 9P maintenance issue or compatibility with Ubuntu 18.04. Possibly a bug in this filesystem mechanism.
