### ISSUE TITLE
libvirt_network modification fails

### ISSUE THREAD

**Issue by dosmanak** [dmacvicar/terraform-provider-libvirt#784]
### Linux distribution

``` Ubuntu.. ```

### Terraform version

Terraform v0.12.28

### Provider and libvirt versions

terraform-provider-libvirt 0.6.1+git.1578064534.db13b678
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Running hypervisor: QEMU 2.11.1
Running against daemon: 4.0.0

___

## Checklist

- [x] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [X] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [X] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [X] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

I have setup libvirt_network and then removed the domain option, because I decided I don't want the libvirt dhcp server to send domain and the network should be only local. But the network update was not succesful. It seems like a general bug, because the network update should be possible and the virsh command  `net-edit --network herring-app-real` and then destroy/start works.

I got error:
```
Error: Error when updating domain in herring-app-real: virError(Code=35, Domain=19, Message='network_update_xml:1: Document is empty
(null)
^')
```

### Setup
```diff 
resource "libvirt_network" "app-real" {
   name = "${var.cluster_name}-app-real"
   autostart = true
   mode = "none"
-  domain = "app-real"
   addresses = ["123.456.789.0/24"]
   dhcp {
     enabled = true
   }
   dns {
     enabled = false
   }
 }
```

### Steps to Reproduce Issue

Create libvirt_network resource with domain set apply terraform, then remove the domain and apply terraform.

**Comment by MalloZup** [comment]
@dosmanak  hi thx for issue.

I do think is kind corner case but we should handle this better. thx for reporting!

**Comment by MalloZup** [comment]
@dosmanak  So I did some research on this. It might seem simple but is not.

AFAIK, from what I get of the Libvirt upstream API:

The virsh net-update use same API as here in golang.

https://wiki.libvirt.org/page/Networking#virsh_net-update
```
The config items in a network that can be changed with virsh net-update are:
   ip-dhcp-host
   ip-dhcp-range (add/delete only, no modify)
   forward-interface (add/delete only)
   portgroup
   dns-host
   dns-txt
   dns-srv

```

I did even tried to do
```
virsh net-edit foo-app-real 
Network foo-app-real XML configuration not changed.
```
And remove the `domain` but didn't worked for me.

I do think, if Updating a "NetworkDomain` isn't supported by libvirt we could force the `network` to be recreated from scratch ( there is a parameter in terraform called ForceNewResource, right now is on false").

I think that this is the only way to do this otherwise 

@dmacvicar  are you familiar with such Network operations?

**Comment by MalloZup** [comment]
ok just to update..
I do think the whole feature was implemented wrong at that time.

We can't update a `domain` attribute from network. this is not supported

`main=19, Message='Operation not supported: can't update 'domain' section of network 'foo-app-real2'')`

```
terraform apply
libvirt_network.app-real2: Refreshing state... [id=3a7e9d63-0602-4b58-aef0-b8c9c000cab5]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # libvirt_network.app-real2 will be updated in-place
  ~ resource "libvirt_network" "app-real2" {
        autostart = true
        bridge    = "virbr3"
      ~ domain    = "foo" -> "bro"
        id        = "3a7e9d63-0602-4b58-aef0-b8c9c000cab5"
        mode      = "none"
        name      = "foo-app-real2"

        dhcp {
            enabled = true
        }

        dns {
            enabled    = false
            local_only = false
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

libvirt_network.app-real2: Modifying... [id=3a7e9d63-0602-4b58-aef0-b8c9c000cab5]

Error: Error when updating domain in foo-app-real2: virError(Code=84, Domain=19, Message='Operation not supported: can't update 'domain' section of network 'foo-app-real2'')

  on main.tf line 4, in resource "libvirt_network" "app-real2":
   4: resource "libvirt_network" "app-real2" {
```

**Comment by dosmanak** [comment]
Hello. Thank you for pointing the libvirt wiki page. It is possible this is
really not supported operation. In that case the whole network must be
recreated. I have done that using terraform taint. But as I recreated all
domains I am not sure if the recreation of the network does mean it is
necessary to recreate all domains using that particular network.

I really appreciate such quick investigation! Thank you.

Dne so 26. 9. 2020 20:02 uživatel Dario Maiocchi <notifications@github.com>
napsal:

**Comment by MalloZup** [comment]
@dosmanak  ok thx for feedback. 

Yes I do think that you need to recreate all domains. I think we can force recreation in that case.


Afaik, I didn't tested, but I believe that if one force creation of network , also the whole domain will be recreated because they are dependent of it afai.

Or you should create a dependency var on hcl level , so that Terraform can manage dependencies and retrigger needed resources.

I will send shortly a PR so you can test this, when you want, no hurry. :grin:

**Comment by dosmanak** [comment]
It seems the issue is resolved. I don't use terraform libvirt provider anymore so I close it now. Thank you.
