### ISSUE TITLE
[Network] Error defining libvirt network: [Code-9] [Domain-19] operation failed: network 'terraform-network' already exists

### ISSUE THREAD

**Issue by MalloZup** [dmacvicar/terraform-provider-libvirt#82]
## Description:

When the network managed by terraform exists already, and you want to spawn machines with terraform-libvirt, you get an error:

``` console
Error applying plan:

1 error(s) occurred:

* libvirt_network.network: Error defining libvirt network: [Code-9] [Domain-19] operation failed: network 'terraform-network' already exists with uuid 7a8d2cae-9e60-4863-977c-2f7d07486b36 -   <network>
      <name>terraform-network</name>
      <domain name="tf.local"></domain>
      <bridge stp="on"></bridge>
      <forward mode="nat">
          <nat>
              <port start="1024" end="65535"></port>
          </nat>
      </forward>
      <ip address="192.168.127.1" prefix="24" family="ipv4">
          <dhcp>
              <range start="192.168.127.2" end="192.168.127.254"></range>
          </dhcp>
      </ip>
  </network>

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**machines are are setup correctly and network is ok**
## How to reproduce:

Take a main.tf from sumaform: https://github.com/MalloZup/sumaform/blob/master/main.tf.libvirt-testing.example

**Comment by inercia** [comment]
In your opinion what would be the expected behaviour?

**Comment by MalloZup** [comment]
@inercia  imho the expected behaviour should be to not have an error.

**Comment by inercia** [comment]
@MalloZup Correct me if I'm wrong, but I think we will always get an error when a resource that is expected to be managed by Terraform already exists, right? For example, if a VM is already there, Terraform will abort the whole execution, and that is the reeason why, if you want to import some existing infrastructure, you should use the [import command](https://www.terraform.io/docs/import/)...

For me the concerning sentence in your report is when you say `"machines are are setup correctly and network is ok"`. So you mean Terraform did not abort, right?

**Comment by MalloZup** [comment]
@inercia discusssing it, i think that is an issue  only when you do not think in terraform way and you have not much exp with the tool. I think we can close and concentrate to others stuff. When you have time, please check the other issue wirh disks. Feels free to ping me if you need explanations
