### ISSUE TITLE
Establish IP addresses once they are assigned

### ISSUE THREAD

**Issue by inercia** [dmacvicar/terraform-provider-libvirt#85]
When using managed networks we can currently specify the IP address manually, or let `dnsmasq` get an IP from the DHCP pool automatically. The problem with the automatic assignation is that it does survive reboots, so clusters can get messed up easily.

We could add an option (or do it automatically) for _a)_ getting  the IP address assigned by `dnsmasq` to the VM and _b)_ add the _IP-MAC_ mapping to the the managed network definition.

**Comment by flavio** [comment]
I think this is the wrong solution to our internal problem. I've already some work in progress to switch our k8s configuration from using IP to using hostnames. Hostnames are always resolved, despite the cluster/dnsmasq being rebooted.

I would close this issue unless you think that's not a good workaround.

**Comment by inercia** [comment]
The problem is that hostnames cannot always be used. For example, when configuring `etcd` in a kubernetes cluster, we should set something like `ETCD_LISTEN_CLIENT_URLS="http://10.17.3.166:2379"`, but this IP address, `10.17.3.166`, will not neccessarily be assigned to the `etcd0` host after a reboot, so the whole cluster would not come up... we are forced to use `ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"`, not the safest option...

**Comment by flavio** [comment]
As agreed we are going to solve this issue in a different way inside of our k8s-terraform project.
