### ISSUE TITLE
The "Using the provider" section of README.md is wrong for recent versions of terraform

### ISSUE THREAD

**Issue by SCDealy** [dmacvicar/terraform-provider-libvirt#858]
### Linux distribution

Ubuntu 18.04 LTS but issue applies to all distros

### Terraform version
1.0.0

### Provider and libvirt versions

0.6.3/linux_amd64/terraform-provider-libvirt b01ffe296c84d0c15ccc6625bfde1597f01cc053
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Running hypervisor: QEMU 2.11.1
Running against daemon: 4.0.0
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [ X] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

If one follows the instructions in the "Using the provider" section of README.md, using the latest version of terraform (1.0.0 though this presumably applies to any version 0.13 or later), the provider will not be found.

The needed changes to make the README.md example work can be found by following the link in the table of contents for "Migrating to terraform v13". Unfortunately for new users, they are not "migrating to" anything, so this document appears irrelevant and they can waste a lot of time figuring out on their own what the problem is. As a new user to both terraform and the libvirt provider, this killed about six hours (though now I know the basics of how to debug terraform, both the older and new provider implementation, search paths, and a host of other likely useful things that I would have preferred to learn later).

### Steps to Reproduce Issue

Follow "Using the provider" instructions / example in terraform-provider-libvirt README.md

**Comment by vmorris** [comment]
It may not be correct, but I struggled through this and found a way forward yesterday:
https://github.com/dmacvicar/terraform-provider-libvirt/issues/838#issuecomment-864451291

**Comment by SCDealy** [comment]
To make it easier for people who get this far, below are the three different ways you can add the provider that worked for me with terraform 1.0.0

```
terraform {
   required_version = ">= 1.0"
   required_providers {
      # This is works, using this location:
      #
      #    ~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64/terraform-provider-libvirt
      #
      # which is the recommendation for terraform-provider-libvirt when
      # migrating to Terraform 0.13 as given here:
      #
      #    https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/docs/migration-13.md
      # 
      libvirt = {
         source = "dmacvicar/libvirt"
         version = "0.6.3"
      }

      # This works with the provider in a zip file placed here:
      #
      #    ~/.terraform.d/plugins/localdomain/provider/libvirt/terraform-provider-libvirt_0.6.3_linux_amd64.zip
      #
      #libvirt = {
      #   source = "localdomain/provider/libvirt"
      #   version = "0.6.3"
      #}

      # This works with the provider placed here:
      #
      # ~/.terraform.d/plugins/localdomain2/provider/libvirt/0.6.3/linux_amd64/terraform-provider-libvirt
      #
      #libvirt = {
      #   source = "localdomain2/provider/libvirt"
      #   version = "0.6.3"
      #}
   }
}

provider "libvirt" {
    uri = "qemu:///system"
}

resource "libvirt_domain" "terraform_test" {
  name = "terraform_test"
}

```

**Comment by dmacvicar** [comment]
From now (master) on the official way to install the provider is from the terraform provider registry. Give it a try to what is described in the pre-release:

https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v0.6.9-pre3
