### ISSUE TITLE
Establish a version

### ISSUE THREAD

**Issue by flavio** [dmacvicar/terraform-provider-libvirt#87]
Right now this project is totally unversioned. I think it's time for us to start to tag each significant release. This will make packaging easier on our side, will make it easier to understand which version is in place and will be more respectful of the human civilization.

I propose to start with version `0.1.0`.

@inercia, @dmacvicar, @moio: what do you think about it?

**Comment by moio** [comment]
Additionally I would remove the EXPERIMENTAL tag from the project's title.

This might not be finished or super stable, but it's definitely useful and beyond the "experiment" phase by now IMO.

**Comment by mssola** [comment]
I agree. We should tag `0.1.0` and remove the `EXPERIMENTAL` tag.

**Comment by dmacvicar** [comment]
Removed the experimental tag and warnings.

Do we agree to use semver?

**Comment by MalloZup** [comment]
We can close this?

**Comment by flavio** [comment]
Nope, until we tag a release. Maybe we can do that after closing the open PRs

**Comment by monstermunchkin** [comment]
Done.

**Comment by MalloZup** [comment]
![party](https://media.giphy.com/media/6nuiJjOOQBBn2/giphy.gif)
