### ISSUE TITLE
Offering a helping hand

### ISSUE THREAD

**Issue by lfarnell** [dmacvicar/terraform-provider-libvirt#9]
Firstly, i just want to say i've been looking for a qemu provider for Terraform for some time now and you are a life saver! Now, i've never programmed in golang before so i wouldnt be of much help there, but if you can think of any other way i can help with this project(ie documentation, tutorials etc, by all means let me know. I would be more then happy to help.

**Comment by dmacvicar** [comment]
Thank you for your interest in the project. I started this to improve my skills in Devops tools and Golang at the same time.

You can make Pull Request with documentation improvements, open issues for features that you really miss from real-life usage (no "it would be cool to..." stuff), contribute examples, and make sure tests, examples and docs are up to date with the documentation. Just make everything via Pull requests.

About code, I am keeping important missing features as open issues, so if you feel brave enough you can try. It is frightening at the beginning but later it is very mechanical (resource, new, delete, modify, etc + tests).

**Comment by dmacvicar** [comment]
Closing, see you in a future PR!
