### ISSUE TITLE
Error: missing expected [     After upgrade from provider version 0.6.10 to 0.6.11

### ISSUE THREAD

**Issue by cyberworm54** [dmacvicar/terraform-provider-libvirt#901]
### Linux distribution

``` Fedora 35 ```

### Terraform version

```sh
terraform -
v
Terraform v0.13.7
+ provider registry.terraform.io/dmacvicar/libvirt v0.6.11
+ provider registry.terraform.io/hashicorp/template v2.2.0

```

### Provider and libvirt versions

```sh
+ provider registry.terraform.io/dmacvicar/libvirt v0.6.11
```
___

## Checklist

- [x] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [x] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [x] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [x] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

## Description of Issue/Question

provider registry.terraform.io/dmacvicar/libvirt v0.6.11 gives an error stating 

Error: missing expected [

### Steps to Reproduce Issue
terraform plan
```
Error: missing expected [


2021/11/09 04:37:31 [ERROR] eval: *terraform.EvalReadState, err: missing expected [
2021/11/09 04:37:31 [ERROR] eval: *terraform.EvalSequence, err: missing expected [
2021/11/09 04:37:31 [ERROR] eval: *terraform.EvalReadState, err: missing expected [
2021/11/09 04:37:31 [ERROR] eval: *terraform.EvalSequence, err: missing expected [
2021/11/09 04:37:31 [ERROR] eval: *terraform.EvalReadState, err: missing expected [
2021/11/09 04:37:31 [ERROR] eval: *terraform.EvalSequence, err: missing expected [
```

___
## Additional information:

Do` you have SELinux or Apparmor/Firewall enabled? Some special configuration? no
Have you tried to reproduce the issue without them enabled? n/a

**Comment by sspreitzer** [comment]
It turned out in my case, that changing the attribute type of `attributes.cpu` from object `{}` to an array of objects `[{}]` in the state file, solved the problem.
Eg.
```json
{
  "cpu": {"mode": "host-passthrough"}
}
```

To:
```json
{
  "cpu": [ {"mode": "host-passthrough"} ]
}
```

This seems to be a breaking change in the state syntax, which is not converted when upgrading the provider.

**Do not forget to backup your state file before you edit it.**

**Comment by cyberworm54** [comment]
Yep, that worked. Thank you so much for the help ! @sspreitzer

**Comment by sspreitzer** [comment]
@dmacvicar fyi

**Comment by scabala** [comment]
@cyberworm54 
I think this is just expected as this proivder is not yet 1.x - breaking errors might happen. Could you close the issue?
