### ISSUE TITLE
Working patchset Ceph/RBD volume support

### ISSUE THREAD

**Issue by gxben** [dmacvicar/terraform-provider-libvirt#905]
@dmacvicar I do have working patchset for minimalistic Ceph/RBD support for distributed volumes usage.

As Ceph/RBD configuration can be quite complex and exhaustive, XSLT could be considered but is quite a pain to offer.

Alternatively, my patch uses the following assumptions:
* no pool creation/deletion support, we only care about volumes
* pool configuration is left to libvirt's sysadmin, which is responsible for designing its XML configuration accordingly and uses **virsh pool-define** to set it up correctly
* there will be a few rbd specific schema updates (addition, no breaking changes) to properly declare the rbd pool/host/port to be used.
* volume creation and remote upload is not fully support by libvirt as of now (or so it seems), so my alternative proposal is to ensure we have a working clone for volume creation, i.e. use an already existing base_volume (up to libvirt's sysadmin to have it deployed beforehand, as a cloudimg base template or whatever the name) as source.

Is it ok with you if I submit a pull request for that (as much as possible I'd avoid keeping it as a fork) ?

**Comment by scabala** [comment]
Hi @gxben,
would you still be interested in creating PR with this patchset?

**Comment by dmacvicar** [comment]
I am only interested if it is something to support only native libvirt functionality. I don't want to have features/logic in the provider. If that is the case, it would be better to work with libvirt developers.

**Comment by scabala** [comment]
As I see it, RB storage pool is supported by libvirt natively - https://libvirt.org/storage.html#rbd-pool.
From what @rbbratta wrote, I concluded that changes needed are only on provider level to enable use of libvirt's native functionality.

So I think this would be big but rather welcomed feature, right?
