### ISSUE TITLE
Problem creating bridged network

### ISSUE THREAD

**Issue by deasmi** [dmacvicar/terraform-provider-libvirt#92]
```
resource "libvirt_network" "vm_network" {
  name = "vm_network"
  domain = "xx.xx.com"
  mode = "bridge"
  bridge = "br3"
}
```

gives the following libvirt error

```
* libvirt_network.vm_network: Error defining libvirt network: [Code-27] [Domain-19] XML error: The <nat> element can only be used when <forward> 'mode' is 'nat' in network vm_network -   <network>
      <name>vm_network</name>
      <domain name="london.zelotus.com"></domain>
      <bridge name="br3" stp="on"></bridge>
      <forward mode="bridge">
          <nat>
              <port start="1024" end="65535"></port>
          </nat>
      </forward>
  </network>
```
I've been looking at the source but sadly do not know go very well ( at all ) so haven't got very far.
I am assuming i need to pass an empty NAT block but can't work out the format ?
Documentation is not very forthcoming on NAT, so I'll volunteer to update or add some examples.

Thanks

**Comment by deasmi** [comment]
I now understand why this is happening.
The default XML for a network includes 

```
<nat>
      <port start='1024' end='65535'/>
</nat>
```
Which won't work for bridge connection.

#93 is an extremely naive attempt by me to fix this. It does cause the network to be created but terraform crashes out. This is not beyond my current ability in go or terraform to diagnose. 

And its new years eve.

**Comment by MalloZup** [comment]
@deasmi  so your fix got merged. can we close the issue?

**Comment by deasmi** [comment]
@MalloZup Please do, sorry missed your reply

**Comment by MalloZup** [comment]
@deasmi thx, no pb

@flavio @moio  i would propose to close this . ( pinging moio since this is ref. on sumaform)
