### ISSUE TITLE
Volume resizing causes kernel panic on first boot

### ISSUE THREAD

**Issue by markcaudill** [dmacvicar/terraform-provider-libvirt#948]
### Linux distribution

Workstation

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

Target Host

```console
$ ssh hermes lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
No LSB modules are available.
```

### Terraform version

```console
$ terraform version
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/dmacvicar/libvirt v0.6.14
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Provider and libvirt versions

```console
$ cd .terraform/providers/registry.terraform.io/dmacvicar/libvirt/0.6.14/linux_amd64
/home/mark/src/infra/volume_size_test/.terraform/providers/registry.terraform.io/dmacvicar/libvirt/0.6.14/linux_amd64

$ ./terraform-provider-libvirt_v0.6.14 -version
./terraform-provider-libvirt_v0.6.14 0.6.14
```
___

## Checklist

- [ ] Is your issue/contribution related with enabling some setting/option exposed by libvirt that the plugin does not yet support, or requires changing/extending the provider terraform schema?

  - [ ] Make sure you explain why this option is important to you, why it should be important to everyone. Describe your use-case with detail and provide examples where possible.
  - [ ] If it is a very special case, consider using the _XSLT_ support in the provider to tweak the definition instead of opening an issue
  - [ ] Maintainers do not have expertise in every libvirt setting, so please, describe the feature and how it is used. Link to the appropriate documentation

- [x] Is it a bug or something that does not work as expected? Please make sure you fill the version information below:

### Setup

```terraform
terraform {
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "0.6.14"
    }
  }
}

provider "libvirt" {
  uri = "qemu+ssh://vmmgr@hermes/system"
}

resource "libvirt_volume" "debian11" {
  name   = "debian11"
  pool   = "default"
  source = "https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2"
}

# OS Volume
resource "libvirt_volume" "os_volume" {
  base_volume_id = libvirt_volume.debian11.id
  name           = "os_volume"
  pool           = "default"
  size           = 10737418240 # 10GiB
}

# VM
resource "libvirt_domain" "vm" {
  autostart  = true
  memory     = 2048
  name       = "test-host-01"
  qemu_agent = true
  running    = true
  vcpu       = 2

  console {
    target_port = "0"
    target_type = "virtio"
    type        = "pty"
  }

  disk {
    volume_id = libvirt_volume.os_volume.id
  }

  network_interface {
    network_name   = "default"
    hostname       = "test-host-01"
    wait_for_lease = true
  }
}
```

### Steps to Reproduce Issue

1. Run `terraform apply` results in a hung VM with a kernel panic.

    ![image](https://user-images.githubusercontent.com/261361/166684086-55ee99b5-f999-4666-8d04-9974f3866150.png)

2. I can manually reset the VM and it then boots normally and comes online.

3. If I remove/comment out the `size` parameter of `libvirt_volume.os_volume` then the initial `terraform apply` brings the VM online properly.

    ```terraform
    resource "libvirt_volume" "os_volume" {
      base_volume_id = libvirt_volume.debian11.id
      name           = "os_volume"
      pool           = "default"
      #size           = 10737418240 # 10GiB
    }
    ```

___
## Additional information:

Do you have SELinux or Apparmor/Firewall enabled? Some special configuration?
Have you tried to reproduce the issue without them enabled?

**Comment by sk4zuzu** [comment]
Hi @markcaudill

This problem is unrelated to the provider itself.

Here's some bug report from Ubuntu https://bugs.launchpad.net/ubuntu/+source/cloud-initramfs-tools/+bug/1123220 which is exactly the same issue. I believe there are two ways to fix it, it's either as suggested in the report (you need to add **serial** console) or you can remove it from from grub config completely (all stuff containing "ttyS").

**Comment by markcaudill** [comment]
@sk4zuzu this is very helpful! Thanks!

**Comment by nova1prime98** [comment]
works perfectly
```
resource "libvirt_domain" "machine" {
  console {
    type        = "pty"
    target_port = "0"
    target_type = "serial"
  }
}
```
